### ISSUE TITLE
configutation error makes axiom fails to ssh

### ISSUE THREAD

**Issue by praveenroot03** [pry0cc/axiom#108]
I have few instances which is tied to private VPC, so that axiom adds additional private IP field to .sshconfig. So it makes ssh configuration errors in while connecting to instance. I tried re-configuring it manually but axiom updates the config as I run the command

Here is my `.sshconfig`

Host server
	HostName <private IP>
<public IP>
	User op
	Port 2266

Host recon
	HostName <private IP>
<public IP>
	User op
	Port 2266

Host jackson14
	HostName <public IP>
	User op
	Port 2266

NOTE: jackson14 was created using axiom others are my old instances

**Comment by paulocamboim** [comment]
Did you get it working? I'm having problems to connect to the droplet.

# Error on axiom-connect
me@xx:~/go/bin$ axiom-connect 
/home/me/.axiom/.sshconfig: line 18: Bad configuration option: xx.xx.xx.107
/home/me/.axiom/.sshconfig: terminating, 1 bad configuration options

# sshconfig contents
me@xx:~/go/bin$ cat /home/me/.axiom/.sshconfig
Host recon
	HostName 10.124.0.2
xx.xx.xx.107
	User op
	Port 2266

# axiom-ls output
The ls command seems off, not sure if it's only when printing on the screen

me@xx:~/go/bin$ axiom-ls
Instance              IP                   Region                Memory       $/M
recon                 10.124.0.2      xx.xx.xx.107  sfo3               s-1vcpu-1gb  5




Thanks

**Comment by pry0cc** [comment]
Have you updated to the latest version?

axiom-update

Thanks,

pry0cc

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by paulocamboim** [comment]
Yes, i did it. But still got the same error.
What I'm trying now is going from zero. I removed the **.axiom** folder and running axiom-configure.
I will let you know in this thread how it go.

Just an idea, it would be nice if we could use an already existing image that is created on Digital Ocean when executing **axiom-configure**

Thanks!

**Comment by paulocamboim** [comment]
I still have the same issue.
I'm using Ubuntu 20.04

**Comment by michael1026** [comment]
I was running into this issue as well. I updated Axiom, then re-configured it using `axiom-configure`. Takes a while, but seems to have fixed the issue.

**Comment by praveenroot03** [comment]
As @michael1026 said `axiom-update` and `axiom-configure` resolved the issue. Guess the new commit has resolved the issue. Also, the new feature to select the region is awesome.

**Comment by sumgr0** [comment]
I've come back to axiom after a while and facing the same error message when connecting to the box created by axiom. I've already tried the suggested axiom-update and axiom-configure, but its not resolved on the Mac OS Big Sur...

Any pointers?
