### ISSUE TITLE
The installation is not stopping

### ISSUE THREAD

**Issue by sillydadddy** [pry0cc/axiom#111]
I am trying to install axiom in Ubuntu 20.04 .
It needed "apt-get install libnotify-bin" to start .

After that the  installation goes on for hours .In the the digital ocean activity tab its showing like this 
![image](https://user-images.githubusercontent.com/61352069/94357490-e7ec4100-00b6-11eb-9b4d-94c54f32eaa6.png)
more than 20 times 

thanks
siLLyDaddy

**Comment by k-sau** [comment]
Have you noticed the reason why the installation is failing? Are you getting the same nuclei installation error(
https://github.com/pry0cc/axiom/issues/76#issuecomment-699438363)

**Comment by pry0cc** [comment]
Yepp, if you don't watch it and ctrl+c after a few cycles then something is definitely off.
