### ISSUE TITLE
Clean axiom-configure does not include interlace install needed to use axiom-scan.

### ISSUE THREAD

**Issue by matglas** [pry0cc/axiom#118]
**Problem:**
After installing axiom and running axiom-scan for the first time it can't find `interlace`.

**Solution:**
Add interlace install to axiom-configure or provide a notice to install interlace.

Partly copied from your setup in the packer build.
```
git clone https://github.com/codingo/Interlace.git /tmp/interlace 
cd /tmp/interlace && sudo python3 setup.py install
``` 

Note this was run on a Parrot OS machine.

**Comment by pry0cc** [comment]
Dope!

**Comment by bughunter0xff** [comment]
Still after manually installing Interlace, i am getting this importlib.metadata.PackageNotFoundError: Interlace

**Comment by K4r1it0** [comment]
> Still after manually installing Interlace, i am getting this importlib.metadata.PackageNotFoundError: Interlace

same here
