### ISSUE TITLE
Feature Request : zsh shell customizations sync

### ISSUE THREAD

**Issue by tavdog** [pry0cc/axiom#12]
Currently the backup/sync functionality only syncs non image default values so any customizations to the shell are not saved.  It would be nice to have a flag to backup and restore changes to the shell and other dot files.

**Comment by pry0cc** [comment]
Awesome idea! 

I was thinking about this, what files should we add? 

.zshrc
.oh-my-zsh
.vim
.vimrc
.config
.tmux.conf

What do you think?

**Comment by tavdog** [comment]
All of those sound good.  ~/.gitconfig too for sure.  Any ideas for a way to specify which files we want backed up ?

**Comment by tavdog** [comment]
I'm a little bit confused about the whole backup/sync process.  Since the backup process backs up to the instance name, if I rm the original instance then want to axiom-init a new instance and restore the original to the new one, they now have different instance names so a sync won't bring the new instance back to the state of the original instance. I guess I could just rename the box directory to the name of the new instance ?

**Comment by pry0cc** [comment]
So I’ve been thinking of scrapping the sync script,it’s definitely confusing.

Give this one liner a go, where yourbox is a machine that has been backed up and is not live already. 

```
axiom-init yourbox —restore=yourbox && axiom-ssh yourbox —tmux && axiom-backup yourbox && axiom-rm yourbox
```

**Comment by pry0cc** [comment]
https://github.com/pry0cc/axiom/commit/bce8b76a58fbc711b25dee61972aef9a323c356e

New commit that enables dotfile backup by default as well as the go directory backup!

Please give it a go and tell me how it works, and don't forget to `axiom-update`.

If it works cool - we can close this issue :)

**Comment by pry0cc** [comment]
Ok I'm beginning to think this is not the best way of doing this.

Some of these git files are taking a very long time, thinking maybe making a tar archive and then transferring that would be better. For both go and .*.

**Comment by tavdog** [comment]
I think the go backup should maybe be separate from the .dot files.  It creates a ~350MB size file.  Maybe tar'ing up the files from find ~op -type f -name ".*" -maxdepth 1
 
I see you how you can give a name to an instance so then it's easy to run a restore on the instance when it's got the same name as the old backed up instance.  But axiom-init yourbox —restore=yourbox  didn't do a restore of the backed up files. I had to do an axiom-restore after the instance was up and running. Not a big deal just fyi

But the only reason I wanted to do .gitconfig was because: with the git branch prompt set to ON, cd'ing into lists/seclists takes about 30 seconds before it responds.  So kind of annoying.

**Comment by pry0cc** [comment]
OK.

So I've gone through completely and redone the backup and the restore scripts.

It is pushed to master, I've redone how I'm pulling and pushing dotfiles, and I'm using a "files-from" directive, you can access this file in ~/.axiom/boxes/backup-files.txt, whatever is in this will be sync'd.

I've also deprecated sync, we can reinvent it, but it'll take some more thought I think.

**Comment by pry0cc** [comment]
Also - could you share your .gitconfig file?

**Comment by tavdog** [comment]
my .gitconfig is just the following :
[oh-my-zsh]
	hide-status = 1

I felt kind of silly going to all this trouble about the backup script once I realized how easy it is to just re-image my modified machine on DO and use that as my starting point but.  I like the files-from direction style, very flexible.
