### ISSUE TITLE
tar (child): doctl.tar.gz: Cannot open: No such file or directory

### ISSUE THREAD

**Issue by jona5pok** [pry0cc/axiom#128]
Saving to: ‘/tmp/doctl.tar.gz’

/tmp/doctl.tar.gz                                   100%[=================================================================================================================>]  11.87M  15.8MB/s    in 0.7s

2020-11-05 01:19:45 (15.8 MB/s) - ‘/tmp/doctl.tar.gz’ saved [12450872/12450872]

tar (child): doctl.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
go:
Already up to date.
What is your DigitalOcean API key?
Key >> 

Anyone else with this mistake? then I try to run axiom-init but it doesn't work, I'm using ubuntu 20.04

**Comment by cybertron10** [comment]
same error

**Comment by 0xtavian** [comment]
fixed in the latest merge, thank you.

`wget -O /tmp/doctl.tar.gz https://github.com/digitalocean/doctl/releases/download/v1.45.0/doctl-1.45.0-linux-amd64.tar.gz && tar -xvzf /tmp/doctl.tar.gz && sudo mv doctl /usr/bin/doct`
