### ISSUE TITLE
Can't generate html report

### ISSUE THREAD

**Issue by cybertron10** [pry0cc/axiom#140]
nmap was unable to generate html report.

no such file merge.html error

![Screenshot 2020-11-21 at 5 25 43 AM](https://user-images.githubusercontent.com/56225601/99860830-4a932200-2bba-11eb-9ebc-17ddebaf2424.png)

**Comment by cybertron10** [comment]
Resolved

**Comment by pry0cc** [comment]
Would you be able to provide your problem and fix for other people searching in future?

**Comment by cybertron10** [comment]
Nmap bootstrap xsl needs xsltproc which was not installed on ubuntu from digital ocean.

I used sudo apt-get install xsltproc

Since then axiom is able to convert XML files into html report. It will be good if you add this install command while installing axiom.
