### ISSUE TITLE
Jaeles Scanner

### ISSUE THREAD

**Issue by cybertron10** [pry0cc/axiom#141]
Can you add Jaeles scanner and thanks for sharing such a great tool.

**Comment by 0xtavian** [comment]
@cybertron10 Can you try this and let me know if it works for you?

Update axiom-scan with the following 
https://github.com/pry0cc/axiom/blob/da97418c2563836cdb77739a9867a23aefd3a84e/images/provisioners/full.json

create module/jaeles.json
https://github.com/pry0cc/axiom/blob/da97418c2563836cdb77739a9867a23aefd3a84e/modules/jaeles.json

jaeles-summary.txt and vuln-summary.txt are overwritten and will only contain partial results, however the full results are returned to the terminal VIA STDOUT. 

Folder names/targets should update and will be the main source of findings.

**Comment by cybertron10** [comment]
@0xtavian It doesn't works installation was done but when I run 
axiom-scan subdomain.txt -m jaeles -o jealesresults

This gives me jeales help options I guess we need to pass templates path as well

**Comment by 0xtavian** [comment]
I believe that is expected behavior with jaeles. As you said, you need to provide templates. The default templates should already be initialized. Try running `axiom-scan targets.txt -m jaeles scan -s 'wordpress' -v`, for example. If you have specific templates that arent added let me know.

**Comment by cybertron10** [comment]
Is there a way I can add my own templates in both nuclei and jaeles.

**Comment by 0xtavian** [comment]
Yes, for example running `axiom-exec "git clone https://github.com/cybertron10/Mysignature"` should download your signatures to all Axiom instances. You should be able to specify them inline with your jaeles command. For nuclei, download the templates to all boxes using any method and edit the module to point to the new templates https://github.com/pry0cc/axiom/blob/master/modules/nuclei.json

**Comment by cybertron10** [comment]
Thank you 

For jaeles I edited the axiom-scan. Do I need to revert back to the original axiom-scan or no need to do so.

Just want to confirm becoz other tools should not stop working.

**Comment by 0xtavian** [comment]
@cybertron10 Everything should work as expected. Please let us know if thats not the case. We've committed these changes to dev for now https://github.com/pry0cc/axiom/tree/dev

The following is a description of changes in dev.
"Creates a unique directory for every scan to work out of. This allows running multiple module at the same time without overwriting input/output files. The $control directory does not get deleted during cleanup from axiom instances. Control directory names have the following format `control=$module"_"$(date "+%F-%H-%M-%S")` aka `nmapx_2020-11-30-19-14-03`. Still have to figure out how to delete the newly created directory during cleanup without deleting ones currently being used by other scans."
