### ISSUE TITLE
Add DNSGen to Supported Commands

### ISSUE THREAD

**Issue by m0chan** [pry0cc/axiom#149]
Title says it all :) - Would be great to distribute DNSGen over multiple hosts.

https://github.com/ProjectAnte/dnsgen

~ @m0chan

**Comment by pry0cc** [comment]
https://github.com/pry0cc/axiom/commit/922ab57b035b2bff4b2f9dbbfc2d6a8e49d848a5

👍

**Comment by pry0cc** [comment]
I'm an idiot... DNSGen is now preinstalled. Module incoming...

**Comment by pry0cc** [comment]
https://github.com/pry0cc/axiom/commit/b28d119392e59d1a59a4b5d726cd3dfc2ea19107

;)

I had an idea for a playbook module too...

```
cat input | subfinder | dnsgen | massdns```

Is this how you would use it?
