### ISSUE TITLE
osx dependency "shuf" not fulfilled by installer

### ISSUE THREAD

**Issue by dst-mx559** [pry0cc/axiom#160]
"shuf" is not installed by default on osx and parsing input scope files to fleets breaks.

to fix the issue, install coreutils via brew.

**Comment by 0xtavian** [comment]
Thank you. We'll get this tested and added soon.

**Comment by 0xtavian** [comment]
@dst-mx559 Can you uninstall coreutils and then rerun axiom-configure to test the new merge?
