### ISSUE TITLE
Adding own tools

### ISSUE THREAD

**Issue by Lucaman97** [pry0cc/axiom#164]
Is it possbile to add your own tools?
If not is it possible to implement this?

Thanks

**Comment by dogasantos** [comment]
it's a VPS running on cloud. You can just connect into it and install your tools.
If you don't want to do it manually, you can write a bash script to run git clone or whatever into each node.

**Comment by 0xtavian** [comment]
@dogasantos @Lucaman97 please see https://github.com/pry0cc/axiom/issues/173#issuecomment-765564851. Going to try to get to this soon.

**Comment by 0xtavian** [comment]
@dogasantos @Lucaman97 https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules let me know what you think!
