### ISSUE TITLE
Adding Linod Support

### ISSUE THREAD

**Issue by h1hakz** [pry0cc/axiom#165]
Hi Team,

Is it possible to add linode sever support also.

Thanks
Ranjith

**Comment by pry0cc** [comment]
Yep :) If you want it bad enough, sponsor the project for $80 per month and it'll become a priority.

**Comment by pry0cc** [comment]
https://github.com/sponsors/pry0cc

**Comment by ZultanH** [comment]
Linode support would be great! I found some resources that you may find useful to add it to the list of providers.
Packer support via https://www.packer.io/docs/builders/linode
Linode CLI tool https://www.linode.com/docs/guides/linode-cli/
Free $100 of credit https://www.linode.com/lp/brand-free-credit-short/

**Comment by 0xtavian** [comment]
awesome info. @h1hakz @ZultanH  we are closing this issue and merging all issues for cloud provider suggestions into one. https://github.com/pry0cc/axiom/issues/177
