### ISSUE TITLE
No option to enter API-key for do

### ISSUE THREAD

**Issue by math-ematics** [pry0cc/axiom#166]
No option to edit settings before install starts, and install can not run with no key added. 

`Configuring your cloud account...
Axiom Account Setup
You can use this wizard to add new accounts, once made, use axiom-account to switch between profiles
Please enter your provider (Default 'do', options: 'gcp', 'ibm', 'azure'):
>> do
Please enter your GPG Recipient Email (for encryption of boxes): (optional, press enter)
>>
Would you like to configure connection to an Axiom Pro Instance? Y/n (Must be deployed.) (optional, default 'n', press enter)
>> n
Profile settings below:
{
  "do_key": "",
  "region": "",
  "provider": "do",
  "default_size": "",
  "appliance_name": "",
  "appliance_key": "",
  "appliance_url": "",
  "email": ""
}
Press enter if you want to save these to a new profile, type 'r' if you wish to start again.

`

**Comment by math-ematics** [comment]
no problem to create a new json from the do.json.example and then axiom-account with the new one.
Then axiom-build no problem , stuff works.

But the installer does not offer the option to edit info

**Comment by sakyb7** [comment]
yes having the same problem

**Comment by 0xtavian** [comment]
@math-ematics @sakyb7 Thanks for bringing this to our attention. Can you both run axiom-update and try again? there was an issue with the port to Azure that caused the field being skipped. https://github.com/pry0cc/axiom/blob/master/interact/axiom-account-setup
