### ISSUE TITLE
packer not auto installed on WSL Ubuntu

### ISSUE THREAD

**Issue by pxng0lin** [pry0cc/axiom#167]
I've installed WSL on my windows desktop and gone through the installation steps for axiom, nearly finished but then noticed it hadn't installed packer, see attached

![axion-nopacker](https://user-images.githubusercontent.com/60779090/104134477-a0e23d00-5381-11eb-915a-b0d45df3d0ea.jpg)

**Comment by pxng0lin** [comment]
Update

It also doesn't install interlace, just found out whilst trying to execute axiom-exec, gave me an error advising 
`line 83: Interlace: command not found`

**Comment by 0xtavian** [comment]
@pxng0lin will get to this sooner or later. Another thing we need to add is to download and install python3 and make it default.

**Comment by abdulsec** [comment]
install unzip
sudo apt install unzip
you should install unzip first , because its required to unzip packet
then intall

**Comment by pry0cc** [comment]
Does that latest update fix this?

**Comment by 0xtavian** [comment]
Please reopen if this is not fixed.
