### ISSUE TITLE
unable to run gospider

### ISSUE THREAD

**Issue by pxng0lin** [pry0cc/axiom#168]
I've checked the modules and found the gospider.json, I've attempted to run the axiom-scan against it but it brings back an error, please see image

`zsh:1: no such file or directory: /home/op/go/bin/gospider
Generated 10 commands in total
Repeat set to 1
zsh:1: no such file or directory: /home/op/go/bin/gospider
zsh:1: no such file or directory: /home/op/go/bin/gospider
zsh:1: no such file or directory: /home/op/go/bin/gospider
cat: input: No such file or directory`

![image](https://user-images.githubusercontent.com/60779090/104323603-44e0fb00-54de-11eb-8526-ace3c3f556bf.png)

**Comment by pxng0lin** [comment]
json contents:

`cat gospider.json
[{
        "command":"cat input | /home/op/go/bin/gospider -S - --depth 3 -v -t 50 -c 3 -o output",
        "ext":""
}]`

**Comment by 0xtavian** [comment]
thanks for letting us know. gospider was missing from the packer build. I went ahead and added it.
