### ISSUE TITLE
Ffuf module error - No such file /home/op/lists/pry-web-quick.txt

### ISSUE THREAD

**Issue by ZultanH** [pry0cc/axiom#172]
When attempting to run the ffuf module using axiom-scan http.txt -m ffuf -o content.csv --threads 2 it would error out saying it couldn't find the default wordlist specified in the module.

**Comment by pry0cc** [comment]
Ahh. Need to set a custom wordlist with -w, 

I'd ssh into an instance, identify the wordlist you want and then run pwd to get the absolute path. Then supply that using -w :)

**Comment by pry0cc** [comment]
Fixed when not specifying the -w option
