### ISSUE TITLE
Add module Dalfox 

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#173]
It would be nice to have this tool running in a distributed manner. 

https://github.com/hahwul/dalfox

**Comment by 0xtavian** [comment]
@pdelteil I've been meaning to get to this. Dalfox is installed but there just is no module for it. I might make a small guide on how to make modules instead. Would you be willing to follow the guide and make the module for it? Its not hard at all to add modules. One of the simplest modules that can be used as a template is dnsx https://github.com/pry0cc/axiom/blob/master/modules/dnsx.json

**Comment by pdelteil** [comment]
Hi there,

Thanks for your answer. I would love to make the module. I will try during the week end.

**Comment by 0xtavian** [comment]
@pdelteil https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules Im going to make another on adding tools that output to JSON or to a folder, but this should work for simple text output

**Comment by 0xtavian** [comment]
accidental close :) We'll close when the module is added.

**Comment by ZultanH** [comment]
Added code for it in pull request #178

**Comment by 0xtavian** [comment]
@ZultanH were you able to test it and everything works as expected?

**Comment by ZultanH** [comment]
@0xtavian yes, the output doesn't look pretty in the main terminal screen but it does the job and works as expected

**Comment by 0xtavian** [comment]
merged! thanks man!! :D
