### ISSUE TITLE
Input file upload fails 

### ISSUE THREAD

**Issue by EthicalKid1** [pry0cc/axiom#174]
I have a setup where I used 15 digital ocean instances but have now switched to 5 instances with the massdns module. Currently, the output is empty ever since I switched to 5 instances. The input file is 9.5 million lines long of domain names with subdomains. I think its upload functionality that fails from the following screenshot.

![2021-01-20_22-37](https://user-images.githubusercontent.com/32944938/105280737-1911e500-5b70-11eb-8df7-6a2773390052.png)

Is there a way to fix this?

**Comment by 0xtavian** [comment]
@EthicalKid1 Can you run `axiom-update` and try again? Also can you show the command you entered? The screenshot is missing a little from the top.
Also try to run `axiom-exec "uname -a" | wc -l`. This should return how many instances you have.

**Comment by 0xtavian** [comment]
Dont run with `-q` to test. Also, is there any data on the instances or the local logs tar.gz? And make sure there arent any orphaned processes with `axiom-exec sudo ps aux`.

**Comment by EthicalKid1** [comment]
@0xtavian I ran `axiom-update` and I modified the massdns module to run without `-q` and it worked. I now get the expected output.

Thanks for your help.
