### ISSUE TITLE
amass preinstalled?

### ISSUE THREAD

**Issue by nullman0x** [pry0cc/axiom#176]
I am trying 
amass -version

getting error
zsh:1: command not found: amass

isn't preinstalled?

**Comment by 0xtavian** [comment]
@nullman0x thanks good catch. it was included (twice actually once by mistake) just not added to path. you can run `axiom-exec "sudo cp /home/op/go/bin/amass /usr/bin"` to fix.

**Comment by nullman0x** [comment]
how to run amass in parallel?
i could not find axiom module for it?
i want to run subdomain enumeration parallely for a domain

**Comment by 0xtavian** [comment]
There is no axiom module for amass however it shouldnt be difficult at all to add one. Check out https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules. If you make a working module we will def commit it to master.
For now we have subfinder which is used to gather from certificate transparency logs sources. We also have massdns, and shuffledns for brute forcing. and DNSX for  just simple resolving.
