### ISSUE TITLE
Tool gf requires additional setup steps to function as intended

### ISSUE THREAD

**Issue by mrpentest** [pry0cc/axiom#18]
According to https://github.com/tomnomnom/gf after installing it using Go, you need to create a ~/.gf/ folder and copy the .json files from /examples folder there. Then, for the autosuggestion/autocomplete function to work you need to source a specific file. Additional filters can be found here: https://github.com/1ndianl33t/Gf-Patterns which would also be nice to include :)

**Comment by pry0cc** [comment]
Been planning on adding this!

Thanks! I will work on this next :)
