### ISSUE TITLE
Not able to access any box created by axiom

### ISSUE THREAD

**Issue by sumgr0** [pry0cc/axiom#180]
Hi,

I've been trying to setup the axiom on my Mac running Big Sur over the Digital Ocean cloud services.

After I successfully create the box(es) using init or fleet commands, I'm unable to access the box via ssh or through scan command.

Looking at the file ~/.axiom/.sshconfig, I notice an unknown IP address: 178.128.143.10 getting listed under my existing VPS box on Digital Ocean not created using axiom.
![image](https://user-images.githubusercontent.com/11391119/105745537-63c2a100-5f64-11eb-88bd-d4c95577d2af.png)

It leads to the error message: 

/Users/sumgr0/.axiom/.sshconfig: line 3: Bad configuration option: 178.128.143.10
/Users/sumgr0/.axiom/.sshconfig: terminating, 1 bad configuration options

I've tried removing the IP, yet it reappears the moment I run the axiom ssh or scan command. I've run the axiom-update and axiom-build command numerous times but no avail.

**Comment by sumgr0** [comment]
Update: I just checked my IP addresses in the DO GUI, and figured that 178.128.143.10 belongs to my box running the ghost blog.

**Comment by pry0cc** [comment]
It looks like you have two hosts named the same thing - check the web gui.

**Comment by sumgr0** [comment]
After a little bit of digging, the ghost blog box has one IPv4 and the other is the floating IP I'd setup ages ago, and never touched it...

**Comment by 0xtavian** [comment]
@sumgr0 you'll need to delete the box on DO GUI, axiom wont be able to. You could also manually edit the ssh config to remove the problem hosts and run axiom-scan with --cache. This skips the API call for axiom-ls. Its due to the way axiom parses the inventory.

**Comment by sumgr0** [comment]
@0xtavian thanks your suggestion of **$HOME/.axiom/interact/axiom-exec and change cache to true** worked and axiom is now able to connect to the box(es)
