### ISSUE TITLE
ssh issue asking for password

### ISSUE THREAD

**Issue by nullman0x** [pry0cc/axiom#182]
i have added ssh key without password at

~/.ssh/id_rsa.pub
~/.axiom/configs/authorized_keys

and build the instance
axiom-build

when axiom-init
all new instances are asking for password, though the ssh key has no password set

need help

**Comment by 0xtavian** [comment]
@nullman0x what platform are you running Ubuntu or Mac? Are you able to SSH into the instances without axiom? SSH op@IP port 2266

**Comment by nullman0x** [comment]
@0xtavian i am using Ubuntu
No i am not able to enter the instance directly 
 SSH op@IP port 2266

it is asking for password

**Comment by nullman0x** [comment]
op@x.x.x.x's password:  
Permission denied, please try again.

**Comment by 0xtavian** [comment]
to be clear your running `ssh ip@axiom-ip -p 2266`? If youre unable to connect to these boxes than your ssh key hasnt been uploaded to the right box. Delete the local ssh pub and private keys, delete axiom, generate new ssh keys and run axiom-configure.
```
rm -rf ~/.ssh/*
rm -rf ~/.axiom/
git clone https://github.com/pry0cc/axiom ~/.axiom/
ssh-keygen -b 2048 -t rsa -q -N ""
cd $HOME/.axiom/interact/
./axiom-configure
```

**Comment by 0xtavian** [comment]
@nullman0x 
Also do a dist-upgrade before installing axiom for good measure 
`sudo apt-get update && sudo apt-get dist-upgrade -y`

**Comment by nullman0x** [comment]
hold on let me try your steps @0xtavian

**Comment by nullman0x** [comment]
@0xtavian 
i tried all steps still having same error
i am using DO cloud with ubuntu

**Comment by nullman0x** [comment]
@0xtavian
![image](https://user-images.githubusercontent.com/77861653/105890512-79ec6200-6035-11eb-915f-46294303ca1b.png)

**Comment by 0xtavian** [comment]
@nullman0x I see the issue. You are running axiom-configure with sudo. Drop the sudo or move the ssh keys to the appropriate user.

**Comment by 0xtavian** [comment]
I would create a new user, add them to sudoers and re-install as a user. The configure script will prompt for creds when sudo is needed.

**Comment by 0xtavian** [comment]
Also when you are testing ssh access, do it without axiom-ssh. `ssh op@<moore13-ip> -p 2266`.

**Comment by nullman0x** [comment]
@0xtavian  ok let me try
I tried earlier without root user, but that time also had same error
then i thought to try with root user

Yes I am also checking with this 
ssh op@<moore13-ip> -p 2266

let me try one more time now, i will get back to you in 15 minutes

**Comment by nullman0x** [comment]
@nullman0x 
am i missing something ?

![image](https://user-images.githubusercontent.com/77861653/105897809-aa84c980-603e-11eb-8ab6-545cbefc1ae0.png)

**Comment by nullman0x** [comment]
same error again
![image](https://user-images.githubusercontent.com/77861653/105898583-a0af9600-603f-11eb-872a-bc204bc116d2.png)

**Comment by 0xtavian** [comment]
> @nullman0x
> am i missing something ?
> 
> ![image](https://user-images.githubusercontent.com/77861653/105897809-aa84c980-603e-11eb-8ab6-545cbefc1ae0.png)
> 
> ![image](https://user-images.githubusercontent.com/77861653/105898063-04858f00-603f-11eb-988c-610c667110d0.png)

@nullman0x  yea for sure u r missing something. did you run sudo apt-get dist-upgrade? also install unzip and paste the full output to a pastebin (remove ur DO api key first).

**Comment by 0xtavian** [comment]
@nullman0x running axiom-configure installs unzip. idk how u missed that. Run `bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)`.

**Comment by nullman0x** [comment]
@0xtavian  ok i will give you output with this 
bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)
please wait

**Comment by 0xtavian** [comment]
ty run `bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)` as a low-priv user and try again, please provide full output.

**Comment by nullman0x** [comment]
@0xtavian 

the current user is op, i have created is also a sudo user

**Comment by mchoji** [comment]
I am facing the same error. Apparently, there is a problem with the script used to build the image at DO. I see several errors regarding dpkg and missing user op.

I will try to build this image manually and see where is the problem at.

**Comment by nullman0x** [comment]
@0xtavian 


log attached
so i created a new vmware vm in ubuntu
i am stilling getting errors

ran these commands
sudo apt-get update && sudo apt install curl -y && sudo apt-get dist-upgrade -y

bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)

[log.txt](https://github.com/pry0cc/axiom/files/5876345/log.txt)

**Comment by 0xtavian** [comment]
@mchoji you are correct @nullman0x sorry for the wild goose chance. I am also investigating.

**Comment by nullman0x** [comment]
@0xtavian  thanks please investigate
I thought I made some mistake, because few days when I used the same script it worked, but when I tried to install it today, not working at all.
I spent my day&night only trying to install this

**Comment by pry0cc** [comment]
I'm trying it out now. I'm aware of the issue but I won't fix it tonight. I'll get this resolved.

**Comment by pry0cc** [comment]
It's probably some bullshit update from Ubuntu or DO that is breaking a package somewhere. I expect it'll be simple and there will be many others complaining soon enough.

Stay tuned.

**Comment by pry0cc** [comment]
![image](https://user-images.githubusercontent.com/4334403/105913313-a20a9f80-5ffa-11eb-9358-eb88f45a3688.png)
Probably the issue

**Comment by pry0cc** [comment]
Does this fix work?

https://github.com/pry0cc/axiom/commit/c304a0406c23d96535c170a66bc6215eb852394d

if so - merge it with master. I'm off.

**Comment by 0xtavian** [comment]
didnt work for me

**Comment by pry0cc** [comment]
build completed, checking to see now if I can ssh in...

**Comment by mchoji** [comment]
I got some errors in the end...not sure what it will impact though.

![2021-01-26_20-01.png](https://user-images.githubusercontent.com/7395296/105918663-304b4980-602c-11eb-814d-8e73a197849e.png)

**Comment by 0xtavian** [comment]
@nullman0x @mchoji, thanks for bringing this. @pry0cc has pushed a fixed. I can confirm that it works. run axiom-update and try again.

**Comment by nullman0x** [comment]
@0xtavian  working fine now
thanks @pry0cc 
closing this issue
