### ISSUE TITLE
Question of install multiple devices

### ISSUE THREAD

**Issue by hahwul** [pry0cc/axiom#183]
@pry0cc 
Hi buddy :D
I have a question about Axiom. Is there any way to share instance information between multiple platforms? If I install the axiom on another device after setting it up on my Macbook, it seems to be make instance image again. Let me know if there's anything I missed 🙏🏼

------ 
== Content not related to the issue ==
Oh, and there's a `discussions` in the github. I think we can separate the actual issue from the question through this. I think it's a good device, so think about it!
![1414](https://user-images.githubusercontent.com/13212227/105869727-e584fe00-603a-11eb-9780-f6b430149724.jpg)

Lastly, thank you so much for making cool tools! You're the best!

**Comment by 0xtavian** [comment]
@hahwul For now you can share the axiom profile between computers. Your account profile is in `~/.axiom/account/<your-account>.json`, which contains your API key. To install Axiom without spinning up a box, clone the repo with the new machine to `~/.axiom` with `git clone https://github.com/pry0cc/axiom ~/.axiom/`, and uncomment the build script https://github.com/pry0cc/axiom/blob/master/interact/axiom-configure#L235 in `~/.axiom/interact/axiom-configure` and then run axiom-configure.

**Comment by 0xtavian** [comment]
I like the idea of making this a discussion tho. But I dont have the permissions to do so. @pry0cc can you make a discussion for this? @hahwul we've been thinking about this for a week or so now about the best way to share a fleet.
To share a fleet between two computers you own, the above works fine. But if sharing a fleet with someone your collaborating with, you might not what to share an API key. In that case we plan to write an `axiom-share` (not official name) command. 

One way it might look:
Your collaborator provides their public key and axiom will add it to all instances known_hosts file. Then axiom will start a webserver with a config file on one of the instances (no sensitive info will be in the config file). The collaborator will download the config file and be able to use your fleet.

**Comment by hahwul** [comment]
@0xtavian @pry0cc 
Oh, thank you so much! I understood it😍 
It's really nice to hear that you're also discussing the axiom-share! First of all, my curiosity has been solved, so I'll close the issue! I'll be waiting for the opening of discussion!
