### ISSUE TITLE
Improvement/Fix: Re-use Azure credentials from config for Packer build

### ISSUE THREAD

**Issue by Mirabis** [pry0cc/axiom#187]
The addition of `"use_azure_cli_auth": true` in axiom.json will tell packer to use the credentials saved in the steps before. [Docs](https://www.packer.io/docs/builders/azure)

**Why?**
I use Azure in a corporate environment where plain `az login` is not allowed regardless of being able to open the browser or 2FA being present. The only way to interact with Azure CLI interactively is to use `az login --service-principal -u http://xxxx -p "pass" --tenant "guidhere"`. Modifying the install files to replace `az login` with the service principal version was easy but after setting the profile (axiom.json) it overwrites the changes and immediately attempts to run packer. 

Packer does not seem to use the cached credentials and triggers another authentication attempt:
```bash

==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using device flow
==> azure-arm: Getting token for https://management.azure.com/
==> azure-arm: Loading auth token from file: /home/user/.azure/packer/oauth-randomid-77df-4beb-b27d-aa0c70b8382cmgmt.json
==> azure-arm: Initiating device flow: /home/user/.azure/packer/oauth-randomid-77df-4beb-b27d-aa0c70b8382cmgmt.json
==> azure-arm: Microsoft Azure: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DR6HJ9BXX to authenticate.
```
My guess is a simple addition in `interact/axiom-account-setup` for `use_azure_cli_auth="true"` would suffice. (quotes to prevent the json unmarshalling error).

**Comment by pry0cc** [comment]
Can you possibly work up a pull request?

**Comment by Mirabis** [comment]
I'll queue it for the weekend.

**Comment by 0xtavian** [comment]
thank you!
