### ISSUE TITLE
[issue] axiom-configure doesn't install several packages 

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#188]
Hello,

I tried to run the axiom-configure on a Kali 2020.4 instance, but the following packages were not installed correctly:

- interlace
- packer 
- doctl 

As a workaround I just ran the installations commands in axiom-configure manually:

interlace
```
git clone https://github.com/codingo/Interlace.git /tmp/interlace
        cd /tmp/interlace && sudo python3 setup.py install
```
packer
```
wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip && cd /tmp/ && unzip packer.zip && sudo mv packer /usr/bin/
```

doctl

```
wget -O /tmp/doctl.tar.gz https://github.com/digitalocean/doctl/releases/download/v1.45.0/doctl-1.45.0-linux-amd64.tar.gz && tar -xvzf /tmp/doctl.tar.gz && sudo mv doctl /usr/bin/doctl
```

**Comment by gsilvapt** [comment]
It would help if you could paste here the logs of the errors so we can identify and push fixes for it. Thanks! :pray:

**Comment by gsilvapt** [comment]
Can you paste some error logs to help understanding why they failed installing? Thanks!

**Comment by pdelteil** [comment]
Hello there @gsilvapt they just were not installed, didn't get any error output from the installing script (axiom-configure), I just realized this packages were missing after running axiom-init 

After this issue is fixed you axiom will be Kali tested and supported :D

**Comment by pry0cc** [comment]
Can you please try out the latest push and tell me if it works now?

**Comment by 0xtavian** [comment]
Thanks, this has been resolved.
