### ISSUE TITLE
Add bc as dependency [Kali] 

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#189]
I was running the axiom-fleet and got some errors due to bc not installed:

![Screenshot from 2021-01-30 01-01-16](https://user-images.githubusercontent.com/20244863/106346549-bcf94000-6296-11eb-966c-8248c1c665a2.png)

**Comment by pdelteil** [comment]
Also jq

**Comment by gsilvapt** [comment]
> Also jq

jq is already supported: https://github.com/pry0cc/axiom/blob/master/interact/axiom-configure#L95

bc support is added in this PR #202

**Comment by pdelteil** [comment]
> > Also jq
> 
> jq is already supported: https://github.com/pry0cc/axiom/blob/master/interact/axiom-configure#L95
> 
> bc support is added in this PR #202

Yes, that's not what I mean.  jq and bc are dependencies required in the 'parent' host from where you are running axiom, not in the image.

**Comment by 0xtavian** [comment]
I believe this was fixed yesterday, let us know if that is not the case. Im going to close this issue, feel free to reopen.
