### ISSUE TITLE
[Issue] App not handling correctly droplets limit

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#190]
I was trying to create a fleet with 15 instances, but my initial limit was 10. 

So, I got this error:

![Screenshot from 2021-01-30 01-22-23](https://user-images.githubusercontent.com/20244863/106347051-4a8a5f00-629a-11eb-9bd3-99f02e88552c.png)

**Comment by math-ematics** [comment]
And you requested a higher fleet cap at Digital ocean via your settings? Since the max is 10 at DO if you do not manually ask for more

**Comment by pry0cc** [comment]
Yeah you'll need to speak to support and ask for an increase!

**Comment by pdelteil** [comment]
> Yeah you'll need to speak to support and ask for an increase!

I'm sorry I couldn't answer before. 

What I meant is that the app is not handling that problem correctly.  I guess it might (if possible) check if the amount of droplets you want to add to a fleet is less or equal to the amount of droplets available. 

If you notice the app is not failing correctly, is creating the amount of droplets available but it keeps trying to initiate droplets that do not exist.
