### ISSUE TITLE
Change colour of blue text in "axiom-ls"

### ISSUE THREAD

**Issue by ZultanH** [pry0cc/axiom#191]
The dark blue colour on a black terminal background makes it essentially impossible to read what the text is in the output of axiom-ls. Would recommend changing it to something more readable in contrast to a black background.

**Comment by pry0cc** [comment]
Can you show me a screenshot? looks fine in both my setups!

**Comment by ZultanH** [comment]
![Screenshot_21](https://user-images.githubusercontent.com/43057246/106406775-11aedd80-6486-11eb-8361-99c24011ec8d.png)
I'm using PuTTY so it could be that as well.

**Comment by rst10124492** [comment]
In Putty, go to Connection - Data, change Terminal-type string to xterm-256color save the session and log in again.
