### ISSUE TITLE
how to backup settings and move axiom?

### ISSUE THREAD

**Issue by nullman0x** [pry0cc/axiom#192]
how can I backup whole of an instance
not just the files listed in ~/.axiom/boxes/backup-files.txt
 ?

**Comment by nullman0x** [comment]
also I have made some custom changes to the boxes.
how can I backup the box and replicate it as fleets?

**Comment by nullman0x** [comment]
i want to backup a whole box and it's configurations 
not just the files listed in ~/.axiom/boxes/backup-files.txt 

how to do this?

**Comment by nullman0x** [comment]
also how to archive a nbox without gpg encryption
axiom-boxes archive <name>

I am getting error
gpg: jaa01.tar.gz: encryption failed: Invalid user ID

**Comment by pry0cc** [comment]
Archive is only gpg encryption, to snapshot a host you need to use snapshotting in the DO panel.
