### ISSUE TITLE
Fedora configuration option using apt

### ISSUE THREAD

**Issue by Mindslave** [pry0cc/axiom#199]
Hey,

I noticed that in `interact/axiom-configure` in the fedora specific part of you use apt, shouldn't it be dnf or yum?

See line 92-94
````
elif [ $OS == "Fedora" ]; then
  	echo -e "${Blue}Installing other repo deps...${Color_Off}"
	sudo apt-get update && sudo apt-get install fzf git unzip python3-pip curl net-tools git unzip xsltproc
````

further down in line 100 you do acctually use dnf

```
sudo dnf -y update && sudo dnf -y install fzf git
```

If wanted I can try to figure out the package names for dnf accordingly and set up a pull request in the next few days.

While Im at it, I appreciate your work on this project, seems awesome so far!

**Comment by pry0cc** [comment]
Fixed!
