### ISSUE TITLE
Digitalocean account locked out due to axiom

### ISSUE THREAD

**Issue by nullman0x** [pry0cc/axiom#201]
account got locked out for running axiom, axiom is the only tool used
used only few droplets

any alternative
please provide a option to deploy axiom on any VPS ?

**Comment by rst10124492** [comment]
Have you asked DO why they blocked your account?

**Comment by nullman0x** [comment]
yes due to axiom mass scaning

**Comment by rst10124492** [comment]
I never got my account blocked and I am mass scanning daily and I am not alone. Make sure to let them know you're scanning organisations that allow it because that's what you're scanning, right?

**Comment by nullman0x** [comment]
yes only targets in scope are scanned

**Comment by nullman0x** [comment]
how old is your account?

**Comment by nullman0x** [comment]
and how many droplet you use

**Comment by nullman0x** [comment]
i am sure I am not the only one
https://twitter.com/w3Nicolas/status/1134529316904153089

**Comment by geeknik** [comment]
Strange. My DO account is almost 8 years and I have a couple hundred droplets running and I've never been suspended from the service even after receiving multiple abuse reports.

**Comment by nullman0x** [comment]
never heard digitalocean allowing more than 10 droplets
I guess you used digitalocean used for some other purpose initially

**Comment by geeknik** [comment]
I don't know about all of the problems other people are having but we just emailed support one day and asked for a bump in our limit and they asked us to justify it and the rest is history. Good luck!

**Comment by nullman0x** [comment]
there goes the thread https://twitter.com/pry0cc/status/1356249648118308865
digitalocean is a mess 

has anyone used it on IBM or any other VPS
I need help

**Comment by nullman0x** [comment]
left digitalocean
