### ISSUE TITLE
i can't start a new droplet using axiom

### ISSUE THREAD

**Issue by bing0o** [pry0cc/axiom#204]
i'm having an issue with axiom, at first it was working all fine, but now i can't start a new droplet(s) using axiom

![axiom-issue](https://user-images.githubusercontent.com/25457545/106648040-047e1580-6590-11eb-98fc-233df4ee450b.png)

any solution !.

**Comment by 0xtavian** [comment]
that region might be full. Try a different one. @bing0o 

<img width="409" alt="Screen Shot 2021-02-02 at 1 37 56 PM" src="https://user-images.githubusercontent.com/21030907/106653002-de3e8280-655b-11eb-83d4-984820a8a53a.png">

**Comment by bing0o** [comment]
yea you're right @0xtavian that's the problem, thanks :]

**Comment by bing0o** [comment]
yea you're right @0xtavian that's the problem, thanks :]
