### ISSUE TITLE
axiom-init not working

### ISSUE THREAD

**Issue by nullman0x** [pry0cc/axiom#205]
hi
 on linode the image is created successfully and i can find it on the linode images panel
![image](https://user-images.githubusercontent.com/77861653/106660097-981e0900-65c5-11eb-861d-d776a1202d33.png)

but axiom-init is not loading (waiting since minutes)

![image](https://user-images.githubusercontent.com/77861653/106660418-f945dc80-65c5-11eb-86f8-49ff7a277072.png)

What's wrong?

**Comment by nullman0x** [comment]
i tried multiple times
same issue
need help

**Comment by 0xtavian** [comment]
@nullman0x all good?
