### ISSUE TITLE
axiom-scp privilege issue

### ISSUE THREAD

**Issue by CuriousIncident** [pry0cc/axiom#206]
I'm trying to copy over my amass config file, but I am getting an privilege error, am I not signed in as root? I will look into axiom-scp and try to solve this as i haven't seen similar reports it might be an issue of my setup.
I'm running Kali Linux I tried both I hope correctly running as a user and as root.

`uname -a: Linux Boot 5.10.0-kali2-amd64 #1 SMP Debian 5.10.9-1kali1 (2021-01-22) x86_64 GNU/Linux`

Command run:
```
axiom-scp /root/dom/ama/config1.ini edison29:/root/lists/config.ini
sending incremental file list
rsync: ERROR: cannot stat destination "/root/lists/config.ini": Permission denied (13)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(660) [Receiver=3.1.3]
```

I hope I'm not making this up.

**Comment by 0xtavian** [comment]
@CuriousIncident try `axiom-scp /root/dom/ama/config1.ini edison29:/home/op/lists/config.ini`.

**Comment by 0xtavian** [comment]
Additionally you have root access with sudo. the sudo password is your API key. Going to close this issue. Please reopen if you need.
