### ISSUE TITLE
Axiom-Build fails at creating image for Linode

### ISSUE THREAD

**Issue by Hebx** [pry0cc/axiom#208]
Hi , I'am having this issue on Wsl 2 Kali Linux & on Linode Ubuntu 20.04 LTS . I've installed all dependencies prior to launching the script eventho the error keeps occuring in loop.

![image](https://user-images.githubusercontent.com/33012322/106767064-67c08400-6632-11eb-8403-890e7699b6db.png)

**Comment by Hebx** [comment]
axiom-build script was pointing to full.json provisioner with a digital ocean build. a modification of the full.json file for a linode build resolve the issue.

**Comment by Hebx** [comment]
The issue has nothing to do with this modification , reopening the issue for more investigation.

**Comment by pry0cc** [comment]
You need to increase your image size to 18GB, on account setup you are prompted if you would like to open a ticket - did you select yes?

If you did - please check in with Linode support and ensure they increase your image size to 18GB - this is required to run axiom :) 

Thanks

**Comment by Hebx** [comment]
I understand now that linode images are limited in size and axiom requirement exceed that default data limitation. 
I open a ticket for the image increase request. 
Thanks
