### ISSUE TITLE
Update rustscan to v 2.0

### ISSUE THREAD

**Issue by kusayuzayushko** [pry0cc/axiom#209]
Currently, it's outdated as hell. 

```
 rustscan --version
RustScan 0.01
```

`wget https://github.com/RustScan/RustScan/releases/download/2.0.1/rustscan_2.0.1_amd64.deb`
`sudo dpkg -i rustscan_2.0.1_amd64.de`

**Comment by pry0cc** [comment]
Good call! Thanks

**Comment by 0xtavian** [comment]
thanks @kusayuzayushko !
