### ISSUE TITLE
Detect id_ed25519.pub key

### ISSUE THREAD

**Issue by kpcyrd** [pry0cc/axiom#21]
hey! right now there's only a check for:

```
if [ -f ~/.ssh/id_rsa.pub ]
```
it would be great if it would also check for non-rsa keys, the most popular being ed25519. So if `~/.ssh/id_rsa.pub` doesn't exist you could check for `~/.ssh/id_ed25519.pub` as a fallback. :)

You can test this by generating a keypair with `ssh-keygen -t ed25519`.

**Comment by pry0cc** [comment]
Yes this is awesome!

It is merged! Thank you!

**Comment by kpcyrd** [comment]
@myrdn thanks!
