### ISSUE TITLE
linode private ip ssh help

### ISSUE THREAD

**Issue by nullman0x** [pry0cc/axiom#212]
hi

i want axiom to communicate via private ip such as 192.168.x.x to other nodes
i dont want to use public ip

how to do this ??

**Comment by nullman0x** [comment]
once a fleet is generated
each of the instance can be alloted a private ip via linode control panel

now I want to use the private ip to connect to all other fleet instead of public ip

**Comment by nullman0x** [comment]
if the instance has private ip 

then axiom-ssh wont run

![Uploading image.png…]()

**Comment by nullman0x** [comment]
as observed the file .sshconfig writes both public ip and private ip to .sshconfig if private ip is alloted for the instance

![image](https://user-images.githubusercontent.com/77861653/106934130-c293d180-673f-11eb-9c89-1ae5e42cb701.png)

**Comment by pry0cc** [comment]
I'll think about a fix for this one using the ipv4[] good catch

**Comment by nullman0x** [comment]
ok 
is it possible to use api key of one linode account to create image and create fleet on another account linode api key

**Comment by 0xtavian** [comment]
@nullman0x only if the Axiom image is publicly accessible. I dont know if Lindo offers this but they very well might.

**Comment by nullman0x** [comment]
i am getting a weird error
when I ran axiom-scan 


/root/.axiom/interact/axiom-scp: line 99: rsync: command not found
/root/.axiom/interact/axiom-scp: line 99: rsync: command not found
/root/.axiom/interact/axiom-scp: line 99: rsync: command not found
/root/.axiom/interact/axiom-scp: line 99: rsync: command not found


though the command, the output results did not get collected and result is empty

**Comment by nullman0x** [comment]
subfinder.txt
