### ISSUE TITLE
Add findomain + fff

### ISSUE THREAD

**Issue by KingOfBugbounty** [pry0cc/axiom#218]
Hello pry how are you?

can you add findomain? fff?

https://github.com/Findomain/Findomain

https://github.com/tomnomnom/fff

Thanks bro.

**Comment by 0xtavian** [comment]
@KingOfBugbounty sorry for the late reply, will try to get this done this weekend! great suggestion

**Comment by KingOfBugbounty** [comment]
Thanks @0xtavian :)

**Comment by pry0cc** [comment]
Testing this now...

**Comment by pry0cc** [comment]
https://github.com/pry0cc/axiom/pull/227

Can you try this update?

**Comment by KingOfBugbounty** [comment]
I think you are in trouble pryd

https://ibb.co/BsQj12z

**Comment by 0xtavian** [comment]
thanks for the add @pry0cc 

@KingOfBugbounty you'll have to run axiom-build to install the new tools

**Comment by 0xtavian** [comment]
and you'll have to create a module. I'll see if i can get around to this today.

**Comment by 0xtavian** [comment]
@KingOfBugbounty Findomain module is added.

**Comment by 0xtavian** [comment]
Thanks for the suggestions @KingOfBugbounty. Added both to axiom 8).
