### ISSUE TITLE
Add npm and nodejs in new boxes

### ISSUE THREAD

**Issue by ArpitKubadia** [pry0cc/axiom#221]
I am not sure if this is already getting installed or not, but on creating a new box and typing npm, the output shows that it does not exist.

**Comment by iNoSec2** [comment]
Just add it to the profile you took, nothing more simple than that ;)

**Comment by ibitebyt3s** [comment]
Not sure if it would be a good idea to add `npm` and `nodejs` to the default axiom builds because they add about 500 MB to the disk and some people might not even use them. It's still not a bad idea, I do installed them afterwards.

**Comment by 0xtavian** [comment]
@ibitebyt3s thanks for bumping this. Closing because I’ve noticed the same. It will increase size a lot more than I’d like and will rarely of ever be used. Plus it should be easy enough to install post init/fleet. Thanks again.
