### ISSUE TITLE
Feature request: Rustscan, Feroxbuster

### ISSUE THREAD

**Issue by cocoonkid** [pry0cc/axiom#222]
Please add Rustscan, Feroxbuster as packages.

**Comment by 0xtavian** [comment]
@cocoonkid good call, added 8). Feedback is always appreciated. Thank you for making the suggestion! Dont forget to check out our guide on making simple modules if you ever wanted to look into doing it yourself. https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules 


https://github.com/pry0cc/axiom/blob/master/modules/feroxbuster.json
https://github.com/pry0cc/axiom/blob/master/modules/rustscan.json

**Comment by cocoonkid** [comment]
Absolutely! Thanks
