### ISSUE TITLE
linode 404 every single axiom-build

### ISSUE THREAD

**Issue by evilpacket** [pry0cc/axiom#224]
From a fresh kali instance I recently installed axiom and configured it for linode. I had previously had axiom working on this linode account and had gone through the support process to get bumped beyond 18gb (both times on us-west). Now on the new kali instance every single time I run axiom-build I get a 404 for the image as demonstrated below. I haven't been able to figure out why it's happening...

Any guidance here is appreciated, thanks for the rad tool... Is the linode support request a 1 time process per account? 

```
==> linode: go: downloading golang.org/x/oauth2 v0.0.0-20210210192628-66670185b0cd
==> linode: go: downloading github.com/trivago/tgo v1.0.7
==> linode: go: downloading github.com/fatih/structs v1.1.0
==> linode: go: downloading github.com/xanzy/go-gitlab v0.44.0
==> linode: go: downloading google.golang.org/appengine v1.6.7
==> linode: go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
==> linode: go: downloading github.com/hashicorp/go-retryablehttp v0.6.8
==> linode: go: downloading golang.org/x/time v0.0.0-20201208040808-7e3f01d25324
==> linode: Shutting down Linode...
==> linode: Creating image...
==> linode: Error creating image: [404] Not found
==> linode: Provisioning step had errors: Running the cleanup provisioner, if present...
Build 'linode' errored: Error creating image: [404] Not found

==> Some builds didn't complete successfully and had errors:
--> linode: Error creating image: [404] Not found

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
```

**Comment by pry0cc** [comment]
Would you be able to show me a screenshot of your images tab here: https://cloud.linode.com/images ?

**Comment by evilpacket** [comment]
I also noticed that the console popped up an error that was to the effect of "failed to create image..."

<img width="1088" alt="Screen Shot 2021-02-13 at 3 59 28 PM" src="https://user-images.githubusercontent.com/115769/107864777-94d01c00-6e14-11eb-86cb-f36f66387605.png">

**Comment by evilpacket** [comment]
Looks like I was wrong on the zone.... but I did try both zones to be sure :/

**Comment by pry0cc** [comment]
You're probably hitting your image size limit, I'd recommend deleting these images through the web panel and then trying axiom-build again.

We need to write in a function that automatically deletes the old images - I'll add that to my list :) Please let me know if that works ^^

**Comment by evilpacket** [comment]
You were absolutely correct, deleting all of my images took care of the issue and my axiom-build was successful. I was originally thinking the image size constraint was each individual image not the total amount of images stored...

Thanks for your help!

**Comment by pdelteil** [comment]
This happened to me this time! 

Definitely needs a better error message and an auto delete option.
