### ISSUE TITLE
Execution stops with no reason while running axiom-scan using nuclei module

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#228]
The execution stopped at 50% with no errors.  This happened before but I never found a reason why. 

![Screenshot from 2021-02-16 03-10-17](https://user-images.githubusercontent.com/20244863/108025067-8ea09200-7004-11eb-998f-1a16dfdd69cc.png)

**Comment by pry0cc** [comment]
This is weird - have you tired updating axiom?

axiom-update && axiom-build

**Comment by pdelteil** [comment]
> This is weird - have you tired updating axiom?
> 
> axiom-update && axiom-build

I will retry after the current run finishes or fails.

**Comment by pdelteil** [comment]
Updating solve the issue. 

Thanks.
