### ISSUE TITLE
Axiom Account Setup - ibm cloud provider fail to create ubuntu - on macos

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [pry0cc/axiom#232]
Creating Ubuntu 18.04 Base VSI
FAILED
flag needs an argument: -k

Base IBM Cloud Server ID is 
FAILED
Incorrect Usage: This command requires one argument.

parse error: Invalid numeric literal at line 1, column 5
Waiting for server to initialize. Current phase: 
Upgrading Ubuntu 18.04 to Ubuntu 20.04... multiple reboots ahead
FAILED
Incorrect Usage: This command requires one argument.

parse error: Invalid numeric literal at line 1, column 5

**Comment by 0xtavian** [comment]
repeat https://github.com/pry0cc/axiom/issues/234 - due to same issue with Mac dependencies

**Comment by 4k4xs4pH1r3** [comment]
> repeat #234 - due to same issue with Mac dependencies

dear I tried one more time installing manually in macOS, still fails= https://gist.github.com/4k4xs4pH1r3/2a26c398c56f6bdbe51707a956ad91db

`rm -rf ~/.axiom/ && git clone https://github.com/pry0cc/axiom ~/.axiom/ &&  $HOME/.axiom/interact/axiom-configure`

#

Also i installed in Kali Linux hosted on ibm with 
`bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)`

and appear the same error= https://gist.github.com/4k4xs4pH1r3/5f47e6e017d4b0518acb6048217f3536
