### ISSUE TITLE
Axiom account setup - azure provider fail to create the vm - on macos

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [pry0cc/axiom#233]
/Users/x/antigen/antigen.zsh: line 2: /bin/antigen.zsh: No such file or directory
/Users/x/.zshrc: line 4: antigen: command not found
/Users/x/.zshrc: line 6: autoload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 1: autoload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 2: zmodload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 3: ((: $+functions[compdef] : syntax error: operand expected (error token is "$+functions[compdef] ")
/Users/x/google-cloud-sdk/completion.zsh.inc: line 4: autoload: command not found
/Users/x/.zshrc: line 16: compdef: command not found
/Users/x/.zshrc: line 17: compdef: command not found
/Users/x/.zshrc: line 18: compdef: command not found
/Users/x/.zshrc: line 19: compdef: command not found
/Users/x/.zshrc: line 20: compdef: command not found
/Users/x/.zshrc: line 21: compdef: command not found
/Users/x/.zshrc: line 22: compdef: command not found
/Users/x/.zshrc: line 25: compdef: command not found
/Users/x/.zshrc: line 26: compdef: command not found
/Users/x/.zshrc: line 27: compdef: command not found
/Users/x/.zshrc: line 28: compdef: command not found
/Users/x/.zshrc: line 29: compdef: command not found
/Users/x/.zshrc: line 30: compdef: command not found
/Users/x/.zshrc: line 31: compdef: command not found
Beginning first packer build...
Building image full for provider azure... This can take up to 25 minutes so please be patient!
Ocassionally this will fail, we  don't know why, but it should auto-restart.
Error reading variables in '/Users/x/.axiom/axiom.json': json: cannot unmarshal bool into Go value of type string
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB! 
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!

**Comment by 0xtavian** [comment]
repeat https://github.com/pry0cc/axiom/issues/234 - due to same issue with Mac dependencies
