### ISSUE TITLE
Axiom account setup - do provider fail to create the vm - on macos

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [pry0cc/axiom#234]
/Users/x/antigen/antigen.zsh: line 2: /bin/antigen.zsh: No such file or directory
/Users/x/.zshrc: line 4: antigen: command not found
/Users/x/.zshrc: line 6: autoload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 1: autoload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 2: zmodload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 3: ((: $+functions[compdef] : syntax error: operand expected (error token is "$+functions[compdef] ")
/Users/x/google-cloud-sdk/completion.zsh.inc: line 4: autoload: command not found
/Users/x/.zshrc: line 16: compdef: command not found
/Users/x/.zshrc: line 17: compdef: command not found
/Users/x/.zshrc: line 18: compdef: command not found
/Users/x/.zshrc: line 19: compdef: command not found
/Users/x/.zshrc: line 20: compdef: command not found
/Users/x/.zshrc: line 21: compdef: command not found
/Users/x/.zshrc: line 22: compdef: command not found
/Users/x/.zshrc: line 25: compdef: command not found
/Users/x/.zshrc: line 26: compdef: command not found
/Users/x/.zshrc: line 27: compdef: command not found
/Users/x/.zshrc: line 28: compdef: command not found
/Users/x/.zshrc: line 29: compdef: command not found
/Users/x/.zshrc: line 30: compdef: command not found
/Users/x/.zshrc: line 31: compdef: command not found
/Users/x/.zshrc: line 34: compdef: command not found
/Users/x/.zshrc: line 35: compdef: command not found
/Users/x/.zshrc: line 36: compdef: command not found
/Users/x/.zshrc: line 37: compdef: command not found
/Users/x/.zshrc: line 38: compdef: command not found
/Users/x/.zshrc: line 39: compdef: command not found
/Users/x/.zshrc: line 40: compdef: command not found
/Users/x/.zshrc: line 43: compdef: command not found
/Users/x/.zshrc: line 44: compdef: command not found
/Users/x/.zshrc: line 45: compdef: command not found
/Users/x/.zshrc: line 46: compdef: command not found
/Users/x/.zshrc: line 47: compdef: command not found
/Users/x/.zshrc: line 48: compdef: command not found
/Users/x/.zshrc: line 49: compdef: command not found
Beginning first packer build...
Building image full for provider do... This can take up to 25 minutes so please be patient!
Ocassionally this will fail, we  don't know why, but it should auto-restart.
digitalocean: output will be in this color.

==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored after 1 second 604 milliseconds: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.

==> Wait completed after 1 second 605 milliseconds

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB! 
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!

**Comment by 0xtavian** [comment]
@4k4xs4pH1r3 

Create an Ubuntu 20.04 VM on a cloud provider and install axiom from there. Not all the dependencies are included for Mac during the setup script. If you want to use Macos, you have to manually install the dependencies first https://github.com/pry0cc/axiom/wiki/0-Installation. 

Or you could install axiom on a local VM, Ubuntu 20.04 and Kali 2020.4 are both supported.

**Comment by ZigzagSecurity** [comment]
Hi, I have the same issue here. I'm using a kali vm up to date.

![image](https://user-images.githubusercontent.com/40743997/122606052-5195ec00-d046-11eb-842f-37f2e2f1b1af.png)

**Comment by 0xtavian** [comment]
@ZigzagSecurity the error says ams2 is unavailable, pick a different region with axiom-account-setup (iirc) and rerun axiom-build

**Comment by 0xtavian** [comment]
@4k4xs4pH1r3 @ZigzagSecurity 

Just pushed Mac support to master. Going to close this issue but feel free to reopen if it doesnt work for you
