### ISSUE TITLE
Axiom account setup - gcp provider fail to create the vm - on macos

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [pry0cc/axiom#235]
Axiom Account Setup
You can use this wizard to add new accounts, once made, use axiom-account to switch between profiles
Please enter your provider (do, gcp, ibm, linode, azure): 
>> gcp

Now your account is setup, we need to run a build
A build will take about 25 minutes, spin up a temporary instance, and then snapshot it to use for our future boxes
Starting Build in 5 seconds... Ctrl+C to quit, remember, you can just type axiom-build at any time
Building image full for provider do... This can take up to 25 minutes so please be patient!
Ocassionally this will fail, we  don't know why, but it should auto-restart.
digitalocean: output will be in this color.

==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored after 3 seconds 17 milliseconds: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.

==> Wait completed after 3 seconds 17 milliseconds

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB! 
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!
No SSH public key detected, would you like to generate a fresh pair? y/n 
y
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/x/.ssh/id_rsa): axiom
axiom already exists.
Overwrite (y/n)? y  
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in axiom.
Your public key has been saved in axiom.pub.
The key fingerprint is:

cat: /Users/x/.ssh/id_rsa.pub: No such file or directory
You're running ZSH! Installing Axiom to $PATH...
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 35:  ! ${+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 38:  ! ${+ZSH_AUTOSUGGEST_ORIGINAL_WIDGET_PREFIX} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 42:  ! ${+ZSH_AUTOSUGGEST_STRATEGY} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 45:  ! ${+ZSH_AUTOSUGGEST_CLEAR_WIDGETS} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 48:  ! ${+ZSH_AUTOSUGGEST_ACCEPT_WIDGETS} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 51:  ! ${+ZSH_AUTOSUGGEST_EXECUTE_WIDGETS} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 54:  ! ${+ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 57:  ! ${+ZSH_AUTOSUGGEST_IGNORE_WIDGETS} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 60:  ! ${+ZSH_AUTOSUGGEST_COMPLETIONS_PTY_NAME} : bad substitution
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: syntax error near unexpected token `('
/Users/x/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: `		user:_zsh_autosuggest_(bound|orig)_*)'
/Users/x/antigen/antigen.zsh: line 2: /bin/antigen.zsh: No such file or directory
/Users/x/.zshrc: line 4: antigen: command not found
/Users/x/.zshrc: line 6: autoload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 1: autoload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 2: zmodload: command not found
/Users/x/google-cloud-sdk/completion.zsh.inc: line 3: ((: $+functions[compdef] : syntax error: operand expected (error token is "$+functions[compdef] ")
/Users/x/google-cloud-sdk/completion.zsh.inc: line 4: autoload: command not found
/Users/x/.zshrc: line 16: compdef: command not found
/Users/x/.zshrc: line 17: compdef: command not found
/Users/x/.zshrc: line 18: compdef: command not found
/Users/x/.zshrc: line 19: compdef: command not found
/Users/x/.zshrc: line 20: compdef: command not found
/Users/x/.zshrc: line 21: compdef: command not found
/Users/x/.zshrc: line 22: compdef: command not found
/Users/x/.zshrc: line 25: compdef: command not found
/Users/x/.zshrc: line 26: compdef: command not found
/Users/x/.zshrc: line 27: compdef: command not found
/Users/x/.zshrc: line 28: compdef: command not found
/Users/x/.zshrc: line 29: compdef: command not found
/Users/x/.zshrc: line 30: compdef: command not found
/Users/x/.zshrc: line 31: compdef: command not found
/Users/x/.zshrc: line 34: compdef: command not found
/Users/x/.zshrc: line 35: compdef: command not found
/Users/x/.zshrc: line 36: compdef: command not found
/Users/x/.zshrc: line 37: compdef: command not found
/Users/x/.zshrc: line 38: compdef: command not found
/Users/x/.zshrc: line 39: compdef: command not found
/Users/x/.zshrc: line 40: compdef: command not found
/Users/x/.zshrc: line 43: compdef: command not found
/Users/x/.zshrc: line 44: compdef: command not found
/Users/x/.zshrc: line 45: compdef: command not found
/Users/x/.zshrc: line 46: compdef: command not found
/Users/x/.zshrc: line 47: compdef: command not found
/Users/x/.zshrc: line 48: compdef: command not found
/Users/x/.zshrc: line 49: compdef: command not found
/Users/x/.zshrc: line 52: compdef: command not found
/Users/x/.zshrc: line 53: compdef: command not found
/Users/x/.zshrc: line 54: compdef: command not found
/Users/x/.zshrc: line 55: compdef: command not found
/Users/x/.zshrc: line 56: compdef: command not found
/Users/x/.zshrc: line 57: compdef: command not found
/Users/x/.zshrc: line 58: compdef: command not found
Beginning first packer build...
Building image full for provider do... This can take up to 25 minutes so please be patient!
Ocassionally this will fail, we  don't know why, but it should auto-restart.
digitalocean: output will be in this color.

==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored after 1 second 670 milliseconds: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.

==> Wait completed after 1 second 670 milliseconds

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 nyc2 is unavailable.

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB! 
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!

**Comment by 0xtavian** [comment]
repeat https://github.com/pry0cc/axiom/issues/234 - due to same issue with Mac dependencies
