### ISSUE TITLE
Add the option to select an existing vm in any cloud provider

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [pry0cc/axiom#236]
Thanks in advance please is possible Add the option to select an existing vm in any cloud provider, by id, thank you.

**Comment by 0xtavian** [comment]
@4k4xs4pH1r3 I'm not sure I understand what you mean. axiom creates a Packer image and uses that image to deploy a fleet of servers. With axiom-select you can pick which ones you want to run axiom-scan, axiom-exec, axiom-scp, etc commands on.

**Comment by 4k4xs4pH1r3** [comment]
I mean have the option to select an existing vm/instance created in do, gcp, ibm or azure during the installation wizard

**Comment by 0xtavian** [comment]
you mean have axiom select an existing vm/instances to install axiom onto?

**Comment by 4k4xs4pH1r3** [comment]
> you mean have axiom select an existing vm/instances to install axiom onto?

yes correct

**Comment by 0xtavian** [comment]
@4k4xs4pH1r3 

We now install axiom directly in our default.json provisioner. https://github.com/pry0cc/axiom/blob/ddf8cd3e32e1723ecd9bd864c1ae2fe9c865e757/images/provisioners/default.json#L118
