### ISSUE TITLE
Axiom-scan not working on Linode

### ISSUE THREAD

**Issue by ZultanH** [pry0cc/axiom#237]
I have done the storage upgrade and have successfully made a build but whenever I do axiom-init or axiom-fleet and attempt to run axiom-scan on a module it instantly finishes and produces no results. 
![Screenshot_12](https://user-images.githubusercontent.com/43057246/108584925-cf940000-7390-11eb-9807-ecb5a376374a.png)

**Comment by 0xtavian** [comment]
If you run axiom-update and try again does it work?

**Comment by ZultanH** [comment]
Already latest version

**Comment by 0xtavian** [comment]
Thats odd. I just tested it and its working for me. `axiom-scan targets.txt -m httpx -o httpoutput`

**Comment by 0xtavian** [comment]
You should have seen some log files created with the `$module+$date` naming convention. To check to see if axiom uploaded the target list you can axiom-ssh into an instance and cd to `/home/op/scan/$module+$date/` make sure you can cat in input files and they have been uploaded.

**Comment by ZultanH** [comment]
![image](https://user-images.githubusercontent.com/43057246/108585477-7fb73800-7394-11eb-8c41-dd08c655a592.png)
Appears that the file is trying to upload but maybe it's too large? Not too sure what the issue could be.

**Comment by 0xtavian** [comment]
the input files should be inside those directories. cd into the directory last used `ls -lat`. The first folder is the most recent scan

**Comment by ZultanH** [comment]
just shows 0 output
![image](https://user-images.githubusercontent.com/43057246/108585669-52b75500-7395-11eb-830e-adc366623b17.png)

**Comment by 0xtavian** [comment]
ok exit out of the axiom instance and run `axiom-exec id` just to make sure u can execute on the instances. double check axiom-select to make sure you have the right boxes selected (your first screenshot looks exactly how it supposed to look, but with results obviously).

Are any other modules not working? What is the exact command you are running?

**Comment by 0xtavian** [comment]
closing this issue has i have not been able to reproduce and no mention of this not working on discord. feel free to reopen for whatever reason tho. thanks @ZultanH
