### ISSUE TITLE
[Question] Build, remove and rebuild fleet

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#238]
Hello there,

I'm running a fleet, I want to remove all droplets and then re create the fleet as was before, I could re build the droplet but it takes some time. I was trying to use the backup feature but I'm not sure it would work to do what I want. 

Thanks.

**Comment by 0xtavian** [comment]
@pdelteil So the wiki say "If you want to backup your instance, run axiom-backup <instance> and a local rsync backup will be made of the home directory in ~/.axiom/boxes/." https://github.com/pry0cc/axiom/wiki/A-Quickstart-Guide#backup-your-instance
So it should just copy everything on an instances and downloads it locally. so partial scan results, wordlists etc. Admittedly i've never used axiom-backup. 

That being said, I think we should change axiom-backup to take an image/snapshot of a live axiom VM the user has deployed and configured on their account, and use that image to deploy fleets etc. Is that what you had in mind?

**Comment by pdelteil** [comment]
Hello @0xtavian,

That's exactly what I have in mind.  😄

**Comment by 0xtavian** [comment]
@pdelteil thanks! this has been implemented. https://github.com/pry0cc/axiom/pull/289

**Comment by pdelteil** [comment]
> @pdelteil thanks! this has been implemented. #289

Thanks @0xtavian. 

How is intended to use it? 

1. axiom-backup ID 
2. deploy a fleet using the backup? (How?) ``axiom-init NAME --restore=ID`` ? 

The documentation in the cheat sheet says : 

```
axiom-init <name> --deploy=<profile> --restore=<box> # Init & deploy & restore

the --deploy option allows you to deploy a profile (stored in ~/.axiom/profiles/). --restore will restore a profile. These options can be used together.

```

Which is a bit confusing..

**Comment by 0xtavian** [comment]
thanks. i'll update that. @pdelteil.  run axiom-init, then ssh into the instance you want to configure for feature fleets, axiom-ssh [instance]. set up everything you want (config files, extra tools etc) and exit that ssh session. Run axiom-backup and follow the prompts. then wait a few minutes until the image is created and run axiom-fleet to deploy with your custom image.

**Comment by makma** [comment]
For others (and future me), I faced a similar issue, I wasn't able to sue my snapshot after `axiom-backup` with message
`An image has not been found in this region. Do you need to run 'axiom-build'?`.
I'm running axiom on WSL. The way to fix was to install `doctl`.
1. `cd ~`
2. `wget https://github.com/digitalocean/doctl/releases/download/v1.60.0/doctl-1.60.0-linux-amd64.tar.gz`
3. `tar xf ~/doctl-1.60.0-linux-amd64.tar.gz`
4. `sudo mv ~/doctl /usr/local/bin`

Thank you for a great tool.
Cheers! 🎉

**Comment by pdelteil** [comment]
> For others (and future me), I faced a similar issue, I wasn't able to sue my snapshot after `axiom-backup` with message
> `An image has not been found in this region. Do you need to run 'axiom-build'?`.
> I'm running axiom on WSL. The way to fix was to install `doctl`.
> 
>     1. `cd ~`
> 
>     2. `wget https://github.com/digitalocean/doctl/releases/download/v1.60.0/doctl-1.60.0-linux-amd64.tar.gz`
> 
>     3. `tar xf ~/doctl-1.60.0-linux-amd64.tar.gz`
> 
>     4. `sudo mv ~/doctl /usr/local/bin`
> 
> 
> Thank you for a great tool.
> Cheers! tada

Good to know. And `doctl` should have been installed using the axiom-configure script, probably it failed and you didn't notice.

**Comment by thehackerish** [comment]
I have the same error on AWS: `An image has not been found in this region. Do you need to run 'axiom-build'?` 
I ran the configuration script, and I can confirm that the AMI and snapshots have been created on my AWS account. However, axiom doesn't seem to detect them. The `axiom.json` file has the correct creds and configuration, apart from the `imageid` which is filled with the image name instead. But I changed it in the `axiom.json` file and used the `--image` arg with both values, it did not work.
Has anyone ran into the same issue before?

**Comment by 0xtavian** [comment]
@thehackerish I just tried and its working for me. If you run `axiom-images ls` do you see the image? If its still not working for you, make sure you are updated to the latest version via `axiom-update` and return `axiom-account-setup` and `axiom-build`
