### ISSUE TITLE
[Feature Request]: Ability to have the fleet on the same network

### ISSUE THREAD

**Issue by Roni-Carta** [pry0cc/axiom#245]
Hi ! 

This Feature Request is self-explanatory. It would be awesome to have the entire fleet under the same network. 

For instance we could use one of the instances as an OpenVPN server, and connect the entire fleet to it. This way, a user could also connect on the network and interact with the fleet. 

Eg: Connect on the network and proxy the requests trough the user's Burp Proxy without having to expose the Proxy online. 

Execution steps:
- Deploy the OpenVPN server
- Deploy a fleet
- Upload the OpenVPN config file to the fleet and connect to the server
- Connect the user with the config file to the OpenVPN server
- Show the new User IP clearly on the screen in order to setup properly proxies/web servers etc...

This could be also done using tunnelings (SSH ?) between the fleet and the user local network. However the fleet will not be able to communicate with one another. 

Thank you for your time and consideration, 

Cheers ! 

Roni/Lupin

**Comment by 0xtavian** [comment]
@Roni-Carta thanks for this! I agree, axiom-vpn should have functionality that allows spinning up a VPN server, connecting all axiom instances to that VPN, and set up routing between all instances.

**Comment by 0xtavian** [comment]
@Roni-Carta 

We are considering https://tailscale.com/ or a similar alternative

**Comment by 0xtavian** [comment]
This has been implemented with the `axiom-ssh —just-generate lock` or `axiom-ssh —just-generate private`. This feature allows connecting to axiom instances via the droplets backend Ip. The only limitation is with DO: the axiom controller and fleet must be in the same region to communicate via backend Ip. All other cloud providers work as expected. The user would of course have to install the axiom controller and fleet on the same cloud provider to leverage these changes. :)
