### ISSUE TITLE
gf-completition is missing 

### ISSUE THREAD

**Issue by kusayuzayushko** [pry0cc/axiom#247]
axiom-update -> axiom-build -> axiom-init proxy ->axiom-ssh proxy

```
proxy:~:% zsh
/home/op/.zshrc:source:114: no such file or directory: /home/op/go/src/github.com/tomnomnom/gf/gf-completion.zsh
proxy:~:% find / -name "gf-completion.zsh" 2>&-
/home/op/go/pkg/mod/github.com/tomnomnom/gf@v0.0.0-20200618134122-dcd4c361f9f5/gf-completion.zsh
proxy:~:% 
```

**Comment by 0xtavian** [comment]
@kusayuzayushko you can safely ignore this error. I'll get around to fixing it maybe later today. gf is just complaining that bash completion isnt working

**Comment by iNoSec2** [comment]
for gf autocomplete i use this in my zshrc
#Autocompletion gf tool from tomnomnom
_cmpl_gf() {
	reply=($(ls $HOME/.gf | cut -f1 -d"."))
}
compctl -K _cmpl_gf gf

if that help, cleaner way for me, instead of using an other zsh file

**Comment by dhauenstein** [comment]
I just issued a PR (#331) for this.
