### ISSUE TITLE
Request: AWS EC2 Support

### ISSUE THREAD

**Issue by 303sec** [pry0cc/axiom#25]
This looks like an cool project, but only being able to use Digital Ocean is a bit limited. Are there any plans to add AWS support? And what are the features / benefits of adding a Digital Ocean API key?

**Comment by pry0cc** [comment]
Yes, this is like version 0.02 in the grand scheme of things.

I want to eventually have a full modular rewrite in Go and have support for every single cloud provider possible! I will need help though!

Right now I just want it to be a playground to figure out how I want the Axiom lifecycle to work, and then rewriting should be simple.
