### ISSUE TITLE
[Issue] Axiom-scan error 'zsh:1: command not found: nuclei'

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#250]
I updated axiom and rebuilt it and now I can't run axiom-scan. 

This is the error I get:

``Command: [ nuclei -silent -update-templates ; cat input | nuclei -o output -stats -t /home/op/nuclei-templates -exclude /home/op/nuclei-templates/technologies/waf-detect.yaml -exclude /home/op/nuclei-templates/technologies/tech-detect.yaml -exclude /home/op/nuclei-templates/dns/cname-service-detector.yaml -exclude /home/op/nuclei-templates/dns/mx-service-detector.yaml -exclude /home/op/nuclei-templates/technologies/favicon-detection.yaml ] | Ext: [txt]
Building file structure...[ OK ]
Uploading input files...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.57it/s]
Repeat set to 1
 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 18/20 [00:00<00:00, 179.68it/s]zsh:1: command not found: nuclei
zsh:1: command not found: nuclei
zsh:1: command not found: nuclei
Generated 20 commands in total
zsh:1: command not found: nuclei
Repeat set to 1
zsh:1: command not found: nuclei
zsh:1: command not found: nuclei
zsh:1: command not found: nuclei
zsh:1: command not found: nuclei
zsh:1: command not found: nuclei
zsh:1: command not found: nuclei
```

Same error for every droplet.

**Comment by 0xtavian** [comment]
@pdelteil please use the new nuclei module or specify the full path to the nuclei binary https://github.com/pry0cc/axiom/blob/master/modules/nuclei.json

**Comment by pdelteil** [comment]
@0xtavian thanks.
