### ISSUE TITLE
cannot access axiom instance after new axiom-init

### ISSUE THREAD

**Issue by rossiV1** [pry0cc/axiom#251]
Hi.

i have been using axiom for a while, but currently i am testing a new build using DigitalOcean with higher specs.

I have created a many new instances today (GMT+8) but i cannot access the instances using axiom-ssh or axiom-connect. I also cannot access the axiom instances using the normal ssh command. It says wrong password.

I am aware the password is the DO API key, but still cannot access them.

I also attach some screenshot from my tests.
![image](https://user-images.githubusercontent.com/37831634/110274691-5b9d5d00-800a-11eb-9f32-3f396f8f6a4b.png)

Thank you.

**Comment by 0xtavian** [comment]
@rossiV1 can you run axiom-update and try again please?

**Comment by 0xtavian** [comment]
@rossiV1 also we changed the root password to a unique randomly generated password that is set during the axiom-build process. Shortly after running axiom-build you will see the new password displayed to the terminal, and again at the very end of the build process.

**Comment by rossiV1** [comment]
> @rossiV1 also we changed the root password to a unique randomly generated password that is set during the axiom-build process. Shortly after running axiom-build you will see the new password displayed to the terminal, and again at the very end of the build process.

yeah thank you. i have tested and currently it is working great! thank you for your time
