### ISSUE TITLE
Golang install not detected on Mac OS installation

### ISSUE THREAD

**Issue by hakluke** [pry0cc/axiom#26]
Looks like a great tool! Golang is not detected on my Mac OS install, see the following screenshot:

![image](https://user-images.githubusercontent.com/13975395/84068316-1e208a80-aa0c-11ea-94c9-426de73fa823.png)

It is because I don't have $GOPATH explicitly set as an environment variable, despite having golang installed.

**Comment by pry0cc** [comment]
Ahhh!

Yeah, maybe we should try and tweak that to configure go. I would've assumed a proper Go install would be with the $GOPATH, otherwise, how do you go get stuff? :P

Is this a fresh install?

**Comment by hakluke** [comment]
Yeah I thought so too, but actually mine works fine. I think if there is no $GOPATH defined it just defaults to ~/go

**Comment by pry0cc** [comment]
Ahhh ok - thanks :)

**Comment by broketech** [comment]
running debian, have same situation. I orginally built go, and it magically works with no env variables. I messed around a little bit and changed the test:

`#install go
whereis go; if [ ! $? -eq 0 ] && [[ -z "$GOPATH" ]];then`

I'll let you know if there are any side effects that I can tell.

**Comment by hakluke** [comment]
Nice. I suspect this will work on Mac too. I'll check later. As a workaround I just removed the check entirely.
