### ISSUE TITLE
[Feature request] axiom-deploy for fast socks proxy

### ISSUE THREAD

**Issue by kusayuzayushko** [pry0cc/axiom#260]

**Comment by 0xtavian** [comment]
What exactly are you looking for @kusayuzayushko ?

Currently you should be able to proxy thru your fleet or instances https://github.com/pry0cc/axiom/wiki/Cheatsheet#proxy-through-a-set-of-hosts-or-one

We also have axiom-deploy profile to configure Squid on port 2525, so it can be used as a proxy server for Burp/OWASP Zap etc.

**Comment by kusayuzayushko** [comment]
Oh, i didn't know about Squid. Currently, i use Microsocks to create a socks5 proxy for my browser but have to install it manually on every new instance, to bypass internet censorship. I also know there is an OpenVPN profile, but i don't want to use a VPN for all my traffic, just for my browser.
Will look into Squid, thank you.
