### ISSUE TITLE
not able to install axiom

### ISSUE THREAD

**Issue by abdulsec** [pry0cc/axiom#264]
hii , i have try to install axiom whole the day  but its not work 
I got this error

![Capture](https://user-images.githubusercontent.com/65031578/111888440-ce301480-89dc-11eb-9ebe-36829877fd2b.PNG)

I run also axiom-build multiple time  , but not working

**Comment by 0xtavian** [comment]
@abdulsec please make sure there are no other private images. If Linode has already increased your storage limit to 18GB keep in mind the GB allocated is the sum of all images combined, not just for one image. If previous bad build or  recovery snapshot(s) of Linode VPS is present on the account's image dashboard, they all must be deleted for axiom to be able to properly provision. 


another similar bug is the way axiom-fleet or axiom-init decides which image to build a fleet with is rudimentary, it simply picks the most recently built image on the account and attempts to initialize instances with that. We plan to change this in the future and store the imageid in the account.json and reference it from there, but thats a few days if not a week away.

Hope this helps

**Comment by abdulsec** [comment]
i will build again , when the storage increased to 18 gb

**Comment by abdulsec** [comment]
after they increase my image to 18 gb now , I was able to run axiom-build successfully
