### ISSUE TITLE
Existing DO droplets pulled into fleet ssh config

### ISSUE THREAD

**Issue by cynicXer** [pry0cc/axiom#265]
I have pre-existing infrastructure in DO (several droplets).  It appears that the initialization of a new fleet pulled the IP addresses of existing droplets into the fleet configuration file in ~/.ssh/.config.  Additionally, the configuration file appears to be malformed and I get "Bad configuration option" errors when trying to run commands (e.g. 'ip a') against the fleet.  The SSH configuration options stanza appears incorrect as well.

Here is a sample of the config file, sanitized:

```
Host ubuntu-s-1vcpu-2gb-sfo2-01
        HostName **<pre-existing infra ip address 1>
<pre-existing infra ip address 2>**
        User op
        Port ####

ServerAliveInterval 60
Host *
        ControlMaster auto
        ControlPath  ~/.ssh/sockets/%r@%h-%p
        ControlPersist 600
Host ubuntu-s-2vcpu-2gb-sfo3-01
        HostName **<pre-existing infra ip address 3>**
        User op
        Port ####

ServerAliveInterval 60
Host *
        ControlMaster auto
        ControlPath  ~/.ssh/sockets/%r@%h-%p
        ControlPersist 600
Host ubuntu-s-1vcpu-3gb-sfo2-01
        HostName **<pre-existing infra IP 4>**
        User op
        Port ####

ServerAliveInterval 60
Host *
        ControlMaster auto
        ControlPath  ~/.ssh/sockets/%r@%h-%p
        ControlPersist 600
Host ubuntu-s-1vcpu-2gb-sfo2-01
        HostName **<pre-existing infra IP 4>
<pre-existing infra IP 5>**
        User op
        Port ####


```

**Comment by 0xtavian** [comment]
@cynicXer does any of your pre-existing infrastructure have private and public IPs by any chance?  I think i see the host `Host ubuntu-s-1vcpu-2gb-sfo2-01` (the last host on the list) has two IPs? At this moment axiom cant handle DO infra with public and private IPs, they cant even be on the account for axiom to work. If you see multiple IPs assigned to one host in the ssh config, you should be fine to just remove that extra IP and then run all axiom commands with --cache. Appending --cache forces axiom to use the ssh config file that's already generated. Not appending --cache tells axiom to make an API request to DO to pull down a list of assets that it uses to generate the SSH config. LMK if that works for you.

**Comment by cynicXer** [comment]
I finished with the old droplets in my DO account and deleted them and re-ran axiom-update and axiom-build.  Fleet seemed to work after that.

Closing this issue.
