### ISSUE TITLE
Subfinder Module Issue

### ISSUE THREAD

**Issue by PR3R00T** [pry0cc/axiom#269]
Hey, When installing Axiom I see that it installed Subfinder via the Go command, However theres currently a issue during the build which does not allow the app to install: 

    digitalocean: Installing Subfinder
==> digitalocean: go: downloading github.com/projectdiscovery/subfinder v0.1.1
==> digitalocean: go: downloading github.com/projectdiscovery/subfinder v2.4.6+incompatible
==> digitalocean: go get: module github.com/projectdiscovery/subfinder@upgrade found (v2.4.6+incompatible), but does not contain package github.com/projectdiscovery/subfinder/v2/cmd/subfinder

Ive tried installing manually but get a different issue: 

root@Cloud-Eye:~# GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder
go: downloading github.com/projectdiscovery/subfinder/v2 v2.4.6
go get github.com/projectdiscovery/subfinder/v2/cmd/subfinder: github.com/projectdiscovery/subfinder/v2@v2.4.6: verifying module: checksum mismatch
        downloaded: h1:cbD0WBZqt2gm0soHcsLg5KDyBeTOMIPkUNlAw3kkL6Q=
        sum.golang.org: h1:FMi4v8fT5aq3QSjvAWZH0GMIAGoQRJxLtWWIRLv8ejo=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

 I think there could be a issue with the projectdiscovery package at this time.

**Comment by PR3R00T** [comment]
https://github.com/projectdiscovery/subfinder/issues/405

**Comment by 0xtavian** [comment]
@PR3R00T thanks you, yea we've been waiting for PD to push a fix.

**Comment by 0xtavian** [comment]
thanks i decided to just add the temp workaround https://github.com/pry0cc/axiom/blob/38c47d8f62cfb029521c01ddad90d44e8d47502d/images/provisioners/full.json
