### ISSUE TITLE
[Issue] Axiom-scan keeps asking for ssh password

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#272]
I did a fresh build, doing: 

``axiom-update && axiom-build``

then 

``axiom-fleet -i=20``

And I get

![Screenshot from 2021-03-26 20-19-58](https://user-images.githubusercontent.com/20244863/112701915-aa534f80-8e70-11eb-9200-a60a8d5749e3.png)

The other problem I have is that I don't know how to get out of that screen, I keep pressing CONTROL+C and more password prompts appear.

**Comment by 0xtavian** [comment]
@pdelteil Im not sure why this is happening. What provider are you using? Can you reinstall following the manual install https://github.com/pry0cc/axiom/wiki/0-Installation#manual? Im setting up a fresh box now to test. Can you also check that `~/.axiom/configs/authorized_keys` has the pub key from `~/.ssh/id_rsa.pub` and if not run
 `cat ~/.ssh/id_rsa.pub > ~/.axiom/configs/authorized_keys
` and then rerun axiom-build.

**Comment by 0xtavian** [comment]
As for having to press Control+C multiple times, you might have to press it 20 times (the size of your fleet), or you can hold down control+c and it should force edit.

**Comment by pdelteil** [comment]
> As for having to press Control+C multiple times, you might have to press it 20 times (the size of your fleet), or you can hold down control+c and it should force exit.

Yes, that's what I thought, but new dialogs keep appearing ( I did press it a lot more than 20 times, the counter indicating the droplet number X/20, keeps reseting).

**Comment by 0xtavian** [comment]
Does it issue persist after reboot?

**Comment by pdelteil** [comment]
> @pdelteil Im not sure why this is happening. What provider are you using? Can you reinstall following the manual install https://github.com/pry0cc/axiom/wiki/0-Installation#manual? Im setting up a fresh box now to test. Can you also check that `~/.axiom/configs/authorized_keys` has the pub key from `~/.ssh/id_rsa.pub` and if not run
> `cat ~/.ssh/id_rsa.pub > ~/.axiom/configs/authorized_keys ` and then rerun axiom-build.
> 
> Also note axiom doesnt support SSH keys that have a password, only a cert. The Pub and private keys must be in $HOME/.ssh/
> 
> `ssh-keygen -b 2048 -t rsa -q -N ""`
> `Enter file in which to save the key (/home/user/.ssh/id_rsa): Y`

Thanks @0xtavian, your instructions solved the issue.

**Comment by pdelteil** [comment]
I faced this issue again. This time I did:

Follow the steps above that solve the problem before with no results. 
Full clean installation. (removing .axiom folder, recreated the ssh keys)
axiom-update && axiom-build several times. 

During the installation many errors were displayed related to the user 'op' (user op not found).  

```
=> digitalocean: Traceback (most recent call last):
==> digitalocean:   File "/usr/lib/cnf-update-db", line 26, in <module>
==> digitalocean:     col.create(db)
==> digitalocean:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 94, in create
==> digitalocean:     self._fill_commands(con)
==> digitalocean:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 137, in _fill_commands
==> digitalocean:     with open(f) as fp:
==> digitalocean: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal-updates_main_cnf_Commands-amd64'

```
2
```
=> digitalocean: E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
    digitalocean: Apt-get update
==> digitalocean: E: Sub-process returned an error code
    digitalocean: Apt-get upgrade
==> digitalocean: E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2397 (apt-get)
==> digitalocean: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
    digitalocean: Apt-get install all ma packages
==> digitalocean: E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2397 (apt-get)
==> digitalocean: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
3 
 ```
==> digitalocean: /tmp/script_2446.sh: 37: gem: not found
==> digitalocean: Failed to start docker.service: Unit docker.service not found.
==> digitalocean: Failed to enable unit: Unit file tor.service does not exist.
    digitalocean: Firewall is active and enabled on system startup
==> digitalocean: useradd: group 'docker' does not exist
==> digitalocean: chown: invalid user: ‘op:users’
==> digitalocean: chpasswd: (user op) pam_chauthtok() failed, error:
==> digitalocean: Authentication token manipulation error
==> digitalocean: chpasswd: (line 1, user op) password not changed
==> digitalocean: chown: invalid user: ‘op:users’
```
4 
```
=> digitalocean: su: user op does not exist
==> digitalocean: rm: cannot remove '/home/op/go/src/': No such file or directory
    digitalocean: Installing gf
==> digitalocean: su: user op does not exist
    digitalocean: The password for user op is: wObxBpF0QCcXOMwn7P5OWOWZrTaiwAGkSeXkZXpWogq1KcbSSGdNWYgQWFRfEvU6yhI4PkhhxPdcG15wRfkzxUElB1IM3TRDHuaHAUzXN5MuN3FlACSjS6TyWE
    digitalocean:
    digitalocean:
    digitalocean: Congratulations, your build is almost done!
    digitalocean:
    digitalocean:              axiom is sponsored by...
    digitalocean: ____                       _ _        _____.         _ _
    digitalocean: / ___|  ___  ___ _   _ _ __(_) |_ _   |_   _| __ __ _(_) |___
    digitalocean: \___ \ / _ \/ __| | | | '__| | __| | | || || '__/ _` | | / __|
    digitalocean:  ___) |  __/ (__| |_| | |  | | |_| |_| || || | | (_| | | \__ \
    digitalocean: |____/ \___|\___|\__,_|_|  |_|\__|\__, ||_||_|  \__,_|_|_|___/
    digitalocean:                                   |___/
    digitalocean:
    digitalocean: Read these while you're waiting to get started :)
    digitalocean:
    digitalocean:     - Quickstart Guide: https://github.com/pry0cc/axiom/wiki/A-Quickstart-Guide
    digitalocean:     - Cheatsheet: https://github.com/pry0cc/axiom/wiki/Cheatsheet
    digitalocean:     - Fleets: https://github.com/pry0cc/axiom/wiki/Fleets
    digitalocean:     - Scans: https://github.com/pry0cc/axiom/wiki/Scans
    digitalocean:
    digitalocean:
==> digitalocean: chown: invalid user: ‘op:users’
```

**Comment by 0xtavian** [comment]
@pdelteil  add 
`    "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done"` to
`.axiom/images/provisioners/full.json` and rerun axiom-build. This is a temp fix. Only DO seems to be broken. 

example:
```
      "inline": [
        "fallocate -l 2G /swap && chmod 600 /swap && mkswap /swap && swapon /swap",
        "echo '/swap none swap sw 0 0' | sudo tee -a /etc/fstab",
        "add-apt-repository -y ppa:longsleep/golang-backports",
        "echo Apt-get update",
        "apt-get update -qq",
        "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done",
```

**Comment by pdelteil** [comment]
> @pdelteil add
> ` "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done",` to
> `.axiom/images/provisioners/full.json` and rerun axiom-build. This is a temp fix. Only DO seems to be broken.
> 
> example:
> 
> ```
>       "inline": [
>         "fallocate -l 2G /swap && chmod 600 /swap && mkswap /swap && swapon /swap",
>         "echo '/swap none swap sw 0 0' | sudo tee -a /etc/fstab",
>         "add-apt-repository -y ppa:longsleep/golang-backports",
>         "echo Apt-get update",
>         "apt-get update -qq",
>         "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done",
> ```

That solved the issue! 

Thanks a lot.

**Comment by pdelteil** [comment]
Thanks. I think I will keep the extra `while`.
