### ISSUE TITLE
The generated file is empty after running scan

### ISSUE THREAD

**Issue by C90D** [pry0cc/axiom#274]
![image](https://user-images.githubusercontent.com/58028789/113567208-c01afe80-9640-11eb-97ac-2007eebddde3.png)
After running the scan module, a log file was generated on each server, but it was not synthesized in the end. Is there a problem with my operation?

**Comment by 0xtavian** [comment]
Did you specify an output file? show the command you are running along with the full terminal output. @C90D

**Comment by C90D** [comment]
Sorry, I responded late.
Let me talk about my configuration first. I installed axiom on vultr and then operated fleet.
This time I can use this command to demonstrate
axiom-scan root.txt -m dnsx -resp -o dns.txt
After running the command, I checked the file and found that there was nothing in it. I reinstalled it and it did not solve the problem.
![image](https://user-images.githubusercontent.com/58028789/113649117-7114ae00-96c0-11eb-994e-cb4ebfa9cc59.png)

![image](https://user-images.githubusercontent.com/58028789/113649094-66f2af80-96c0-11eb-80b4-0e1f657c0286.png)

**Comment by anasbousselham** [comment]
httpx your root file before your nuclei scan.

**Comment by C90D** [comment]
Do you mean that you need to use the httpx processing in axiom before scanning with nuclei?I have used httpx separately before using nuclei.@anasbousselham

**Comment by anasbousselham** [comment]
so it's not a nuclei problem, first step please try to run any module like `axiom-scan subs_target -m httpx -o httpx` and after connected to one of your fleet instance `axiom-ssh inst01` and ls your `work` folder, screenshot it or `cat` someone files here...

**Comment by C90D** [comment]
Excuse me, I have a question, shouldn't the files generated after running be in my local? Why doesn't my fleet output the generated results to a local file?

**Comment by 0xtavian** [comment]
@C90D not sure why this is happening for you. Would you mind adding `set -xv` to the top of the axiom-scan script in `$HOME/.axiom/interact/axiom-scan`, running again and providing debug output? Feel free to send us the debug output via Discord or upload it to pastebin just be sure to delete any sensitive data in the debug output beforehand.

**Comment by C90D** [comment]
Excuse me, can you take a look at this file?
[debug.txt](https://github.com/pry0cc/axiom/files/6268482/debug.txt)

**Comment by 0xtavian** [comment]
@C90D

> ![image](https://user-images.githubusercontent.com/58028789/113567208-c01afe80-9640-11eb-97ac-2007eebddde3.png)
> After running the scan module, a log file was generated on each server, but it was not synthesized in the end. Is there a problem with my operation?

so it seems like you didnt provide an output file. You can tell because output is saved to `/root/test/scan+$timestamp` is used for the output file, which happens when you dont provide an output file.

> Sorry, I responded late.
> Let me talk about my configuration first. I installed axiom on vultr and then operated fleet.
> This time I can use this command to demonstrate
> axiom-scan root.txt -m dnsx -resp -o dns.txt
> After running the command, I checked the file and found that there was nothing in it. I reinstalled it and it did not solve the problem.
> ![image](https://user-images.githubusercontent.com/58028789/113649117-7114ae00-96c0-11eb-994e-cb4ebfa9cc59.png)
> 
> ![image](https://user-images.githubusercontent.com/58028789/113649094-66f2af80-96c0-11eb-80b4-0e1f657c0286.png)

it seems like you did provide an output file here but for some reason it didnt work. Are the results saved to the remote instances? look for 'remote logs saved to `/home/op/scan/$module+$timestamp/output`. Or are they saved locally? `/home/.axiom/logs//$module+$timestamp/`


Try reinstalling axiom as a non-root user with sudo privs.

`rm -rf /root/.axiom/`
create a user, add to sudo and su to the user `adduser user` `adduser user sudo` `su user`
`git clone https://github.com/pry0cc/axiom ~/.axiom/`
`bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)`

When you say youre running axiom on vultr do you mean the axiom fleets are VMs on the vultr provider? Or are you just using vultr as a control and then spinning up instances/fleets on DO, Linode, Azure or IBM?

**Comment by C90D** [comment]
Both of these locations have generated results, but they are both separate and not merged. I am trying to install with the user user, and I will give feedback later.
I using vultr as a control and then spinning up instances/fleets on DO.

**Comment by dokkillo** [comment]
Hi, I have same problem. I'm using a non-root user, I launched httpx and the output returns empty.
![imagen](https://user-images.githubusercontent.com/920841/113989224-84ef1a00-9850-11eb-9482-b0b60d13d271.png)

Its all ok, and then.. .when i try to see  the output file, it returns empty.

![imagen](https://user-images.githubusercontent.com/920841/113989304-99cbad80-9850-11eb-953a-1cb2c6940509.png)

**Comment by dokkillo** [comment]
My issue its fixed.... i forget to add axiom to the path
export PATH="$PATH:$HOME/.axiom/interact"

**Comment by C90D** [comment]
Aha, I will try too, thanks bro

**Comment by C90D** [comment]
I can generate files, but httpx does not seem to be installed. @0xtavian
