### ISSUE TITLE
Add tools - 

### ISSUE THREAD

**Issue by KingOfBugbounty** [pry0cc/axiom#275]
Heeeeey dude !!

How are you guys?

https://github.com/devanshbatham/ParamSpider
https://github.com/KathanP19/Gxss
https://github.com/s0md3v/Arjun

I'm looking through the list.
https://github.com/pry0cc/axiom

Thanks bro!!

**Comment by 0xtavian** [comment]
Hey @KingOfBugbounty, we are good thanks for asking!

We actually have an Arjun module already https://github.com/pry0cc/axiom/blob/master/modules/arjun.json. With your ParamSpider module that only leaves gxss :)

**Comment by KingOfBugbounty** [comment]
Woow Perfect my bro !
Thanks my bro, i will close issue. :D
