### ISSUE TITLE
[Error] interlace: error: The path input does not exist!

### ISSUE THREAD

**Issue by blackpungas** [pry0cc/axiom#277]
Hi there, I really tried everything before opening this issue, but I cant figure this out.

The command Im trying to run is the one that appears for ffuf in the documentation.

```
axiom-scan http.txt -m ffuf -o results.csv -threads 1
```

I've got 8 instances and only one ends up running ffuf (the first one), the others outputs this error

"interlace: error: The path input does not exist!"

I tried modifying ffuf.json
I tried with a local dictionary being uploaded

I made myself sure that the dictionary path is fine, and it is indeed, since the first instance runs it right.

**Comment by 0xtavian** [comment]
@blackpungas any chance you have only one target in http.txt?

**Comment by blackpungas** [comment]
ouch, that was the error indeed, thanks, but.. was I doing something wrong?

**Comment by 0xtavian** [comment]
@blackpungas nope. But if you are trying target only one target with the combined power of a fleet, unfortunately axiom doesnt scale like this, yet. But we do have plans in the future to add this functionality. Im going to close this issue but feel free to reopen or post if you have anymore questions.
