### ISSUE TITLE
Uploading local files

### ISSUE THREAD

**Issue by k-sau** [pry0cc/axiom#28]
Hi, 
Is there any way we can upload local files to the droplets? I tried ``scp`` but getting the following error:
``ssh: connect to host x.x.x.x port 22: Connection refused``

**Comment by myrdn** [comment]
I think ssh is listening on port `2266`, you have to specify the port in your `scp` command.

**Comment by pry0cc** [comment]
Yes you do, the recommended way of pushing files would be to:
```
axiom-backup host
axiom-boxes cd host
pwd
```
(Then move all files to this path)
Then
```
axiom-restore host
```
And it will use rsync to push. Not very clean, still thinking of a way to make this slicker. Should probably add a one liner!

**Comment by daehee** [comment]
Old issue, but adding this note for others looking to scp files to & from an axiom box. As noted above, specify port `2266` using `-P` option and username/IP address for the axiom box.

```
scp -P2266 newlist.txt op@138.68.242.68:/home/op/lists/newlist.txt
```
