### ISSUE TITLE
do having issue with API

### ISSUE THREAD

**Issue by khanjanny** [pry0cc/axiom#294]
i have tried to install on my do but it seems somehow not working .any solution ..?

REEOR ::

==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 Size is not available in this region.
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 Size is not available in this region.

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 Size is not available in this region.

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB!
For support, take a screenshot of the last 20 l

**Comment by 0xtavian** [comment]
@khanjanny  run `doctl compute size list` and pick a different size/slug. Add the new size to `.axiom/account/[your-account].json` then rerun axiom-build
