### ISSUE TITLE
Supporting file upload for folders, not only wordlist

### ISSUE THREAD

**Issue by NagliNagli** [pry0cc/axiom#300]
Hi,

for various scans I want to upload a folder, would be cool to specify it as the -wL flag and to support folders as well as files.

cheers.

**Comment by 0xtavian** [comment]
hey @NagliNagli thanks thats def an interesting idea. Question tho, what tool uses a folder as a targetlist/wordlist? also i changed the title, do u agree with that title? :p

**Comment by NagliNagli** [comment]
Hi, specific folder of nuclei templates for example

**Comment by 0xtavian** [comment]
@NagliNagli its actually supported already :). I updated the docs https://github.com/pry0cc/axiom/wiki/Filesystem-Utilities#using-axiom-scp
https://github.com/pry0cc/axiom/wiki/Cheatsheet#copy-files-to-and-from-hosts

thanks! I didnt know this myself.
