### ISSUE TITLE
An Error During Subfinder Scan

### ISSUE THREAD

**Issue by h1-secu** [pry0cc/axiom#307]
Hey guys,
When I run subfinder, axiom asks me the droplets' passwords. I guess its not normal. I put the passwords manually but it doesn't work. 

Output:   

````
kali@kali:~/Desktop$ axiom-scan 1.txt -m subfinder -o subfinder_verizon.txt
Erase is control-H (^H).
              _
  ____ __  __(_)___  ____ ___        ______________ _____
 / __ `/ |/_/ / __ \/ __ `__ \______/ ___/ ___/ __ `/ __ \
/ /_/ />  </ / /_/ / / / / / /_____(__  ) /__/ /_/ / / / /
\__,_/_/|_/_/\____/_/ /_/ /_/     /____/\___/\__,_/_/ /_/

                                    @pry0cc

Module: [ subfinder  ] | Input: [ 1 targets ] | Instances: 5 [ verizon01 verizon02 verizon03 verizon04 verizon05 ]
Command: [ /home/op/go/bin/subfinder -silent -d _target_ -o _output_/_target_ ] | Threads: [ 3 ] | Ext: [txt]
op@1**.***.***.***'s password: 
op@2**.***.***.***'s password:  
````

**Comment by 0xtavian** [comment]
@h1-secu please look into this issue for guidance https://github.com/pry0cc/axiom/issues/272/

**Comment by h1-secu** [comment]
@pdelteil Im not sure why this is happening. What provider are you using? Can you reinstall following the manual install https://github.com/pry0cc/axiom/wiki/0-Installation#manual? Im setting up a fresh box now to test. Can you also check that `~/.axiom/configs/authorized_keys` has the pub key from `~/.ssh/id_rsa.pub` and if not run
 `cat ~/.ssh/id_rsa.pub > ~/.axiom/configs/authorized_keys
` and then rerun axiom-build. 

Also note axiom doesnt support SSH keys that have a password, only a cert. The Pub and private keys must be in $HOME/.ssh/


`ssh-keygen -b 2048 -t rsa -q -N ""`
`Enter file in which to save the key (/home/user/.ssh/id_rsa): [enter]`

_Originally posted by @0xtavian in https://github.com/pry0cc/axiom/issues/272#issuecomment-808593078_

The `~/.axiom/configs/authorized_keys` file is blank. Also there is no `id_rsa.pub` file at `~/.ssh/`

````
kali@kali:~/.ssh$ ls
known_hosts  sockets
````

I just built it manually and added `"while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done",` to `.axiom/images/provisioners/full.json`.
Still same.

**Comment by 0xtavian** [comment]
@h1-secu 

What provider? but the fix should be simple.

Remove `"while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done",`  from `.axiom/images/provisioners/full.json`.
 
you never created an ssh key or added the public key to `~/.axiom/configs/authorized_keys`.
you must have gotten a warning during setup that no ssh keys were identified? bottom line is you need to create SSH pub and private keys with no password  via`ssh-keygen -b 2048 -t rsa -q -N ""`. The SSH keys must be in `~/.ssh/` (which is the default). After you create the SSH keys, add the pub key to the axiom build via `cat ~/.ssh/id_rsa.pub > ~/.axiom/configs/authorized_keys `. After that run axiom-build.
