### ISSUE TITLE
[linode] Specified number of instances fail to spin up

### ISSUE THREAD

**Issue by uBadRequest** [pry0cc/axiom#318]
I asked Linode to increase my limit of linodes I could spin up to 50, but when I run 'axiom-fleet -i=50', I only end up getting 35.

Is there currently anything that would check whether or not the specified number of hosts have successfully started? Or adding to the current fleet while keeping the naming scheme?

**Comment by 0xtavian** [comment]
@uBadRequest Im not sure how to check if the limits have been increased via the cli but I would suggest reaching out to support if you think something is awry.

> Is there currently anything that would check whether or not the specified number of hosts have successfully started?

`axiom-ls` displays the instances on the account that are active. You can also double check with the GUI (you might have to use it from time to time to delete automatic backup images of linodes). 

> Or adding to the current fleet while keeping the naming scheme?

Yes, for example, if you want to add 10 more to an existing fleet execute `axiom-fleet [previous-fleet-prefix] -i=10`
