### ISSUE TITLE
Feature request: masscan range and port combo sharding

### ISSUE THREAD

**Issue by arkenoi** [pry0cc/axiom#319]
Say, you scan a number of IP ranges with masscan. The target has some IDS in place and once it detects something that definitely looks like a port scan it bans your scanner instance. As of now, all target ranges are being split by chunks exactly the way you specify it in the command line, say, you have 3 ranges and 3 scanning instances, each one would get its own. However, if we were able to split all 3 targets across all 3 instances, we could have 3x more scanning rate on each before getting noticed and filtered out, because each target range would be scanned from all available sources!

**Comment by 0xtavian** [comment]
@arkenoi I wouldnt provide axiom-scan with subnets ranges. Instead use mapcidr https://github.com/projectdiscovery/mapcidr to fully expand the ranges beforehand.
