### ISSUE TITLE
"An image has not been found in this region."

### ISSUE THREAD

**Issue by s3ns3ii** [pry0cc/axiom#322]
Whenever trying to start an instance I get this error. The axiom.json file seems good to me so not sure what is this. Any suggestion please? Already ran axiom-build again but didn't help.
Selected the ams2 region on setup, and in the snapshot this one is selected too.

"An image has not been found in this region. Do you need to run 'axiom-build'?"

**Comment by s3ns3ii** [comment]
sorted in the meantime with a reinstall.. :)

**Comment by 0xtavian** [comment]
If that happens again try executing `axiom-account [your-account]` and make sure the imageid located in `~/.axiom/account/[your-account].json` is the correct image tag/title/name. You can check the cloud dashboard web GUI for the image name your are supposed to use.  The naming convention for image names is always axiom-$REGION$TIMESTAMP. If none of that works reinstall :).

**Comment by hi-unc1e** [comment]
Use `axiom-init --image-id 153972312` instead
`--image-id`
- My vendor is DO, solved

**Comment by hi-unc1e** [comment]
> An image has not been found in this region. Do you need to run 'axiom-build'?
The root cause of this error, is due to my `jq` is empty

Here is the bash result
```bash
root@amd-vm:~# file /usr/bin/jq
/usr/bin/jq: empty
```

# solution
- reinstall jq
- use `image_id` instead
