### ISSUE TITLE
A few instances not closing after finishing the task

### ISSUE THREAD

**Issue by Raywando** [pry0cc/axiom#323]
Hi

I ran nuclei module on 36 instances and it worked fine but eventually, this is the output I get after the task finishes and get stuck there

![lQkPyBxUR1](https://user-images.githubusercontent.com/33800255/116775748-4cb4b300-aa6d-11eb-8741-e5944e00c318.png)

These two pictures are from `htop` command that shows a few instances are still not closing and i have to kill them manually
(every time I run the tasks, different random instances get stuck)

![WindowsTerminal_Wx7wPRSBK9](https://user-images.githubusercontent.com/33800255/116775710-1e36d800-aa6d-11eb-9f3d-d9355f1ce41a.png)
![WindowsTerminal_TfC8ZaeTWp](https://user-images.githubusercontent.com/33800255/116775711-20009b80-aa6d-11eb-9a32-e66fc7c66d94.png)

This is the command i used: 
`axiom-scan probed -m nuclei -o nuclei_out`

Nuclei module:
![image](https://user-images.githubusercontent.com/33800255/116775798-b7fe8500-aa6d-11eb-9f7f-0ee88147cd0e.png)

**Comment by 0xtavian** [comment]
@Raywando if you run axiom-exec 'sudo ps aux' you will more likely see nuclei scans still running. You can run nuclei with -stats to display stats to confirm the scans are still running.
