### ISSUE TITLE
[issue] Auto ticket creation failed

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#327]
This is the error I got 

![Screenshot from 2021-05-05 14-37-27](https://user-images.githubusercontent.com/20244863/117192377-a5f34e00-adaf-11eb-981e-2fdba4fa1007.png)

**Comment by mchoji** [comment]
@pdelteil  I have submitted a PR that fixes this issue. In the meanwhile, you can run the command manually 

```bash
linode-cli tickets create --description 'Hello! I have recently installed the axiom framework http://github.com/pry0cc/axiom and would like to request an image increase to 18GB please for the purposes of running packer. Thank you have a great day! - This request was automatically generated by Axiom' --summary 'Image increase request to 18GB for Axiom' --region ''
```

Remember to run `axiom-build` once your ticket gets resolved.
