### ISSUE TITLE
Is there any work on Google Cloud?

### ISSUE THREAD

**Issue by itsgudenuf** [pry0cc/axiom#329]
Just curious.

I enjoy using Linode, but wouldn't mind having GCP as another option.

**Comment by 0xtavian** [comment]
Hey @itsgudenuf, not at the moment. We'd happily merge another one of your awesome PRs if you happen to take it upon yourself.

**Comment by itsgudenuf** [comment]
LoL. OK.
I just wanted to make no one else was working on it.
I started looking at it a few weeks ago before I got into reconFTW.

Let me see what I can do.
