### ISSUE TITLE
Update nuclei templates and add a sensible config

### ISSUE THREAD

**Issue by dhauenstein** [pry0cc/axiom#332]
I'd love to see nuclei templates updated when building a axiom snapshot, for example by executing 
`nuclei -ut` . 
This itself should be a simple task and could be easily configured in the provisioning json file, but additionally I'd like to propose creating a sensibel initial [nuclei config ](https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-config). 
Of course nuclei-templates can be updated by using axiom-exec, but I'd like to use a fleet scan without installing additional tools or executing housekeeping tools. Also, the template would be updated with every `axiom-build`, which should be done anyway to keep all tools updated. 
Any ideas how to implement this nicely?

**Comment by 0xtavian** [comment]
Thanks @dhauenstein for the suggestion and the other PRs! When using nuclei module for axiom-scan (https://github.com/pry0cc/axiom/blob/master/modules/nuclei.json) we actually do update before each run, but adding them to the Packer provisioners is something we can do. 

About the nuclei config I'll have to look into it more but might be worth doing. For what its worth you could always do axiom-init (so just spin up one instance), then axiom-connect (or axiom-ssh $instance-name) and configure that one instance to your liking, such as setting up nuclei config, subfinder API keys etc, then disconnect from that instance, run axiom-backup and follow the prompts. In a few minutes, you'll after a new image is created from the previous instance, you'll be able to deploy fleets with custom image with axiom-fleet. LMK if that suits your needs https://github.com/pry0cc/axiom/wiki/A-Quickstart-Guide#backup-an-initialized-instance---axiom-backup-instance. Thanks again for the PRs!

**Comment by dhauenstein** [comment]
Hey @0xtavian , you are of course absolutely right - nuclei templates get updated with every run. Sorry I missed this and it totally makes sense. 
About the config: I'd love to see a possibility to configure/upload/install additional tools on the axiom snapshot. Now there are several ways: 
1. Use `axiom-ssh` or `axiom-exec` to provision a once build box with your own tools and files. After that run `axiom-backup` again to get an updated snapshot. This all can be poured into a simple bash file.  This feels a bit clumsy, as axiom already is using a provisioner for initial setup, but of course a viable solution. 
2. Maybe the possibility to plug into the provisioning workflow to add local tools/files with the initial setup, without necessarily commiting them to the main repo. 

What do you think?

**Comment by 0xtavian** [comment]
@dhauenstein I think this is a brilliant idea. we can have an option for the user to go to `~/.axiom/config/` and fill out config files and maybe have some default ones as an option. For an example how this could work check out the barebones Packer provisioner https://github.com/pry0cc/axiom/blob/master/images/provisioners/barebones.json. We would just set the source and destination files appropriately and it would auto upload the config to the base image. Im going to work on this sometime next week if I have time.
