### ISSUE TITLE
Temporary failure resolving mirrors.digitalocean.com

### ISSUE THREAD

**Issue by VonTran** [pry0cc/axiom#34]
Running the script on arch (with doctl installed)
> digitalocean: Err:1 http://security.ubuntu.com/ubuntu eoan-security InRelease    
> digitalocean:   Temporary failure resolving 'security.ubuntu.com'                                                                                                     
> digitalocean: Err:2 http://dl.google.com/linux/chrome/deb stable InRelease       
> digitalocean:   Temporary failure resolving 'dl.google.com'                                                                                                           
> digitalocean: Err:3 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu eoan InRelease                                                                         
> digitalocean:   Temporary failure resolving 'ppa.launchpad.net'                  
> digitalocean: Err:4 http://apt.vulns.sexy stable InRelease                                                                                                            
> digitalocean:   Temporary failure resolving 'apt.vulns.sexy'                                                                                                          
> digitalocean: Err:5 https://download.docker.com/linux/ubuntu eoan InRelease      
> digitalocean:   Temporary failure resolving 'download.docker.com'                                                                                                     
> digitalocean: Err:6 http://mirrors.digitalocean.com/ubuntu eoan InRelease                                                                                             
> digitalocean:   Temporary failure resolving 'mirrors.digitalocean.com'                                                                                                
> digitalocean: Err:7 http://mirrors.digitalocean.com/ubuntu eoan-updates InRelease                                                                                     
> digitalocean:   Temporary failure resolving 'mirrors.digitalocean.com'                                                                                                
> digitalocean: Err:8 http://mirrors.digitalocean.com/ubuntu eoan-backports InRelease                                                                                   
> digitalocean:   Temporary failure resolving 'mirrors.digitalocean.com'           
> digitalocean: Reading package lists...                                           
> digitalocean: W: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/eoan/InRelease  Temporary failure resolving 'mirrors.digitalocean.com'                  
> digitalocean: W: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/eoan-updates/InRelease  Temporary failure resolving 'mirrors.digitalocean.com'          
> digitalocean: W: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/eoan-backports/InRelease  Temporary failure resolving 'mirrors.digitalocean.com'        
> digitalocean: W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/eoan-security/InRelease  Temporary failure resolving 'security.ubuntu.com'                   
> digitalocean: W: Failed to fetch http://apt.vulns.sexy/dists/stable/InRelease  Temporary failure resolving 'apt.vulns.sexy'                                           
> digitalocean: Installing sn0int                                                  
> digitalocean: W: Failed to fetch https://download.docker.com/linux/ubuntu/dists/eoan/InRelease  Temporary failure resolving 'download.docker.com'
> digitalocean: W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease  Temporary failure resolving 'dl.google.com'                            
> digitalocean: W: Failed to fetch http://ppa.launchpad.net/longsleep/golang-backports/ubuntu/dists/eoan/InRelease  Temporary failure resolving 'ppa.launchpad.net'
> digitalocean: W: Some index files failed to download. They have been ignored, or old ones used instead.                                                               
> digitalocean: Reading package lists...                                                                                                                                
> digitalocean: Building dependency tree...                                                                                                                             
> digitalocean: Reading state information...                         
> digitalocean: E: Unable to locate package sn0int                                                                                                                      
> digitalocean: Provisioning step had errors: Running the cleanup provisioner, if present...                                                                            
> digitalocean: Destroying droplet...                                              
> digitalocean: Deleting temporary ssh key...                          
> Build 'digitalocean' errored: Script exited with non-zero exit status: 100.Allowed exit codes are: [0]

Error occurs shortly after creating the GPG pubkey
Build fails because the urls are not resolving on the box.

**Comment by pry0cc** [comment]
Yeah this is a weird issue, we're setting the DNS to 1.1.1.1 so I'm not sure why that would conflict with it... It works sometimes and sometimes not.

**Comment by pry0cc** [comment]
Maybe we should set the DNS to Google, maybe this is CloudFlare DNS acting crazy?

**Comment by codered** [comment]
I am not seeing this on digital ocean. @pry0cc - maybe you can close this?
