### ISSUE TITLE
[Question] Linode instances 2 GB RAM

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#344]
Hello there,

Why default Linode instances are not the smaller size (and cost [double] 10$ per month). Wouldn't run correctly on a 1 GB instance or it just a bug while creating the fleets? 

Thanks.

**Comment by 0xtavian** [comment]
@pdelteil its not a mistake. We noticed a significant performance increase with $10 a month boxes vs $5, which of course the user has the option to change during axiom-account-setup

**Comment by pdelteil** [comment]
Thanks for your answer. 

Maybe a message with the price could be included during the installation/config process.
