### ISSUE TITLE
Other vps support 

### ISSUE THREAD

**Issue by shelu16** [pry0cc/axiom#348]
Hi I show there is 3 4 vps provide support to install vps . Can you make way to install othere then digital Ocean or any vps I can install

**Comment by 0xtavian** [comment]
I dont fully understand what you mean.  Currently, DigitalOcean, IBM Cloud, Linode and Azure are officially supported providers. Are you asking to install on a different cloud provider? If so, what cloud provider? @shelu16

**Comment by 0xtavian** [comment]
Closing as possible repeat issue https://github.com/pry0cc/axiom/issues/236
