### ISSUE TITLE
1.axiom wrong directory 

### ISSUE THREAD

**Issue by anasbousselham** [pry0cc/axiom#349]
Hi,
I have this issus, the 1.axiom is wrong
`cp: cannot create regular file '/root/1.axiom/tmp/gospider+1622043286/merge/output/www_my_com': No such file or directory`

**Comment by 0xtavian** [comment]
can you make sure to update to the latest version and try again? if that doesnt work try changing the names of your target list and output file/folder name to something random and try again. thanks @anasbousselham

**Comment by anasbousselham** [comment]
It is working now but however I have a lot files with ext. ~1~ with different size like this :

-rwxr-xr-x 1 root root 4.1K May 30 10:12 www_mywebsite_com

-rwxr-xr-x 1 root root 116K May 30 10:12 www_mywebsite_com.~1~

**Comment by 0xtavian** [comment]
@anasbousselham I'm unable to reproduce. Can you try again and reopen the issue if needed?  make sure you are using the modules we provide and if not, paste the module you are using. thank you
