### ISSUE TITLE
axiom-scan: cp: Argument list too long

### ISSUE THREAD

**Issue by bhutch** [pry0cc/axiom#352]
Hello,

When the list of targets is large, axiom-scan may run into problems during merge operations. The cp "glob" could exceed the maximum command size (ARG_MAX).

For example, when merging directories, line 227 may present problems:

            cp -r $tmp/output/* $tmp/merge

Mode set to directory... Merging directories...
/home/axiom/.axiom/interact/axiom-scan: line 227: /usr/bin/cp: Argument list too long

A possible workaround:
find $tmp/output -type f -print0 | xargs -0 -I{} cp {} $tmp/merge

That's the only "Argument list too long" I've encountered. It may be worth rewriting the following two lines if these globs could experience a similar problem:

            cp -r --backup=t $tmp/output/*/* $tmp/merge
            cp -r $tmp/output/*/* $tmp/merge

**Comment by 0xtavian** [comment]
@bhutch thanks, working on a fix in this branch. https://github.com/pry0cc/axiom/blob/gee/interact/axiom-scan.

**Comment by 0xtavian** [comment]
this has been pushed to master. However we'll also need to replace this line and likely a few more https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan#L181

**Comment by 0xtavian** [comment]
@bhutch done! https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan do let us know if you run into this issue again.

**Comment by QinHsiu** [comment]
Hello, I have the same problem, the result as follow:
-bash: /bin/cp: Argument list too long
Could you find a way to solve it?
