### ISSUE TITLE
Digital Ocean - Enable IPV6 when creating the instance

### ISSUE THREAD

**Issue by Techbrunch** [pry0cc/axiom#357]
It would be great to enable IPV6 when creating droplet (or at least have the option to enable it).

This would enable port scan using IPV6.

This can be done with doctl using the `--enable-ipv6` flag.

Source: https://docs.digitalocean.com/reference/doctl/reference/compute/droplet/create/

Workaround: https://docs.digitalocean.com/products/networking/ipv6/how-to/enable/#on-existing-droplets

**Comment by Techbrunch** [comment]
According to this page: https://docs.digitalocean.com/products/networking/ipv6/

> You cannot enable IPv6 on Droplets created from custom images.

Which is weird since you can do it using the web interface. Maybe this means that it cannot be done at creation time.

Setting ipv6 to true in do.json:

```json
{
  "builders": [
    {
      "type": "digitalocean",
      "ssh_username": "root",
      "snapshot_name": "{{ user `snapshot_name` }}",
      "api_token": "{{ user `do_key` }}",
      "image": "ubuntu-20-04-x64",
      "region": "{{ user `region`  }}",
      "size": "s-1vcpu-1gb",
      "ipv6": true
    }
  ]
}
```

It worked when building the image but not when creating new droplet from the image.

**Comment by 0xtavian** [comment]
@Techbrunch I'll try to look into this over the weekend, just been very busy. For what its worth Linode seems to have IPV6 automatically enabled

**Comment by darkc0d37** [comment]
@Techbrunch  @0xtavian  this can be done by modifying ```do-funcations.sh``` file 
This is the pull request https://github.com/pry0cc/axiom/pull/377/commits/24f8c1c77bffe4d7f274310ffde0632d7e52ac63

**Comment by 0xtavian** [comment]
thanks! Closing this. Reopen if there are any more issues.
