### ISSUE TITLE
[Issue] Packages not installed on Ubuntu 18

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#360]
Hello,

This is an issue for users trying to make axiom work on Ubuntu 18.

I don't know why, but the installation script won't install ruby and python3-pip. You need to install them manually. 

`sudo apt install ruby python3-pip`

This does work in Ubuntu 20.x.

**Comment by 0xtavian** [comment]
@pdelteil Ubuntu 18 is not supported due to these issues.

**Comment by pdelteil** [comment]
Understood. Thanks.
