### ISSUE TITLE
Clean up shell functions

### ISSUE THREAD

**Issue by ResistanceIsUseless** [pry0cc/axiom#361]
I want to open discussion for cleaning up .zshrc and maybe consider splitting out some of the program specific shell functions in their own file or folder. This would make it easier to add more and keep things organized. 

Also, I noticed that playbooks aren't really used currently. Is that correct? Maybe we use playbooks for multi-step actions for things like one-liners and functions for more utility functions related to axiom like starting and stopping a container.

Anyways, let me know what you think and maybe we can hash that out and I'll do a pull on documentation.

**Comment by 0xtavian** [comment]
answered in discussions
