### ISSUE TITLE
Project Discoverys Interactsh

### ISSUE THREAD

**Issue by 0xBrewz** [pry0cc/axiom#363]
I think this would be a good feature for us that dont use burp collabator.. the framework already has the requirements and the project discovery suite on it.. i didnt see it in the list so thought adding it would be good and not much work at all

Tool: https://github.com/projectdiscovery/interactsh

Related Blogposts: 
https://blog.projectdiscovery.io/interactsh-release/
https://blog.projectdiscovery.io/nuclei-interactsh-integration/

**Comment by 0xtavian** [comment]
@0xBrewz thanks for the suggestion, its been committed to dev. will push to master today
