### ISSUE TITLE
Does add tools like xray or awvs to scan some normal web vul for this is a good idea?

### ISSUE THREAD

**Issue by gkfnf** [pry0cc/axiom#368]

**Comment by 0xtavian** [comment]
@gkfnf Im not sure I've heard of awvs, can you send a link? As for xray, there are a few that I know of, with the most popular one being https://github.com/chaitin/xray. However, as they note on their page "xray is not open source". I have heard good things about this software thru the grapevine but wont add it to axiom's images by default before of its closed source nature. That being said, I think xray would be best suited for an optional axiom-deploy(https://github.com/pry0cc/axiom/blob/master/interact/axiom-deploy) profile  (https://github.com/pry0cc/axiom/tree/master/profiles ). There isnt much documentation on these however but its not very code heavy. Im going to close this issue as we wont be adding xray to a default axiom image any time soon.
