### ISSUE TITLE
problema com a instalação do axiom.

### ISSUE THREAD

**Issue by froboot** [pry0cc/axiom#369]
ola, estou com esse problema ao tentar instalar o axiom, ja fiz varias coisas e mesmo assim continua dando o mesmo erro. ja excluir o droplet, instalei de novo, e dar o mesmo erro. poderia ajuda ?
(==> digitalocean: Erro ao criar droplet: POST https://api.digitalocean.com/v2/droplets: 422 criar este (s) droplet (s) excederá seu limite de droplet
==> digitalocean: Excluindo chave SSH temporária ...
Erro ao criar 'digitalocean': Erro ao criar droplet: POST https://api.digitalocean.com/v2/droplets: 422 criar este (s) droplet (s) excederá seu limite de droplet

==> Algumas compilações não foram concluídas com sucesso e apresentaram erros:
-> digitalocean: Erro ao criar droplet: POST https://api.digitalocean.com/v2/droplets: 422 criar este (s) droplet (s) excederá seu limite de droplet

==> Builds terminados, mas nenhum artefatos foram criados.
Sua construção falhou :( Por favor, dê uma olhada nos erros!
Isso pode acontecer às vezes, se você tiver um erro [404] ao usar o Linode, provavelmente é porque você precisa solicitar suporte para um tamanho de imagem maior para 18 GB!
Para obter suporte, faça uma captura de tela das últimas 20 linhas e abra um problema em https://github.com/pry0cc/axiom/issues
Às vezes, apenas executar uma compilação novamente pode funcionar, então tente pelo menos uma vez: 'axiom-build', obrigado!)
![erro4](https://user-images.githubusercontent.com/85703684/122658395-057ca180-d143-11eb-828f-0b42ba25d1ce.png)

**Comment by 0xtavian** [comment]
@froboot 

as the error says: you exceed your droplet limit. you either have to delete an instance or ask DO nicely to increase your droplet limit allowance
