### ISSUE TITLE
New box username & onetime password in email

### ISSUE THREAD

**Issue by x1mdev** [pry0cc/axiom#37]
Hi @pry0cc,

Thank you for this awesome tool!

I've noticed some strange/unnecesary behaviour when starting up new boxes.

Example: `axiom-init hades --restore=hades && axiom-ssh --tmux && axiom-rm hades -f` (Economics)

Whenever I run this command and detach from tmux the box is destroyed. Now, when I'm executing the same command again everything works just fine. No passwords etc have been provided etc because the system works with `ssh`. Nothing strange so far.

However, when checking my inbox I noticed that I've received a couple of emails from Digital Ocean containing the information for my new box:

>Your new Droplet is all set to go! You can access it using the following credentials:

```
Droplet Name: pain
IP Address: 1.1.1.1 (dummy)
Username: root
Password: deadbeefdeadbeefdeadbeef
```
>For security reasons, you will be required to change this Droplet’s root password when you login. You should choose a strong password that will be easy for you to remember, but hard for a computer to guess. You might try creating an alpha-numerical phrase from a memorable sentence (e.g. “I won my first spelling bee at age 7,” might become “Iwm#1sbaa7”). Random strings of common words, such as “Mousetrap Sandwich Hospital Anecdote,” tend to work well, too.

>As an added security measure, we also strongly recommend adding an SSH key to your account.

Is it possible to disable this? Axiom does not use the root user with password authentication as far as I'm aware of and the SSH key has been added during setup.

Kind regards,
x1m

**Comment by pry0cc** [comment]
Yeah, so we change all that and DO has an automated email solution. 

Personally I just ignore the emails and have an email filtering rule to automatically mark them as read and archive them, if you can find a better way to disable emails though, I will definitely add it to the readme :)

**Comment by xxzxcuzx-me** [comment]
It looks that the only way to "disable" that notification is to specify ssh key at droplet creation. You can do that by adding --ssh-keys flag to the "doctl compute droplet create" command, for example: --ssh-keys 4d:23:e6:e4:8c:17:d2:cf:89:47:36:b5:c7:33:40:4e
The fingerprint of the ssh key must match a key added by you to your account. You can list ssh keys with command: doctl compute ssh-key list
You can also add that key automatically with: doctl compute ssh-key create --public-key public_key_content key_name
So it's possible to add ssh key to an account at configuration and then just specify that ssh-key during droplet creation to get rid of that irritating email notification.
You can read more about it here: https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client
at the "Creating resources" paragraph.
I can create pull request with solution to this issue if you want. It would add ssh key to an account in axiom-configure and specify --ssh-keys flag in interact/includes/functions.sh and providers/do-functions.sh
