### ISSUE TITLE
Axiom can't build out Linode Machine due to image request size

### ISSUE THREAD

**Issue by frederickalcantara** [pry0cc/axiom#371]
Based on the message instructions, I get the following. 

<img width="1183" alt="Screen Shot 2021-06-22 at 5 39 44 PM" src="https://user-images.githubusercontent.com/23001248/123003182-d6537380-d380-11eb-8cb9-3a357d5aa7b8.png">

Please advise on how I can fix this, to provide some context I'm using a MacOS machine (Big Sur 11.4).

**Comment by 0xtavian** [comment]
@frederickalcantara for linode you have to open a support ticket and request a larger image size. During axiom-account-setup there should be an option to auto submit a ticket (https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/linode.sh#L90). If that is in fact the issue, they take around 24 hours or so to respond. Oddly, the error you are getting says 404 image not found. LMK if you have already made the request and have confirmed Linode has increased your allowed size, it could be a different isuse.
