### ISSUE TITLE
Nuclei v2 Update

### ISSUE THREAD

**Issue by ikuamike** [pry0cc/axiom#38]
Nuclei v2 has been released, is it possible to update the build?

**Comment by pry0cc** [comment]
Yes! The packer image builds from the direct GitHub nuclei.

https://github.com/pry0cc/axiom/blob/4095fcad4ab909d6e99f9bb2731e76d7bf3207fb/packer.json#L195

So all you have to do is run axiom-build and wait for it to build a new image for you.

**Comment by ikuamike** [comment]
For version 2 you need 

`GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei`

Note the **v2**

Here's the reference from their page.
https://github.com/projectdiscovery/nuclei#from-source

**Comment by pry0cc** [comment]
Would you be able to open a PR so I can merge it?

pry0cc

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ikuamike** [comment]
Would be happy to, I'll try on Monday. I'm afk this weekend. Thanks.
