### ISSUE TITLE
LiveTargetsFinder - can it be added to the modules please? Thanks.

### ISSUE THREAD

**Issue by rohancollab** [pry0cc/axiom#382]
hi @pry0cc ,

Thanks for this awesome framework! Really amazed by the speed. Just asking if is it possible to add LiveTargetsFinder by allyomalley to Modules?

LiveTargetsFinder - https://github.com/allyomalley/LiveTargetsFinder

Thanks a lot.

**Comment by 0xtavian** [comment]
@rohancollab If youre interested in adding a module please take a look at: https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules. The tool sounds interesting but there isnt any new functionality here that isnt already in the other tools (especially considering its just a wrapper for other tools), another concern is that it might not be maintained (last commit was Nov 2019).
