### ISSUE TITLE
No module kxss

### ISSUE THREAD

**Issue by MR-pentestGuy** [pry0cc/axiom#385]
There is no module called kxss here

**Comment by 0xtavian** [comment]
@MR-pentestGuy thanks for pointing that out. if youre interested in making a module take a look here https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules. Otherwise it will have to wait until I have time

**Comment by MR-pentestGuy** [comment]
well made one 
 here you go 

[{
        "command":"cat input | /home/op/go/bin/kxss | tee output",
        "ext":"txt"
}]

**Comment by 0xtavian** [comment]
sweet, added! https://github.com/pry0cc/axiom/blob/master/modules/kxss.json
