### ISSUE TITLE
Feature suggestion: --no-logs switch so logs are not saved

### ISSUE THREAD

**Issue by Regala** [pry0cc/axiom#389]
Axiom produces a large number of logs with each run, which grow over time and very easily takes up dozens of GB storage space. 
![image](https://user-images.githubusercontent.com/1380527/125762297-f6f0a732-e41b-40b5-9fa7-474bede023d7.png)

The proposal is something like a `--no-logs` flag which would NOT save logs after the run, both locally and remotely (remotely it's even harder to track). 

Even better would be to be able to specify that global behavior in a config file e.g. `axiom.json`. Further, cli flags could overwrite this value when you are testing stuff out.

**Comment by 0xtavian** [comment]
@Regala the first part is done and pushed to master :D

**Comment by 0xtavian** [comment]
https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan#L294 changing `keeplogs` to `false` also works

**Comment by 0xtavian** [comment]
@Regala closing this but feel free to open it back up or @ me if you still want the `keeplogs` switch in `axiom.json`.

**Comment by Regala** [comment]
@0xtavian definitely would like the `keeplogs` flag in `axiom.json` - easier than changing my dozens of axiom-* calls 🙈

**Comment by rober-h** [comment]
@Regala the only script that uses the keeplogs flag is axiom-scan, currently. Moving it to axiom.json would make it easier to incorporate that flag into other scripts ofc. I'll see what I can do. :)

**Comment by Regala** [comment]
< 3
