### ISSUE TITLE
[Bug] Axiom hangs when a job in a ssh session is silent for a long time

### ISSUE THREAD

**Issue by Regala** [pry0cc/axiom#397]
Sometimes axiom hangs for no apparent reason; when you press enter you get the following message:
![unknown](https://user-images.githubusercontent.com/1380527/126197016-b547a129-e869-4c91-ab11-ddf0c6e297f4.png)
Talking with @0xtavian, this might be due to the ssh session which is dropped/closed if no output in the terminal exists; which might happen if it's a long scan and you use `-silent` flags or redirect the output to `/dev/null`. 

A current workaround might be allowing the scan to actually print some output, which _should_ keep the session alive.

**Comment by pdelteil** [comment]
I'm getting something similar: 

``Connection to 45.ZZ.XX.YY closed by remote host.`` 

In my case the ssh session is not silent since I'm printing stats every 3 minutes (nuclei)

**Comment by NitescuLucian** [comment]
I confirm this issue. My workaround is using axiom-exec to check if all commands are done and then scp the local output files from the fleet.

**Comment by 0xtavian** [comment]
thanks @NitescuLucian. I plan on fixing this sooner or later. Hopefully before the new year. This is the problem code.  https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan#L774-L777 and https://github.com/pry0cc/axiom/blob/master/interact/axiom-scan#L791

**Comment by 0xtavian** [comment]
this fix has been pushed to master.
