### ISSUE TITLE
ffuf and -mr

### ISSUE THREAD

**Issue by eugui** [pry0cc/axiom#405]
Hi,

I'm trying to use axiom-scan + ffuf module with "-mr" (regex) but is not working.

This command is ok and I have a vulnerability:
./ffuf -u W1/W2 -w URLS:W1 -w wordlist/ffuf_test:W2 -mr "\b(?:a|b|c)\b" -t 10

Using axiom-scan I don't have a vulnerability:
axiom-scan URLS -m ffuf -wL wordlist/ffuf_test -mr "\b(?:a|b|c)\b" --cache --threads 3 -o ffuf_test.csv

**Comment by 0xtavian** [comment]
@eugui for more reliable usage edit the module itself, dont enter it in the command line. So for your example, just add the -mr etc to the `~/.axiom/module/ffuf.json` file.
