### ISSUE TITLE
axiom-power - turn on / turn off / restart 

### ISSUE THREAD

**Issue by RapidEU** [pry0cc/axiom#406]
Hiya,

I've had a problem with some of my droplets, I was overloading their resources and they got stuck, I was unable to execute any command. 

The only solution was to restart all of them manually, I was wondering maybe you could implement and perform direct API interaction to restart/turn on/turn off the machines, that could solve further problems, luckily I only had 3 machines and not 30 :p.

**Comment by 0xtavian** [comment]
@RapidEU working on this but might not get it finished until after DEFCON. These are the corresponding cli calls that have to be integrated for reference.

Linode

linode-cli linodes shutdown $(instance_id $instance_name)
linode-cli linodes boot  $(instance_id $instance_name)
linode-cli linodes reboot  $(instance_id $instance_name)

Digital Ocean

doctl compute  droplet-action  power-off  $(instance_id $instance_name)
doctl compute  droplet-action power-on  $(instance_id $instance_name)
doctl compute  droplet-action reboot  $(instance_id $instance_name)

IBM Cloud

ibmcloud sl vs power-off  $(instance_id $instance_name)
ibmcloud sl vs power-on  $(instance_id $instance_name)
ibmcloud sl vs reboot  $(instance_id $instance_name)

Azure

az vm start -g axiom -n  $(instance_id $instance_name)
az vm restart -g axiom -n  $(instance_id $instance_name)
az vm stop -g axiom --name  $(instance_id $instance_name)
