### ISSUE TITLE
axiom-scan --list not working correctly

### ISSUE THREAD

**Issue by mchoji** [pry0cc/axiom#407]
I think it is expected that one should use `axiom-scan --list` to list the available modules so they know which to use. However, when issuing this command, we are presented to an error:

![image](https://user-images.githubusercontent.com/7395296/127556025-562344c2-d1e6-4316-905c-8aef8e7b5bc6.png)

This command only works if we specify a module to use, which seems counter intuitive:

![image](https://user-images.githubusercontent.com/7395296/127556302-543808b8-40b0-4524-92ae-af1831f62778.png)

**Comment by 0xtavian** [comment]
@mchoji thanks this is a bug. I'll push a fix shortly

**Comment by 0xtavian** [comment]
@mchoji thanks. should be working now.
