### ISSUE TITLE
generate sshconfig from axiom-select and allow private ips

### ISSUE THREAD

**Issue by RapidEU** [pry0cc/axiom#410]
Hiya,

As previously discussed with @0xtavian , this request is being made because of errors I have encountered when using it in an active environment. I have a machine which doesn't have a public ip's, therefore when trying to execute any command, the sshconfig that is generated is malformed because of a missing HostName field value.

So the suggestion is basically to make it so the sshconfig is regenerated when using axiom-select and only with the selected machine.

Other than that, an option to generate the sshconfig using private ip's is another suggestion that came up while investigating what was the problem I had. 

Thanks :)

**Comment by 0xtavian** [comment]
@RapidEU i think we are going to hold off on generating the ssh config for only those selected. We’ve added communicating via private IPs https://github.com/pry0cc/axiom/issues/245. Please let me know if I missed anything. Maybe there’s another reason to reconsider this.
