### ISSUE TITLE
Axiom-Scan Error (Solved)

### ISSUE THREAD

**Issue by Marcio861** [pry0cc/axiom#415]
i have docker kali clear in WSL
Linux 0b17d71b0c3a 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux

I running axiom-scan targetsfile -m subfinder -o outputfile.txt

output:

usage: interlace [-h] [-t TARGET | -tL FILE] [-e EXCLUSIONS | -eL FILE]
                 [-threads THREADS] [-timeout TIMEOUT] [-pL FILE]
                 (-c COMMAND | -cL FILE) [-o OUTPUT] [-p PORT] [--proto PROTO]
                 [-rp REALPORT] [-random RANDOM] [--no-cidr] [--no-color]
                 [--no-bar] [--repeat REPEAT] [-v | --silent]
interlace: error: The path input does not exist!

help me
please

**Comment by saajanbhujel11** [comment]
Yes, buddy, this error is shown in the WSL. 

But, I noticed that if we create one more blank line in our target domain file, then the error does not show anymore.

Let suppose you have created 4 fleets, and you want to perform the scan with this cmd:  `axiom-scan targetsfile -m subfinder -o outputfile.txt`. 

So, For performing the above cmd without any error, Only you have to create a text file for your target with one extra blank line. like below pic:
<img width="239" alt="1" src="https://user-images.githubusercontent.com/87616854/128760756-20fadaeb-2a7f-43e6-af59-9a057a632f87.png">

**Comment by Marcio861** [comment]
not work blank line:

https://prnt.sc/1lzc657

not work with nmap too

https://prnt.sc/1lzebqu

**Comment by Marcio861** [comment]
I am solved:

apt install rsync -y

**Comment by 0xtavian** [comment]
@Marcio861 thanks, i think the `-y` was missing from the script preventing the instal of rsync? https://github.com/pry0cc/axiom/blob/master/interact/axiom-configure#L95

**Comment by 0xtavian** [comment]
> Yes, buddy, this error is shown in the WSL.
> 
> But, I noticed that if we create one more blank line in our target domain file, then the error will not show.
> 
> Let suppose you have created 4 fleets, and you want to perform the scan with this cmd: `axiom-scan targetsfile -m subfinder -o outputfile.txt`.
> 
> So, For performing the above cmd without any error, Only you have to create a text file for your target with one extra blank line. like below pic:
> <img alt="1" width="239" src="https://user-images.githubusercontent.com/87616854/128760756-20fadaeb-2a7f-43e6-af59-9a057a632f87.png">

@saajanbhujel11 generally this error can be ignored. its just interlace complaining that it doesnt have a target

**Comment by Marcio861** [comment]
> hanks, i think the `-y` was missing from the script preventing the instal of rsync? https://github.com/pry0cc/axiom/blob/master/interact/axiom-configure#L95

I'm not sure -y reference to auto accept install;
had to test axiom-scp separately and said there was no rsync, bingo! I installed rsync
