### ISSUE TITLE
Is Possible?

### ISSUE THREAD

**Issue by Marcio861** [pry0cc/axiom#416]
Is Possible running axiom-scan  with:   cat urlsfile.txt | waybackurls?

**Comment by 0xtavian** [comment]
https://github.com/pry0cc/axiom/wiki/Cheatsheet#scanning-using-a-fleet
`axiom-scan urlsfile.txt -m waybackurls -o myoutputfile` is likely what you are looking for. Also check out `axiom-scan --help` and `axiom-scan --list`. To understand how it works, read: https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules
