### ISSUE TITLE
after choising reconftw as provisioner i show this erros , i'm using digitalocean 

### ISSUE THREAD

**Issue by amineethic** [pry0cc/axiom#422]
digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 creating this/these droplet(s) will exceed your droplet limit
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 creating this/these droplet(s) will exceed your droplet limit

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 creating this/these droplet(s) will exceed your droplet limit

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB!
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!

**Comment by 0xtavian** [comment]
@amineethic the error "creating this/these droplet(s) will exceed your droplet limit" means you already have the max number of droplets on your account. You have to either delete one or ask support nicely for an increase.

**Comment by amineethic** [comment]
@0xtavian thanks a lot for your help
