### ISSUE TITLE
cant run axiom-scan with --spinup flag if axiom-init or axiom-fleet hasnt been previously run

### ISSUE THREAD

**Issue by 0xtavian** [pry0cc/axiom#436]
Reported by c4nh0t0 on 0x00sec discord:

unable to run axiom-scan with spinup flag without first running axiom-init or axiom-fleet. Axiom-scan was erroring because it expects selected.conf and ~/.axiom/sshconfig files to be present but aren't created until after first run of axiom-init or axiom-fleet. 
Even tho axiom-scan is overwriting those when spinup flag is specified, there is a bug expecting those files to exist.

**Comment by c4nh0t0** [comment]
Some evidences about it:

![001](https://user-images.githubusercontent.com/8462973/130797207-8b17e371-117a-46b9-b88f-bf2707dbe0a3.png)

![002](https://user-images.githubusercontent.com/8462973/130797232-76b07420-4080-4adc-a9a3-6ed5738d0ac1.png)

![003](https://user-images.githubusercontent.com/8462973/130797255-aa6df5f8-04f2-4bfc-a1ba-49cdbb4a7221.png)

**Comment by 0xtavian** [comment]
I believe this is fixed with the latest commit. Reopen if not :)

**Comment by c4nh0t0** [comment]
Not sure if its fixed. I run a fresh install in my VPS and got this error:

![temp](https://user-images.githubusercontent.com/8462973/133124883-357d2bab-804f-4c63-b2b2-c7cc29a39c24.png)
