### ISSUE TITLE
Go get deprecation

### ISSUE THREAD

**Issue by ResistanceIsUseless** [pry0cc/axiom#452]
"Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead."
https://golang.org/doc/go-get-install-deprecation

We will probably need to keep track of packages that break because of this. Also, on that topic I wonder if there would be any value in writing test cases for axiom. Make sure apps are being installed on the vm among other things.

**Comment by 0xtavian** [comment]
@ResistanceIsUseless fixed in here https://github.com/pry0cc/axiom/pull/455 :)
