### ISSUE TITLE
linkfinder module does not return any result.

### ISSUE THREAD

**Issue by jcr7301** [pry0cc/axiom#457]
Command: `axiom-scan urls.txt -m linkfinder -o output.txt` returns an empty file.
Executing the same input in my host or in an instance does return a correct file.
Playing with the module I can make it write the result in a local axiom instance but I cannot get it in my host in anyway unless I do axiom-scp with all the instances, which a find a little bit too much of a workaround.

linkfinder module: 
```
[{
  "command":"python3 -u /home/op/recon/LinkFinder/linkfinder.py -d -i _target_ -o cli | tee -a _output_",
  "ext":"txt",
  "threads":"4"
}]
```
Also, I can't find any reference to 'threads' in the json definition or 'target/output' with underscores in the wiki or other documentation.

**Comment by 0xtavian** [comment]
@jcr7301 good catch. The module should be fixed now. Let me know if you like the output. Also there is no documentation about one-shot modules e.g. modules with `_target_` threads `_output_` `_cleantarget_` etc. I'll try to write some today, I've been meaning to get to it. Thanks again.

**Comment by jcr7301** [comment]
Thanks. It's working now
