### ISSUE TITLE
Custom secretfinder module returns parse error.

### ISSUE THREAD

**Issue by jcr7301** [pry0cc/axiom#459]
I've created my own custom module for SecretFinder (https://github.com/m4ll0k/SecretFinder) in a similar way as linkfinder (https://github.com/pry0cc/axiom/commit/2c412835d3f9aa1f17af2b66f84994adb0277e5e) but it returns `parse error: Invalid numeric literal at line 1, column 2` for whatever input I've tried.

Command:

`axiom-scan urls.txt -m secretfinder -o result.txt`

SecretFinder module:
```
[{
  "command":"python3 -u /home/op/recon/SecretFinder/SecretFinder.py -i _target_ -o cli | tee -a _output_/_cleantarget_",
  "ext":"",
  "threads":"4"
}]
```

**Comment by 0xtavian** [comment]
@jcr7301 Is your module in `~/.axiom/modules/secretfinder.json`? if you run `axiom-scan --list` do you see your module?

**Comment by jcr7301** [comment]
Yep, that was, I had a typo in the name. Sorry.
Closing...
