### ISSUE TITLE
Unable to ssh after axiom-configure

### ISSUE THREAD

**Issue by codered** [pry0cc/axiom#46]
First off, great work! 

After I run configure, I am unable to connect to the droplets that are created. I am on Mac OS Mojave. The same keys work for my existing droplets without any problem. 

Any ideas why this could be happening? Any tips to troubleshoot?

**Comment by pry0cc** [comment]
Can you tell me what error you get? A screenshot?

**Comment by codered** [comment]
I spun up a droplet called "hades". I enabled -vvv in the connect script you have. 

[~/.axiom/configs]$ axiom-ssh hades                                                                                                                  *[master][ruby-2.4.0]
ssh: connect to host 64.227.80.139 port 2266: Operation timed out
[~/.axiom/configs]$ axiom-connect hades                                                                                                              *[master][ruby-2.4.0]
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/hsingh/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug2: resolve_canonicalize: hostname 64.227.80.139 is address
debug2: ssh_connect_direct
debug1: Connecting to 64.227.80.139 [64.227.80.139] port 2266.

**Comment by codered** [comment]
I am using Mac OS Mojave. Can you tell me where I should look in the code to ensure that the key is added correctly?

**Comment by codered** [comment]
I think I found the problem. It is not using the pub key that is on my computer, (i did a recovery on the droplet and dropped in. I found that it has some random key in there). I believe this has to do with the check during configuration.
