### ISSUE TITLE
[feature] make axiom-configure smarter and less aggressive

### ISSUE THREAD

**Issue by mchoji** [pry0cc/axiom#463]
The current axiom-configure script do a lot of things, including installing packages from native repos and tools. However, it does that without checking if dependencies are already satisfied, which sometimes can break environment. Example: it will install a specific Go version without checking if it is already installed. Also, it will try download and install provider's script more than once during the process.

My suggestion would be to make axiom-configure check if every dependency is satisfied or not while letting the user knows about it and just indicating the proper command to be run by them instead doing it automatically (unless an option like -y is given). This should give more flexibility to the user. In case everything is ok, the script would proceed with the configuration itself.

**Comment by 0xtavian** [comment]
@mchoji Thanks for the suggestion. I'll try to make changes this week to implement the ideas.
