### ISSUE TITLE
Unable to find nuclei-templates folder in a newly  initialized instance

### ISSUE THREAD

**Issue by xaeroborg** [pry0cc/axiom#474]
Please have a look at the below screenshot. I initialized a single instance and checked for the nuclei-templates under /home/op of the initialized instance but I couldnt find it. Do I need to manually drop the templates folder into my instance? or am I doing something wrong?

I actually wanted to test running all the templates against a target and to use the entire folder as the wordlist - which I wanted to try if it works with axiom, I found that the nuclei-templates folder was missing; unless I am doing something wrong
![image](https://user-images.githubusercontent.com/33274680/137583994-bc842df9-e425-4e2f-88f0-5152d8bd8f1b.png)

**Comment by pdelteil** [comment]
If you run nuclei it will download all the templates automatically.

**Comment by xaeroborg** [comment]
@pdelteil I was actually going through your blog(https://medium.com/bug-bounty/how-to-run-subfinder-with-axiom-dc2fec98920c) :) and the way you explained was so clear. Just that I am getting used to axiom, I am discovering new things related to its inner working. BTW is it possible to run all the templates against a site? I do know that you raised a similar issue in the past but I am not too sure. In nuclei syntax one would use "-t nuclei-templates/" but in axiom its -w right?
