### ISSUE TITLE
Command axiom-fleet testy -i=80 creates 3 instances

### ISSUE THREAD

**Issue by NitescuLucian** [pry0cc/axiom#491]
I updated the axiom and build a new image in the past 1h and now I am getting the following:

```
root@axiom:~# axiom-fleet testy -i=80
Initializing new fleet 'testy' with 3 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ testy01 testy02 testy03  ]
Initialized instance 'testy02' at 'xxx'!
Initialized instance 'testy03' at 'xxx'!
Initialized instance 'testy01' at 'xxx'!
```

What should I do? How can I help?

**Comment by NitescuLucian** [comment]
I just seen https://github.com/pry0cc/axiom/pull/486 I think the documentation should also be updated. All good :100: !

The new command is: `axiom-fleet testy -i 80`

**Comment by 0xtavian** [comment]
@NitescuLucian thanks. I updated the Fleets page [here](https://github.com/pry0cc/axiom/wiki/Fleets#usage) and made some edits to the [Filesystem-Utilities](https://github.com/pry0cc/axiom/wiki/Filesystem-Utilities#axiom-fleet) page. The same info can be found running `axiom-fleet -h`,`axiom-fleet --help` or `axiom-fleet help`.
