### ISSUE TITLE
Some error while trying to deploy it in digital ocean

### ISSUE THREAD

**Issue by sreenathr10** [pry0cc/axiom#492]
Building image default for provider do... This can take up to 25 minutes so please be patient!
Ocassionally this will fail, we  don't know why, but it should auto-restart.                                                                                            
digitalocean: output will be in this color.

==> digitalocean: Creating temporary ssh key for droplet...
==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 creating this/these droplet(s) will exceed your droplet limit
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 creating this/these droplet(s) will exceed your droplet limit

==> Some builds didn't complete successfully and had errors:
--> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 creating this/these droplet(s) will exceed your droplet limit

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB! 
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!
You may need to restart your shell: /usr/bin/bash

**Comment by 0xtavian** [comment]
@sreenathr10  as the error indicates, "creating this/these droplet(s) will exceed your droplet limit". If you want to increase your droplet limit you have to open a ticket with DO support.
