### ISSUE TITLE
Axiom Fleet Initialization Failure

### ISSUE THREAD

**Issue by xaeroborg** [pry0cc/axiom#494]
I got this error while creating multiple axiom fleets. I updated and built last week but I didnt use it right away and I ran it today and got this error. Out of 3 fleets just the first one got created. 

![image](https://user-images.githubusercontent.com/33274680/141318668-cc565a3e-1b63-4fce-8e44-163e75b6ce6a.png)

**Comment by 0xtavian** [comment]
@xaeroborg thanks, there were some small syntax changes last week. you can exclude the equal sign. Run `axiom-fleet -h` `axiom-init -h` and `axiom-ssh -h` to see the new help menus and syntax. 
https://github.com/pry0cc/axiom/issues/491

**Comment by xaeroborg** [comment]
@0xtavian The fleet creation worked like a charm. I then ran axiom-select rayaan* and all the three instances got selected. But when I ran axiom-scan against targets with Nuclei module 1) In the first run it couldnt SSH into the fleets created. 2) Only one of the fleet could finish the scan and it looked like it was stuck. I havent seen this behavior until the recent update. 
![image](https://user-images.githubusercontent.com/33274680/141430710-dd02b785-184a-4312-87da-e963e68c5450.png)

**Comment by 0xtavian** [comment]
@xaeroborg please try to recreate. its possible that one instance had an issue during provisioning and is taking longer than expected.

**Comment by xaeroborg** [comment]
@0xtavian As requested I have recreated the steps all the way from creating instance and then firing the instances to run a scan and it took 10mins and nothing was scanned.
![image](https://user-images.githubusercontent.com/33274680/141444133-51256cc2-153f-47ce-aa63-85053bb9536d.png)

I then ran the scan but also added axiom-select rayaan* and then ran the same scan and this was the result
![image](https://user-images.githubusercontent.com/33274680/141446326-04ebca69-da6c-4b87-9946-f25db7d678d6.png)

**Comment by 0xtavian** [comment]
@xaeroborg this issue is very likely fixed by just waiting a few moments a bit longer after initialization before using the instances. Also make sure you dont have two fleets with the [same names](https://github.com/pry0cc/axiom/issues/487). I'll work on it this weekend. I see the issue and its that the instance simply hasnt finished provisioning, yet you are trying to use it. this is why its taking a long time to get results back, because SSH has to timeout. The cloud provider could also be temporarily slow, causing a delay in provisioning, it happens form time to time.

Before using a fleet, maybe try running `axiom-exec id` to make sure they are fully provisioned. In any case, I will make improvements this weekend.

**Comment by xaeroborg** [comment]
@0xtavian I completely agree to what you've mentioned above. 1) I have always made sure that I dont end up using redundant/same instance names 2) I also had the suspicion that the VPS service would have been down(eventhough I though it could be unlikely but from time to time these things happen if not always) 3) I will definitely use `axiom-exec id` after initializing the fleets and before deploying them to scan. Thank you for your prompt response. Have a wonderful weekend.

just an update that based on what you advised me above and everything worked like a charm. 
![image](https://user-images.githubusercontent.com/33274680/141609330-36859bda-3c0e-4dfd-8801-3a3eb6e45770.png)
![image](https://user-images.githubusercontent.com/33274680/141609425-c695f945-571b-4281-9bc0-69d96a9aecda.png)

Requesting you to add in wiki to advise users to perform an `axiom-exec id` just to make sure all the SSH configs have been added to the respective fleets initialized and then move ahead to the scanning. 
Any users who are trying to add fleets

**Comment by stefan-stojanovic-s** [comment]
Can confirm this issuee still keeps on happening. I am using linode. There is also a problem where instances get created but FAIL to boot power on. Again, I am not sure if this is just linode shenanigans or axiom problem

**Comment by devcoinfet** [comment]
I agree this just started happening to me today and the first term that came up led to you guys.  The thing is I also am having intermittent boot issues via linode instances and i am aware of you guys figuring out it is the 5 machine limit with linode but my concern is I'm experiencing the same issues with boots as well as the strange 408's on a  self coded ssh / paramiko setup via python so this is quite cool to see I'm not the only one hitting a  wall spinning up linode

**Comment by 0xtavian** [comment]
@devcoinfet glad we helped track down your issue as well!

> My thought is to add about a 5 second delay between creation of workers at least I'm seeing a better response from the linode-cli via remote docker instance this way

I was thinking about this as well. I'll have to play around with it.
