### ISSUE TITLE
Weird bug when creating a fleet

### ISSUE THREAD

**Issue by stefan-stojanovic-s** [pry0cc/axiom#495]
Here are the logs, not sure what could be the problem here, given that it happens quite randomly.
I have a script which adds new 5 instances to a fleet with sleep time in-between, up until a certain threshold is reached.
When this error occurs, It gets into infinite recursion since it doesn't fulfil the threshold at all.
If its of any value, I am using linode for this.

```
Initializing new fleet 'raven' with 5 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
/home/dev/.axiom/interact/axiom-fleet: line 156: 09: value too great for base (error token is "09")
/home/dev/.axiom/interact/axiom-fleet: line 234: [: -gt: unary operator expected
Selected: [ raven01 raven02 raven03 raven04 raven05 raven08 raven09 ] 
Fleet started succesfully!
To delete your fleet, just run axiom-rm "raven*" -f
```

```
Initializing new fleet 'raven' with 5 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
/home/dev/.axiom/interact/axiom-fleet: line 156: 09: value too great for base (error token is "09")
/home/dev/.axiom/interact/axiom-fleet: line 234: [: -gt: unary operator expected
Selected: [ raven01 raven02 raven03 raven04 raven05 raven08 raven09 ] 
Fleet started succesfully!
To delete your fleet, just run axiom-rm "raven*" -f
```

**Comment by pdelteil** [comment]
Hi,

Please add the relevant section of your script here to check it out.

**Comment by 0xtavian** [comment]
@stefan-stojanovic-s please run `cd ~/axiom/ && git pull` to get the latest code. You might have to delete your changes and then readd them to the newest code. We'll also need whatever code you added so we can troubleshoot, as the issue seems to be in your alternations. Feel free to join us on discord.

**Comment by 0xtavian** [comment]
closing as non-repeatable. feel free to reopen or comment with more info.
