### ISSUE TITLE
Accidentally deleted my own instance along with axiom fleet

### ISSUE THREAD

**Issue by xaeroborg** [pry0cc/axiom#499]
**Request to add this option** 
I spun up 4 instances and I usually delete the instance with this command `axiom-rm "fleet-name*" -f `but for some reason axiom gave  me a msg to use `axiom-rm "\*" -f`  and as much as this command says that this will delete all the instances including the main instance I never thought axiom would do it, I thought there was a fail-safe option where it would not delete the parent instance but just few mins ago it did in the blink of an eye. 

Could @0xtavian you please kindly add this option where the rm command doesnt delete the parent instance

**Comment by 0xtavian** [comment]
@xaeroborg you have to escape the asterix
`axiom-rm "fleet-name\*” -f`.

**Comment by 0xtavian** [comment]
@xaeroborg keep in mind the failsafe option is the optional `-f`, excluding this forces the user to confirm each action deletion.

Would a detailed help menu be sufficient?

**Comment by xaeroborg** [comment]
@0xtavian thanks that would be great. Fortunately Linode has a feature to recover the deleted instance and now I have got back the entire linode as it was. 

Glad to know that excluding the -f is the best failsafe option, excellent!
