### ISSUE TITLE
Go lang fails to install tools

### ISSUE THREAD

**Issue by rixtrayker** [pry0cc/axiom#506]
Fix provisioners by specifying go-lang version ( 1.16 ) go get works **`golang-1.16-go`**

**Comment by 0xtavian** [comment]
hi @rixtrayker what cloud provider and pwhich rovisioner are you using? if azure please see https://github.com/pry0cc/axiom/issues/501 for a tmp workaround.

**Comment by 0xtavian** [comment]
if its not azure, which tools were having issues installing? thanks again. @rixtrayker

**Comment by rixtrayker** [comment]
It was DigitalOcean, I can't remember the tools but many tools failed due to go install

**Comment by 0xtavian** [comment]
Please update to the latest version of axiom and run rerun axiom-build. go get is deprecated. Since we install go1.17.1 and build using go install, there should be no reason to downgrade go and use
A deprecated build method. Whatever issues you were having I suspect will be fixed by using the latest code. 
If you happen to run into the issue again after using the latest code please note and tool name. Closing as this is unrepeatable

**Comment by rixtrayker** [comment]
https://github.com/pry0cc/axiom/blob/master/images/provisioners/reconftw.json

"/bin/su -l op -c 'go get -u github.com/ffuf/ffuf'",
        "echo 'Installing cf-check'",
        "/bin/su -l op -c 'go get -u github.com/dwisiswant0/cf-check'",
        "echo 'Installing Gxss'",
        "/bin/su -l op -c 'go get -u github.com/KathanP19/Gxss'",
and more ...
you keep using ( go get ) in reconftw last update 25 days ago

I didn’t check all provisioners

**Comment by rixtrayker** [comment]
Notice go install doesn't work with every go app so you may need to test before using "go install"

**Comment by 0xtavian** [comment]
Only the reconFTW provisioner still uses `go get`, ( using  go version go1.17.5.) Sometime in the future we'll have to update the reconFTW provisioner  similar to how we updated Default and Barebones https://github.com/pry0cc/axiom/blob/master/images/provisioners/default.json. For now it doesnt seem to be breaking anything, unless i've missed something

Packer ( aka axiom-build) terminal output with errors like these can generally be ignored. 

```
    digitalocean: Installing ffuf
==> digitalocean: 100 82854  100 82854    0     0   919k      0 --:--:-- --:--:-- --:--:--  919k
==> digitalocean: go: downloading github.com/ffuf/ffuf v1.3.1
==> digitalocean: go: downloading github.com/pelletier/go-toml v1.8.1
==> digitalocean: go: downloading github.com/pelletier/go-toml v1.9.4
==> digitalocean: go get: installing executables with 'go get' in module mode is deprecated.
==> digitalocean:       Use 'go install pkg@version' instead.
==> digitalocean:       For more information, see https://golang.org/doc/go-get-install-deprecation
==> digitalocean:       or run 'go help get' or 'go help install'.
    digitalocean: Installing cf-check
==> digitalocean: go: downloading github.com/dwisiswant0/cf-check v1.0.3
==> digitalocean: go get: installing executables with 'go get' in module mode is deprecated.
==> digitalocean:       Use 'go install pkg@version' instead.
==> digitalocean:       For more information, see https://golang.org/doc/go-get-install-deprecation
==> digitalocean:       or run 'go help get' or 'go help install'.
    digitalocean: Installing Gxss
==> digitalocean: go: downloading github.com/KathanP19/Gxss v0.0.0-20211130125458-f7409d3e98b8
==> digitalocean: go get: installing executables with 'go get' in module mode is deprecated.
==> digitalocean:       Use 'go install pkg@version' instead.
==> digitalocean:       For more information, see https://golang.org/doc/go-get-install-deprecation
==> digitalocean:       or run 'go help get' or 'go help install'.
    digitalocean: Installing Crobat
==> digitalocean: go: downloading github.com/cgboal/sonarsearch v0.0.0-20211123154547-0f3168bf7f1e
    digitalocean: Installing waybackurls
==> digitalocean: go get: module github.com/cgboal/sonarsearch@upgrade found (v0.0.0-20211123154547-0f3168bf7f1e), but does not contain package github.com/cgboal/sonarsearch/crobat
==> digitalocean: go: downloading github.com/tomnomnom/waybackurls v0.0.2
==> digitalocean: go get: installing executables with 'go get' in module mode is deprecated.
==> digitalocean:       Use 'go install pkg@version' instead.
==> digitalocean:       For more information, see https://golang.org/doc/go-get-install-deprecation
==> digitalocean:       or run 'go help get' or 'go help install'.
```

if you happen to see any tool that doesnt get installed let me know.

```
➜  ~ axiom-ssh kare01

 ▄▄▄      ▒██   ██▒ ██▓ ▒█████   ███▄ ▄███▓
▒████▄    ▒▒ █ █ ▒░▓██▒▒██▒  ██▒▓██▒▀█▀ ██▒
▒██  ▀█▄  ░░  █   ░▒██▒▒██░  ██▒▓██    ▓██░
░██▄▄▄▄██  ░ █ █ ▒ ░██░▒██   ██░▒██    ▒██
 ▓█   ▓██▒▒██▒ ▒██▒░██░░ ████▓▒░▒██▒   ░██▒
 ▒▒   ▓▒█░▒▒ ░ ░▓ ░░▓  ░ ▒░▒░▒░ ░ ▒░   ░  ░
  ▒   ▒▒ ░░░   ░▒ ░ ▒ ░  ░ ▒ ▒░ ░  ░      ░

Public IP: [redacted] - Instance: kare01

➜  ~ ls go/bin 
Gxss  assetfinder  crlfuzz  dnsx  gau      getJS  github-endpoints   gospider  httpx              nuclei   qsreplace  subjs   urlprobe     zdns
anew  cf-check     dalfox   ffuf  gauplus  gf     github-subdomains  gron      interactsh-client  puredns  subfinder  unfurl  waybackurls

```

**Comment by 0xtavian** [comment]
I was asking talking to @six2dez yesterday about how we should go about refreshing reconFTW provisioner

**Comment by six2dez** [comment]
> I was asking talking to @six2dez yesterday about how we should go about refreshing reconFTW provisioner

Updated provisioner https://github.com/pry0cc/axiom/pull/509/commits/64d44975cc4fc7ea82439245007f691ac66e8f3e
