### ISSUE TITLE
Problem when showing output with -o

### ISSUE THREAD

**Issue by VinzelOps** [pry0cc/axiom#507]
Hello, is there a solution to return the -o function as output for each module's output? I always try -o for output, but only logs are output +[modules]*

**Comment by 0xtavian** [comment]
@VinzelOps i believe if you specify only `-o` without an output filename, the filename will be `+1234567890`. However if you don’t provide any output arguments at all ( so just don’t type `-o` in the command line), the default output filename will be $module+$timestamp. If that’s not what you were looking for let me know.

**Comment by NitescuLucian** [comment]
I confirm the issue, previously `-o` allowed arbitrary file names. Example: `-o nmap.txt` previously created `nmap.txt`. Is intended to be a copy of axiom logs folder?

**Comment by 0xtavian** [comment]
@NitescuLucian @VinzelOps 
I see the issue thanks so much for reporting I’ll have to fix out momentarily. this happened after the recent update.

**Comment by 0xtavian** [comment]
@NitescuLucian @VinzelOps it’s fixed with the latest push to master.  I forgot to remove a line after testing. Thanks again for bringing this up. If everything works as expected feel free to close the issue.

**Comment by VinzelOps** [comment]
Thank you very much
