### ISSUE TITLE
Add an ability to select a region during axiom-configure

### ISSUE THREAD

**Issue by kusayuzayushko** [pry0cc/axiom#51]
By default, it's "San Francisco, United States", so please let us select different locations or add an automated selection based on ping measurement.

**Comment by pry0cc** [comment]
This is a fantastic idea!

**Comment by pry0cc** [comment]
How would you do this?

**Comment by rst10124492** [comment]
> How would you do this?

Not the original poster but this was something I had on my mind too and was going to implement something quickly at some point during the next weekends when I could find some free time.

After we request the api key we can use it to query the api for the available regions, display them to the user ask them to pick one or have them use a default one.

**Comment by pry0cc** [comment]
Added `axiom-account-setup` which includes a configuration helper for region!

**Comment by 0xtavian** [comment]
this has been long resolved :)
