### ISSUE TITLE
axiom-build ERROR:unfortunately, can not find builder path

### ISSUE THREAD

**Issue by d3sh1n** [pry0cc/axiom#514]
![image](https://user-images.githubusercontent.com/78736442/149302601-babb9bf8-7ab9-40c7-befb-310ac1ba5fd2.png)
How should I solve this problem?

**Comment by 0xtavian** [comment]
@d3sh1n 
What cloud provider are you using? I believe one way to get this error is by selecting `gcp` which is currently not fully supported ( I'll remove that option soon to avoid confusion). If not selecting gcp, first make sure you are on the latest code by running axiom-update ( aka `cd ~/.axiom/ && git pull`), next you might have to run `axiom-account-setup` or `axiom-configure` again.

**Comment by greckko** [comment]
Same issue with default digitalocean provider and ubuntu 18.04 image.

**Comment by 0xtavian** [comment]
@greckko @d3sh1n thanks I’ll investigate later today. In the meantime using Ubuntu 20.04 should work.

**Comment by 0xtavian** [comment]
@greckko @d3sh1n Thanks again for bringing this to my attention. I just pushed a fix to master. The bug only affected Ubuntu 18.04, Ubuntu 20.04 had no issues. Please run `axiom-update` and `axiom-configure`. If everything works as expected feel free to close this issue.
