### ISSUE TITLE
如何异步请求的同时更换代理ip?

### ISSUE THREAD

**Issue by shihaochen666** [pry0cc/axiom#516]

**Comment by 0xtavian** [comment]
@shihaochen666 

Something like [this](https://0x00sec.org/t/advanced-axiom-usage-axiom-scan/24600)?

```
Axiom-proxy
Start a proxy round-robin listener against all our nodes in our fleet.

axiom-proxy 'fire*' --single
Run curl over and over again to show it’s different ips

This proxy can be used in burp 
curl --socks5-hostname 127.0.0.1:1337 https://ipinfo.io | jq
curl --socks5-hostname 127.0.0.1:1337 https://ipinfo.io | jq -c
curl --socks5-hostname 127.0.0.1:1337 https://ipinfo.io | jq -c
curl --socks5-hostname 127.0.0.1:1337 https://ipinfo.io | jq -c
curl --socks5-hostname 127.0.0.1:1337 https://ipinfo.io | jq -c
curl --socks5-hostname 127.0.0.1:1337 https://ipinfo.io | jq -c
```

We also have [USING AXIOM TO SEND BURP SUITE REQUESTS TO ALTERNATING PROXIES]( https://jamesonhacking.blogspot.com/2021/04/using-axiom-to-send-burp-suite-requests.html) 
Other whiteup and videos [here](https://github.com/pry0cc/axiom/wiki/Videos-and-Write-Ups) 

However, there is a problem documented here https://github.com/pry0cc/axiom/issues/498, axiom-proxy does not fully work without code changes.
I plan to update axiom-proxy as my next test. Maybe in a week it will be finished. 
Im going to close this issue as a repeat of the first issue  https://github.com/pry0cc/axiom/issues/498 but post in the issue if you have questions.
