### ISSUE TITLE
Another alternative DO

### ISSUE THREAD

**Issue by VinzelOps** [pry0cc/axiom#519]
Is there any guide for axiom installation on GCP or Azure?

**Comment by 0xtavian** [comment]
@VinzelOps For Azure use this fix for now. https://github.com/pry0cc/axiom/issues/435#issuecomment-982938874.
GCP isn’t fully implemented

**Comment by VinzelOps** [comment]
Ok, is there a video or my guide for installation with azure? please help

**Comment by 0xtavian** [comment]
@VinzelOps sorry for the late response, we dont have a video for setup. if you ran into errors during azure setup, please try the latest code in the master repo (pushed a fix for azure) and let me know what errors if any prevent you from completing setup.
I noticed with azure only, axiom-build fails with an error suggesting it was not able to find the image resource axiom (this is some strange azure bug it seems). Just run axiom-build again and it should resolve. 

Join the 0x00sec discord and ask in the axiom channel if you need more direct assistance.
