### ISSUE TITLE
Issue with axiom-init on ParrotSecOS

### ISSUE THREAD

**Issue by BUGBOUNTYchrisg8691** [pry0cc/axiom#52]
So, I've been running this on Ubuntu and it runs great. Today, I tried to install on a Parrot OS VM and have been having some issues, but I'm running into this permission error and I'm trying to find a way around it. It allows me to run the bash one-liner in Tilix emulator but not in Konsole and not on either while in tmux. When I run one-liner in Tilix, it will install the commands in Konsole, but they will not work in Tilix, after restarting Tilix, obviously. The one liner runs through just like in Ubuntu( I did not compare them line by line, but the final output is the same.)   I know this must be a configuration error on my end, and I can see that I don't have permissions to /tmp/packer-xxxx..., but I'm stuck. I'm also have a problem with zsh and tilix where my zsh config is only sourced and in Tilix, but opening up Konsole, displays the default shell for Parrot. I'm assuming the two are linked in some way. Any help would be greatly appreciated.

└──╼ $./axiom-configure 
Hello! Welcome to Axiom configuration :)
To begin, I will ask you a few questions                                                                       
Press enter to continue                                                                                        

Installing deps! Please wait :) 
go: /usr/bin/go /usr/lib/go /usr/share/go /usr/share/man/man1/go.1.gz
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.
What is your DigitalOcean API key? 
Key >>  xxxxx...
Setting up doctl!...
Using token [xxxxx...]

Validating token... OK

Detected SSH public key, would you like me to install this for your axiom setup? y/n 
y
You're running Bash! Installing Axiom to $PATH...
Beginning first packer build...
Failed to initialize build 'digitalocean': error initializing builder 'digitalocean': Unrecognized remote plugin message: Error starting plugin server: listen unix /tmp/packer-plugin428766856: listen: operation not permitted
digitalocean output will be in this color.

==> Builds finished but no artifacts were created.

**Comment by BUGBOUNTYchrisg8691** [comment]
I'm an idiot. I'm sorry. I guess chsh did not work correctly or something. I went into the 'edit current profile' in the settings tab and manually changed the shell command from /bin/bash to /bin/zsh and it fixed my zsh config, so I'm hoping that it fixes this as well. I'm running bash one liner now and will close this as soon as it finishes, but I believe this was my issue. My fault.

**Comment by pry0cc** [comment]
Let me know how it goes! I'm glad you're getting some mileage :) 

Are you enjoying axiom? Do you have any suggestions?

**Comment by BUGBOUNTYchrisg8691** [comment]
I am, very much, and as far as suggestions go, no, the zsh history you have added is a great touch and other things you already have planned just sound brilliant. I am new to all of this, and a tool like this a great for someone like me, but also a lot to wrap your head around. Oh, that was one thing, maybe someone could do a video on the usage of this tool. That would honestly be great. Someone that knows the tool well. The README is decently thorough as is, but a walk through might be extremely helpful for newcomers.

Other than that, thank you for your quick response to this issue. I also did not have doctl installed properly so instead of using snap i just went with a release from Digital Oceans github page. But yeah, it's working perfectly, now. Again, thank you for being so on top of all the issues.
