### ISSUE TITLE
Axiom-Scan w/Assetfinder - Strange Output

### ISSUE THREAD

**Issue by notakodr** [pry0cc/axiom#524]
![Screenshot from 2022-02-11 10-57-37](https://user-images.githubusercontent.com/99501690/153653058-b9c94ebf-7655-457b-9368-dd7420b6e48e.png)

Getting some strange Axiom info in the output text file... 

Any ideas?? 

Big thanks to you and the team for creating such an exciting project.

**Comment by pdelteil** [comment]
It seems you're seeing the colored output in a 'plain text' form.

**Comment by notakodr** [comment]
> ### **[pdelteil](/pdelteil) ** commented [4 minutes ago](#issuecomment-1036616982)

Thank you for reaching out. Super appreciated. 

I am a total noob trying to setup my first automated scan using Axiom.. Would like to have Axiom-Scan do all the scans 

Trying to use assetfinder, subfinder and chaos to enum subs. Then send all the cleaned up data to nuclei etc... 
Perhaps I am looking at this from the wrong view.

Below is my first attempt at coding my own auto recon.  Is there a flag to set to stop colored text output? 

#!/bin/bash

domain=$1

if [[ -z "$domain" ]];

then echo "> Domain Required!"
    exit 1;
else
spinupfleet(){
axiom-fleet -i 10 -r sfo3,nyc1,tor1
axiom-select '\*'
}
spinupfleet

domain_enum(){
mkdir -p $domain/subdomains $domain/intel $domain/intel/nuclei
axiom-scan ~/hyatt -m assetfinder $domain --subs-only | tee $domain/subdomains/assetfinder.txt
sort -u $domain/subdomains/assetfinder.txt -o $domain/subdomains/assetfinder.txt
}
domain_enum

destroy(){
axiom-rm '\*' -f 
}
destroy
fi

**Comment by 0xtavian** [comment]
@notakodr check out the wiki for some videos and write ups. I’d recommend first watching https://www.youtube.com/watch?v=t-FCvQK2Y88  NahamCon 2021 - Introduction to Axiom, then reading about Simple Modules https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules. 
Some tips: avoid using `|` unless required and only use it directly in the module. There is no point piping to tee sort -u, axiom-scan does this already if using `txt` extension in the module (IIRC). Join the discord if you need additional help https://github.com/pry0cc/axiom/wiki

Ty @pdelteil for pointing out the reason for the output coloring.

**Comment by notakodr** [comment]
Awesome, thanks!
