### ISSUE TITLE
Zsh is not detected due to incorrect shell path

### ISSUE THREAD

**Issue by CrystalSage** [pry0cc/axiom#53]
Currently, the user's default shell is detected by checking the $SHELL variable. The paths used to check the shells are hardcoded in [axiom-configure](https://github.com/pry0cc/axiom/blob/master/interact/axiom-configure). For any path that is not included in this file, the default shell is not detected.

e.g On my machine running Arch Linux, I've my Zsh installed through Pacman. The $SHELL variable is set to `/bin/zsh` for me. As a result, axiom-configure does not detect Zsh as my default shell, since the path is not hardcoded on [line 180 of axiom-configure](https://github.com/pry0cc/axiom/blob/4a13a6858447707d56cf465dd4142d1e8ab1ad31/interact/axiom-configure#L180)

A better method for checking the default shell is to consult the user's `/etc/passwd` entry and read the default shell from there. The following bash two liner quickly solves the issue.
```bash
user_entry=$(getent passwd | grep "^$USER")  # Grabs the user's passwd entry
user_shell=${user_entry##*/}  # Grabs the text after last slash of the passwd file (shell name)
```

The bash script outputs $user_shell as "zsh" on my Arch machine and "bash" on my Ubuntu WSL2, where bash is default.

**Comment by pry0cc** [comment]
Nice. Can you add this as a PR?

**Comment by CrystalSage** [comment]
Created PR #82  for this. Closing the issue.
