### ISSUE TITLE
Transfer axiom to another machine without having to reinstall?

### ISSUE THREAD

**Issue by gprime31** [pry0cc/axiom#530]
I want to transfer from my vps to local machine.
Is this possible?

**Comment by 0xtavian** [comment]
@gprime31 The axiom controller needs to be installed on the machine if you want to run axiom-scan commands ( for example ). If axiom is already installed on both machines simply transfer pub/priv key ( axiom_rsa by default) and the axiom profile ( $HOME/.axiom/accounts/youraccount.json ), then run `axiom-account your-account`.  

If you are only looking to transfer scan data from the vps to local, use scp.

**Comment by gprime31** [comment]
Ok,
So then is there a way to skip the install and backup part and just use the backup that's already there?
(Like when it creates the tmp droplet and backs it up)

**Comment by 0xtavian** [comment]
You can’t skip installing the axiom controller if you want to use axiom. You can however skip initiating the first Packer build upon install. You’d have to transfer your ssh key from the vps to local machine if you want to use an image already build. 

`axiom-configure --unattended`
  
 If you want to skip running `axiom-account-setup`
```
axiom-configure --shell bash --unattended --config { "do_key": "[redacted]", "region": "nyc1", "provider": "do", "default_size": "s-1vcpu-1gb", "appliance_name": "", "appliance_key": "", "appliance_url": "", "email": "", "op": "[redacted]", "imageid": "axiom-default-myimageid", "provisioner": "default", "sshkey": "id_rsa" }
```
https://github.com/pry0cc/axiom/wiki/Filesystem-Utilities#axiom-configure

**Comment by gprime31** [comment]
Awesome.
Thanks.
