### ISSUE TITLE
[Feature] Ability to load nuclei templates from a local directory

### ISSUE THREAD

**Issue by iambouali** [pry0cc/axiom#531]
Hello,

I think it would be great if axiom allows the ability to load nuclei templates from a local directory on the root machine. This would help speed up some hacker's workflow when they create custom templates and want to launch them against a list of targets.

Best

**Comment by iambouali** [comment]
Duplicate

**Comment by 0xtavian** [comment]
So you can upload a single template currently with -wL but not a folder of templates. For now we suggesting just using axiom-scp before the axiom-scan command. There are tentative  plans to support uploading a folder of template, but in the meantime I suggest using axiom-scp.

**Comment by pdelteil** [comment]
> Hello,
> 
> I think it would be great if axiom allows the ability to load nuclei templates from a local directory on the root machine. This would help speed up some hacker's workflow when they create custom templates and want to launch them against a list of targets.
> 
> Best

I also think it would be helpful.
