### ISSUE TITLE
axiom-Fleet 15 Gives me Only 3 Instance even when i have enough droplet limit

### ISSUE THREAD

**Issue by daai1** [pry0cc/axiom#545]
Hi,
My droplet limit is more than 20 and If I give axiom-fleet bounty -i=15  it creates only 3 droplets. So if I want 15 instances I had to run the command 5 times to get 15 instances I don't know why I'm not able to create 15 instances in a single shot even when I have a droplet limit of more than 20.

@pry0cc  @0xtavian Can you Please Check this issue?

axiom-fleet bounty -i=15                                                    
Initializing new fleet 'bounty' with 3 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ bounty01 bounty02 bounty03  ]
Initialized instance 'bounty01' at '164.92.113.220'!
Initialized instance 'bounty02' at '164.92.121.81'!                                                                                                                                                                                        
Initialized instance 'bounty03' at '164.92.105.19'!
Selected: [ bounty01 bounty02 bounty03 ]ion...                                                                                                                                                                                             
Fleet started succesfully!
To delete your fleet, just run 'axiom-rm "bounty*" -f'

**Comment by pry0cc** [comment]
Drop the =

**Comment by daai1** [comment]
Working now. Thank you @pry0cc
