### ISSUE TITLE
Unable to create new instance

### ISSUE THREAD

**Issue by daai1** [pry0cc/axiom#546]
Hi, 

I'm getting this error while creating instance

@pry0cc @0xtavian Can you Please Check this issue?

➜  .axiom git:(master) ✗ axiom-fleet new -i 15
Initializing new fleet 'new' with 15 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ new16 new17 new18 new19 new20 new21 new22 new23 new24 new25 new26 new27 new28 new29 new30  ]
Initialized instance 'new16' at ''!ization...
Initialized instance 'new17' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new18' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new19' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new20' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new21' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new23' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new22' at ''!                                                                                                                                                                                                      
Initialized instance 'new24' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new25' at ''!                                                                                                                                                                                                      
Initialized instance 'new26' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new27' at ''!                                                                                                                                                                                                      
Initialized instance 'new28' at ''!ization...                                                                                                                                                                                            
Initialized instance 'new29' at ''!                                                                                                                                                                                                      
Initialized instance 'new30' at ''!
>> T-Minus 108 to fleet new initialization...

**Comment by daai1** [comment]
Looks like it's already in PATH also created 20 instance in the morning and i not faced this issue. After i destroyed some instances and tried creating some more instances in the evening and i'm getting this error. In between i added some regions in axiom.json file.

➜  ~ pwd
/root
➜  ~ echo $PATH
/root/go/bin:/usr/local/go/bin:/root/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.local/bin:/root/.axiom/interact

**Comment by daai1** [comment]
I tried the same again now it creates only 2 instance. @pry0cc 

➜  ~ axiom-fleet bounty -i 15 --regions sfo3,nyc1,nyc2,nyc3,ams2,ams3,sfo1,sfo2,sgp1,lon1,fra1,tor1,blr1
Initializing new fleet 'bounty' with 15 instances...
Cycling through following regions:sfo3,nyc1,nyc2,nyc3,ams2,ams3,sfo1,sfo2,sgp1,lon1,fra1,tor1,blr1...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ bounty16 bounty17 bounty18 bounty19 bounty20 bounty21 bounty22 bounty23 bounty24 bounty25 bounty26 bounty27 bounty28 bounty29 bounty30  ]
Initialized instance 'bounty17' at ''!ization...
Initialized instance 'bounty18' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty19' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty20' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty21' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty23' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty22' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty24' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty25' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty26' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty27' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty28' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty30' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty16' at '164.92.97.51'!                                                                                                                                                                                          
Initialized instance 'bounty29' at '164.92.65.125'!

**Comment by daai1** [comment]
@pry0cc @0xtavian I tried again after 3 hours and I'm facing the same issue.

➜  ~ axiom-fleet bounty -i 15 --regions sfo3,nyc1,nyc2,nyc3,ams2,ams3,sfo1,sfo2,sgp1,lon1,fra1,tor1,blr1
Initializing new fleet 'bounty' with 15 instances...
Cycling through following regions:sfo3,nyc1,nyc2,nyc3,ams2,ams3,sfo1,sfo2,sgp1,lon1,fra1,tor1,blr1...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ bounty01 bounty02 bounty03 bounty04 bounty05 bounty06 bounty07 bounty08 bounty09 bounty10 bounty11 bounty12 bounty13 bounty14 bounty15  ]
Initialized instance 'bounty02' at ''!ization...
Initialized instance 'bounty03' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty04' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty05' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty06' at ''!
Initialized instance 'bounty07' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty08' at ''!
Initialized instance 'bounty09' at ''!
Initialized instance 'bounty10' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty11' at ''!
Initialized instance 'bounty12' at ''!
Initialized instance 'bounty13' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty15' at ''!
Initialized instance 'bounty01' at '164.92.121.212'!                                                                                                                                                                                        
Initialized instance 'bounty14' at '143.244.184.48'!                                                                                                                                                                                        
Selected: [ bounty01 bounty14 ]itialization...                                                                                                                                                                                              
Fleet started succesfully!
To delete your fleet, just run 'axiom-rm "bounty*" -f'

**Comment by 0xtavian** [comment]
@daai1 

Did you transfer your image to the new region before trying to provision in that region? With DO you need to transfer the image, some providers auto transfer the image, but DO does not.

First get the imageid from `axiom-images ls` , then run `for i in $(axiom-region ls | grep -v false | grep -v Slug | cut -d ' ' -f 1); do doctl compute image-action transfer [imageid-here] --region $i  --wait  ; done`

and it will transfer your image to every region. then you can use -r/--regions.  

Also, you have unavailable regions in your list.

I spun up 15 instances in all available regions without any problem. 

To see available regions run `axiom-region ls`. The following regions are currently unavailable for me. 
sfo1,ams2,ny2,sfo2

**Comment by daai1** [comment]
@0xtavian followed the steps and the issue is resolved now. Thanks for the one-liner. Your support is great and awesome @pry0cc @0xtavian Thanks.

**Comment by pry0cc** [comment]
Thanks 🙏 @0xtavian

**Comment by daai1** [comment]
@pry0cc @0xtavian  Unable to create instance  getting this error, please help me.

initializing new fleet 'bounty' with 25 instances...
Cycling through following regions:sfo3,nyc3,ams3,sgp1,lon1,fra1,tor1,blr1...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ bounty01 bounty02 bounty03 bounty04 bounty05 bounty06 bounty07 bounty08 bounty09 bounty10 bounty11 bounty12 bounty13 bounty14 bounty15 bounty16 bounty17 bounty18 bounty19 bounty20 bounty21 bounty22 bounty23 bounty24 bounty25  ]
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
jq: error (at <stdin>:3829): Cannot iterate over null (null)
Initialized instance 'bounty05' at ''!ization...
Initialized instance 'bounty23' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty17' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty25' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty03' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty22' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty11' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty24' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty16' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty06' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty04' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty10' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty18' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty13' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty12' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty07' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty01' at ''!ization...                                                                                                                                                                                            
Initialized instance 'bounty09' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty02' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty08' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty20' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty14' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty19' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty21' at ''!                                                                                                                                                                                                      
Initialized instance 'bounty15' at ''!                                                                                                                                                                                                      
Selected: [ bounty01 bounty02 bounty03 bounty04 bounty05 bounty06 bounty07 bounty08 bounty09 bounty10 bounty11 bounty12 bounty13 bounty14 bounty15 bounty16 bounty17 bounty18 bounty19 bounty20 bounty21 bounty22 bounty23 bounty24 bounty25 ]                                                                                                                                                                                                                                          
Fleet started succesfully!
To delete your fleet, just run 'axiom-rm "bounty*" -f'
