### ISSUE TITLE
Go get doesn't appear to be a thing anymore

### ISSUE THREAD

**Issue by stop-a** [pry0cc/axiom#561]
Running axiom-scan and got an error ```[redacted]/.axiom/interact/axiom-scan: line 1006: anew: command not found```

Looked at the script and anew command is called. Worked backwards and on line 1036 I think I see the issue, ```go get -u github.com/tomnomnom/anew >> /dev/null 2>&1```. The whole block:
```
###########################################################################################################
1033 #  Install anew if not already installed
1034 #
1035 if ! [ -x "$(command -v anew)" ]; then
1036 go get -u github.com/tomnomnom/anew >> /dev/null 2>&1
1037 fi
1038 
1039 ###########################################################################################################
```

If I run that at the command line, I get an error basically saying "we don't do 'go get' anymore. Use 'go install example.com/cmd@latest' instead".

After running ```go install github.com/tomnomnom/anew@latest``` I was able to make the error go away.

Looks like there's a couple of other opportunities for this kind of error, as well:
``` bash
$ grep "go get" axiom-*
axiom-configure:go get -u github.com/tomnomnom/anew >> /dev/null 2>&1
axiom-orgalorg: go get github.com/reconquest/orgalorg
axiom-scan:GO111MODULE=on go get -v github.com/hahwul/gee >/dev/null 2>&1
axiom-scan:go get -u github.com/tomnomnom/anew >> /dev/null 2>&1
```

**Comment by 0xtavian** [comment]
thanks, we've updated configure and scan.
