### ISSUE TITLE
Axiom-scan interlace error

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#562]
I was running axiom-scan using the module subfinder in the following way

``axiom-scan verizon_domains.txt -m subfinder -o subfinder_verizon.txt``

And got the following error:

![Screenshot from 2022-07-03 17-52-54](https://user-images.githubusercontent.com/20244863/177061281-63bb1427-b316-44d8-9779-b077b015fca5.png)

I fixed the issue adding ``mkdir -p $/tmp/status``  (I will create a PR)

**Comment by pdelteil** [comment]
Checking the error, I did notice the folder $home/.axiom/tmp/..../status wasn't created.  

Not sure yet about the root cause, but I will keep testing.

**Comment by 0xtavian** [comment]
the file does get created. it might be a race conduction during axiom-scan that shows that error, but u can safely ignore.
