### ISSUE TITLE
Flag -oD doesn't work

### ISSUE THREAD

**Issue by ZigzagSecurity** [pry0cc/axiom#565]
Hi, I noticed that the flag -oD causes some issues with the axiom-scan.

![Screenshot_20220706_151204](https://user-images.githubusercontent.com/40743997/177559999-71634268-c02a-4ccb-8577-3fd3d0c69d53.png)

As you seen in the screenshot, when I use the flag `-oD some-name ` the command is empty when sent to the different instances. 
it works fine if I removed this specific flag though. I am doing something wrong ? 

I installed  axiom yesterday using the auto installer so it should be up to date. 
You can see the custom module I am using on the top of the screenshot. 

Thank you for reading ! :)

**Comment by 0xtavian** [comment]
@ZigzagSecurity can you post the json module? You might just need to change the ext mentioned in the module to`"etc":"dir"` or `"etc":""` ( both are ways to specify merging as a folder, look at other modules for an example).

**Comment by 0xtavian** [comment]
just realized you already posted the json module -_-  ty. I see the issue (I think), change
`-o output` to `-o output/output` and rerun. @ZigzagSecurity

**Comment by ZigzagSecurity** [comment]
Hi ! Thank you for coming so quickly ! I managed to get it to work following your advice but I also had to change the extension to "dir". I still the issue with the extension left empty. 

Thank you and have a good day :)

**Comment by 0xtavian** [comment]
Noted, thanks!
