### ISSUE TITLE
add more timeouts when creating fleets

### ISSUE THREAD

**Issue by marcelo321** [pry0cc/axiom#567]
When creating fleets in linode with a number above 10 I tend to get code 429 "too many requests" and I have to run the command again with the amount of linodes I actually want.

Would it be possible to add some extra timeouts in the creation of fleets?

```
┌errors─┬───────────────────┐
│ field │ reason            │
├───────┼───────────────────┤
│       │ Too many requests │
└───────┴───────────────────┘
```

**Comment by 0xtavian** [comment]
@marcelo321 can you update to the latest code and try again?

**Comment by marcelo321** [comment]
Hi @0xtavian, if I want to update it to the last version without building again, how do I do it? so I can try it

**Comment by 0xtavian** [comment]
Hey @marcelo321 thanks for testing. did all the instance spin up regardless of errors?

**Comment by marcelo321** [comment]
@0xtavian,

definitely improved but I think 2-3 instances didn't set up, so out of 12 I think 9 were up correctly.

edit: just run it again creating 12 instances and got 0 errors, all instances were ok <3

**Comment by pdelteil** [comment]
I also had this issue, can confirm it works great now.
