### ISSUE TITLE
AWS build error

### ISSUE THREAD

**Issue by lonelyman666** [pry0cc/axiom#568]
im getting this error

![Screenshot from 2022-07-09 09-51-19](https://user-images.githubusercontent.com/96546053/178088910-43aeb2cd-69c3-4d13-a200-151938ca74d1.png)

how can i fix this

**Comment by 0xtavian** [comment]
@lonelyman666 You posted creds, you should invalidate. You can get past this error by bumping the version of packer. But I fear there is another error after. Might need to manually authenticate to the cli. Not sure. I apologize I haven’t really had the time to look at.

**Comment by lonelyman666** [comment]
> @lonelyman666 firstly, like 0xtavian say: Download latest packer with this command: `wget -q -O packer.zip https://releases.hashicorp.com/packer/1.8.1/packer_1.8.1_linux_amd64.zip && unzip packer.zip && sudo mv packer /usr/bin/ && rm packer.zip ` After download, If you try to run `axiom-configure` again, It stuck because of reinstall the packer so don't configure anything. Anyways, It should be solve your problem. If It doesn't comment again.

hi @samet-g I have followed what you said but i got the same error. Is this from IAM that is not set properly?



> Incase you get error like this then create a keypair named axiom in the region which you selected during axiom setup process. ![image](https://user-images.githubusercontent.com/43294620/179185423-87ae57d7-6a61-40d0-9f73-9d94ff2c32ee.png)

@b1bek how can you install axiom for aws. did you get an error like me. after running the first time? I've tried with DO it works smoothly. but not with this aws

**Comment by b1bek** [comment]
@lonelyman666 After upgrading packer and creating axiom keypair i was able to use axiom in AWS. Try changing shell to zsh or oh-my-zsh once

**Comment by 0xtavian** [comment]
This has been since fixed. Thanks all. Closing but lmk if you still see this issue @b1bek @lonelyman666 @samet-g
