### ISSUE TITLE
Mac OSX - expr: division by zero

### ISSUE THREAD

**Issue by big-ppp** [pry0cc/axiom#575]
Running Mac OSX - Monterey 12.4 

Trying to run naabu seems it cant split the file it runs in a endless loop with the below error message

"expr: division by zero"

![image](https://user-images.githubusercontent.com/17185724/181312923-ec046026-2f3f-47d0-b862-5c9bba5a4c47.png)

**Comment by 0xtavian** [comment]
@big-ppp you don’t have any instances selected ( `instances: 0`). You should have gotten an error saying “error with number of instances” (lmk if that didn’t happen). To list instances run `axiom-ls` to select them run `axiom-select instance-prefix*`, you might need to escape the asterix.
