### ISSUE TITLE
AWS build error

### ISSUE THREAD

**Issue by Huntinex** [pry0cc/axiom#577]
Hi,
I ran `axiom-build` and it succeeded, but when I run `axiom-exec ls` it gives me an error :
![image](https://user-images.githubusercontent.com/83470008/183361147-18d03e1c-4d69-4515-8e9c-28d7bd4bd24f.png)

**Comment by pdelteil** [comment]
Hi there,

That indicates that the file selected.conf is not yet created. The command `axiom-select` should fix it. 

Also, is not recommended to run commands logged in as root, the use of sudo command is the way to go.
