### ISSUE TITLE
Additional Tool

### ISSUE THREAD

**Issue by random-robbie** [pry0cc/axiom#578]
Hey Dude,

Is it possible to add cero `go get -u github.com/glebarez/cero` to the tools list.

it just grabs the SSL cert my idea is to fire up a fleet and scan AWS range with this and put it all in one big text file.

**Comment by 0xtavian** [comment]
Hey bud,

we already include [cero](https://github.com/pry0cc/axiom/blob/master/modules/cero.json) as a [docker based module](https://github.com/0xtavian/minimal-pentesting-dockerfiles/blob/master/cero/Dockerfile). All you have to do is build with the default provisioner and you should be all set. To see a list of modules you can run `axiom-scan —list`. Lmk if it doesn’t work for whatever reason and we’ll fix it. @random-robbie

**Comment by random-robbie** [comment]
sorry mate just seen it on the build now nice one! closing ticket.
