### ISSUE TITLE
Axiom doesn't work on cron 

### ISSUE THREAD

**Issue by bart3nder** [pry0cc/axiom#590]
Hello folks.
Amazing project, thanks for your efforts,
When i'm trying to use axiom with its modules and utilities in my script which i set in cron for every e.g 1 hour, i face many error that indicates axiom could not run under cronjobs:
```
bash: /tmp/exec/axiom-exec+1660857984/command: No such file or directory
```
I've tested many solutions as setting PATH in script and providing full path a and ... but it doesn't work. is there any solutions to use it under cron? anything i can do or you guys can implement?
Thanks again.

**Comment by jarombrown** [comment]
Did you find a solution for this issue?

**Comment by bart3nder** [comment]
Hello, Sorry for late response.
No I'm afraid I didn't find any solution to solve this issue, But I would be glad to hear yours (If there is any).

**Comment by jarombrown** [comment]
Hey, for me the issue was that some of the references to axiom commands weren’t prepended with the full path, specifically in the axiom-scan file.
