### ISSUE TITLE
Axiom freezes at "Provisioner" option.

### ISSUE THREAD

**Issue by RodricBr** [pry0cc/axiom#605]
#### Image:
![image](https://user-images.githubusercontent.com/72948934/187995835-75fc237c-59df-4186-afc2-b39864a43e51.png)

I can't press enter, or type anything, it just freezes and all I could do was cancel the process (CTRL+C). Tested on a Debian 11 x64 and on a Ubuntu 22.04 x64 machine.

**Comment by 0xtavian** [comment]
@RodricBr that’s odd. Question if you press control+c, then reload your shell ( via running `bash` or running `zsh` if you installed omz or zsh), and finally try running axiom-build again, does it work? You could also select the provisioner via the command line by running `axiom-build default` for example. What’s your shell? bash, zsh or oh-my-zsh?

**Comment by 0xtavian** [comment]
Also, Ubuntu 22.04 unfortunately isn’t supported atm. If you can use Ubuntu 20.04 that would be preferable. The only issue with Ubuntu 22.04 is that by default the version of python is 3.10, which doesn’t play nicely with Interlace. There are plenty of workarounds to the interlace issue mentioned in their repo. Just keep in mind you’ll have to that extra step once to get exec/scan etc working if you stick with Ubuntu 22.04 https://github.com/codingo/Interlace/issues/167

**Comment by RodricBr** [comment]
> What’s your shell? bash, zsh or oh-my-zsh? <br>

My current shell is bash.

<br>

> Also, Ubuntu 22.04 unfortunately isn’t supported atm. If you can use Ubuntu 20.04 that would be preferable. <br>

Yeah... thanks, that seems to resolve the problem, I used Ubuntu 20.04 and it worked as expected!

---

Also, this is what the program prints out after one hour of waiting, if this can be useful to you. (On Ubuntu 22.04)
![image](https://user-images.githubusercontent.com/72948934/188017233-65e3ea83-7e97-4741-8a3c-0ecb79539b40.png)

**Comment by 0xtavian** [comment]
@RodricBr Thanks, yeah there is definitely some bug here. I am able to reproduce. The workaround is unfortunately when axiom-configure calls axiom-build, you'll have to control+c and then run axiom-build again. I'll look into it over the weekend. Thanks for bringing this up!

**Comment by jackson-jackson** [comment]
I've got the same issue.

**Comment by 0xtavian** [comment]
@jackson-jackson @RodricBr can you please update to the latest code and try again? It seems I was able to identify the issue. Run `axiom-update` to update to the latest code. If you've made any local changes you might have run `cd $HOME/.axiom ; git status` and restore any files it complains about, then run `axiom-update` again. Thank you both!

**Comment by jackson-jackson** [comment]
@oxtavian, that worked. Thanks for the insanely fast fix :)

**Comment by RodricBr** [comment]
@0xtavian 
Yeah, it seems like the bug was fixed, thanks for the help, and keep up the good work!
