### ISSUE TITLE
/home/op/.axiom/interact/axiom-scan: line 693: generate_sshconfig: command not found cat: /home/op/.axiom/selected.conf: No such file or directory cp: cannot stat '/home/op/.axiom/.sshconfig': No such file or directory error with number of instances, exiting

### ISSUE THREAD

**Issue by Sarfu47** [pry0cc/axiom#607]
After create axiom instance and then now run axiom tool like now I run axiom-scan and this showing 

/home/op/.axiom/interact/axiom-scan: line 8: /home/op/.axiom/interact/includes/functions.sh: No such file or directory
              _
  ____ __  __(_)___  ____ ___        ______________ _____
 / __ `/ |/_/ / __ \/ __ `__ \______/ ___/ ___/ __ `/ __ \
/ /_/ />  </ / /_/ / / / / / /_____(__  ) /__/ /_/ / / / /
\__,_/_/|_/_/\____/_/ /_/ /_/     /____/\___/\__,_/_/ /_/

                                    @pry0cc
                                 & @0xtavian

/home/op/.axiom/interact/axiom-scan: line 693: generate_sshconfig: command not found
cat: /home/op/.axiom/selected.conf: No such file or directory
cp: cannot stat '/home/op/.axiom/.sshconfig': No such file or directory
error with number of instances, exiting... 
Anyone now about this issue, how to fix this issue

**Comment by 0xtavian** [comment]
@Sarfu47 can you try again with the latest code? Run axiom-update prior. Also make sure the instances are selected with axiom-select
