### ISSUE TITLE
Python 3.10 Interlace

### ISSUE THREAD

**Issue by Techbrunch** [pry0cc/axiom#608]
Interlace doesn't work with python 3.10 cf https://github.com/codingo/Interlace/issues/167

@0xtavian you might want to consider using something other than interlace in the future, @six2dez mentionned rush in https://github.com/six2dez/reconftw/issues/561

On osx you probably want to edit the following files:

```python
/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py
/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/abc.py
```

**Comment by 0xtavian** [comment]
This should be fixed with the latest Interlace @Techbrunch ty for reporting!
