### ISSUE TITLE
axiom-scan regions

### ISSUE THREAD

**Issue by cswiers** [pry0cc/axiom#611]
We can specify regions when using axiom-fleet, we can also directly start fleets using axiom-scan. We cannot however specify regions when using axiom-scan directly if I am not mistaking. Is it possible to add this?

**Comment by 0xtavian** [comment]
@cswiers thanks for opening this issue. Currently `axiom-scan —fleet` doesn’t recognize the `—regions` argument the way `axiom-fleet` does. However with a few relatively simple code changes, it certainly can. When I get some time, I’ll work on extending the `—regions` argument to `axiom-scan`. Good idea :) thanks again!

**Comment by cswiers** [comment]
Yes, it works like a charm! Thank you
