### ISSUE TITLE
Axiom Not recognizing Any Module

### ISSUE THREAD

**Issue by Sicks3c** [pry0cc/axiom#619]
## Summary

Hello guys

I have setup axiom from scratch using all the steps and adding the proper keys and profiles
however, whenever I use any `module`  it shows this

<img width="1427" alt="Screen Shot 2022-09-25 at 21 19 43" src="https://user-images.githubusercontent.com/32225186/192163521-b5e2c1dd-eeba-47c5-a84c-3e4483fa1694.png">

I hope you can help

Cheers

**Comment by Sicks3c** [comment]
Fixed by adding 
`/home/op/.local/bin` to PATH

Cheers

**Comment by pdelteil** [comment]
Please show us the command you're using.

**Comment by Sicks3c** [comment]
I was using 
`axiom-scan file -m subfinder -o output.txt`
but I kinda fixed it, I had to add `/home/op/.local/bin` to PATH
