### ISSUE TITLE
no such file or directory: packer.json

### ISSUE THREAD

**Issue by BUGBOUNTYchrisg8691** [pry0cc/axiom#62]
So, I'm attempting to run the bash one liner on a new install of Linux and it looks like the packer json file is no longer in the repo. I noticed this earlier when I ran axiom-update on another machine and then went to run axiom-build and got this same issue. I luckily had a pull from a few weeks back and just copied the packer.json into .axiom directory. I'm I doing something wrong here or is this a mistake?

**Comment by michael1026** [comment]
I can confirm the same issue here.

**Comment by streaak** [comment]
I can confirm the same issue on MacOS

**Comment by Jabo-SCO** [comment]
I had this issue too. https://github.com/pry0cc/axiom/pull/64 fixes it.

**Comment by BUGBOUNTYchrisg8691** [comment]
Thanks, everyone, for the help. It seems to be fixed, now, anyway.
