### ISSUE TITLE
ERROR: API Version 2022-03-01 does not have operation group 'images'

### ISSUE THREAD

**Issue by Monst3rSec** [pry0cc/axiom#620]
Hi Team,

I have installed the axiom using easy-install method and have setup my Azure account with axiom( chosen default options only). 

However, I encountered the below problem when attempting to initialize an **axiom-init.**

Please assist me in solving this problem.

thanks in advance. 

**Reference:**
![image](https://user-images.githubusercontent.com/60444051/192498422-0771d57d-5abf-4225-a5a3-60e7ba687ddd.png)

**Comment by 0xtavian** [comment]
This has finally been fixed thanks to @six2dez :)
