### ISSUE TITLE
Feature Request: Automatically upload configs with API keys

### ISSUE THREAD

**Issue by thapr0digy** [pry0cc/axiom#622]
From what I can tell, there is no automation built in place to copy the configuration for a tool such as subfinder or amass from the system into each instance/fleet when running axiom-scan. It would be great to have an option for copying over a user specified configuration location with all of the secrets/API keys into the instance/fleet when running axiom-scan with the module.

My current workflow is spin up the instance/fleet, run axiom-scp to copy to all of the instances, then run axiom-scan.

**Comment by 0xtavian** [comment]
@thapr0digy this is already supported, but maybe it can be more intuitive (check out the axiom-scan help menu for a description). 

Use the axiom-scan `—local-config` argument and pass the path to a local config. AND In the module you have to add the `_config_` string somewhere so axiom knows where to position the config file. 

During runtime, axiom will upload the local config to each of the scanners unique working directory and will replace the variable `_config_` in the module with the user-provided config. It works similar to the`_wordlist_` variable replace. 

If you need an example, the module command might look like:
`nuclei -stats -rc _config_ -o output`
cli command:
`axiom-scan targets-list.txt -m nuclei —local-config /home/localuser/custom-nuclei-config.yaml`

In case you were wondering, dynamically splitting a folder of config files and uploading a unique config file to every instance is not supported yet but is on the roadmap.
