### ISSUE TITLE
cf-check module appears broken

### ISSUE THREAD

**Issue by nicoandmee** [pry0cc/axiom#624]
When attempting to run `axiom-scan` with `cf-check` as module, I observed the following output:
```shell
docker: Error response from daemon: pull access denied for axiom/cf-check, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

Upon checking I guess https://github.com/Cgboal/exclude-cdn is a great alternative, but should we mark this module as deprecated perhaps to avoid confusion? I will be happy to submit a PR.

**Comment by 0xtavian** [comment]
@nicoandmee good catch. Yea I removed it from the default provisioner. To avoid confusion,  
I’ll merge a PR removing the module.

**Comment by nicoandmee** [comment]
> @nicoandmee good catch. Yea I removed it from the default provisioner. To avoid confusion, I’ll merge a PR removing the module.

💯 https://github.com/pry0cc/axiom/pull/625
