### ISSUE TITLE
wordlist distribution

### ISSUE THREAD

**Issue by K4r1it0** [pry0cc/axiom#630]
instead of distributing the targets on different instances to be run on puredns i want to distribute the wordlist to be splitted with and run with the same target how can i do this?

**Comment by 0xtavian** [comment]
@dhauenstein glad you figured it out. ICYMI, we have a wiki page going over horizontal versus vertical scanning https://github.com/pry0cc/axiom/wiki/Horizontal-vs-Vertical-Scaling
