### ISSUE TITLE
AWS :: Axiom Fleet "Init” Fails —Single Region

### ISSUE THREAD

**Issue by Hax0rG1rl** [pry0cc/axiom#632]
Hi, 

Trying to spawn several instances in a single AWS region, nothing fancy, I get this error: 

```An error occurred (InvalidKeyPair.NotFound) when calling the RunInstances operation: The key pair 'axiom' does not exist```

This is a fresh install, axiom version is from Oct 15, 2022. 

Any ideas about how this can be resolved?

Thanks!

**Comment by mrtnrdl** [comment]
Same issue here - building the image right before works fine though.

**Comment by mrtnrdl** [comment]
I'm pretty sure the root cause of the error is the following line in `providers/aws-functions.zsh`: 

```
aws ec2 run-instances --image-id "$image_id" --count 1 --instance-type --region "$region" "$size" --key-name axiom --security-groups axiom --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$name}]" 2>&1 >> /dev/null
```

**Comment by 0xtavian** [comment]
This has been fixed. Lmk if you run into any issues.

**Comment by mrtnrdl** [comment]
Works like a charm. Thanks mate <3
