### ISSUE TITLE
Not able to install on Azure - Ubuntu VM

### ISSUE THREAD

**Issue by satishshekher99** [pry0cc/axiom#643]
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.

No browser opens.
Also where is the code that I need to enter?

![Screenshot 2022-11-09 183312](https://user-images.githubusercontent.com/117471520/200837540-2bbfb015-c7ca-4b63-a674-caaf9567df72.png)

**Comment by pdelteil** [comment]
You could try loading the url (https://login....) using firefox (manually or clicking the link).  Once you open the link you'll get the code.

**Comment by 0xtavian** [comment]
Pretty sure azure is broken atm :/ @satishshekher99

**Comment by six2dez** [comment]
Hi! Any update on axiom's Azure setup/usage? :)

**Comment by 0xtavian** [comment]
Azure is now fixed thanks to @six2dez

**Comment by molitona** [comment]
@six2dez @0xtavian have the same problem. how to fix?

**Comment by molitona** [comment]
it's ubuntu 20.04 LTS vps

**Comment by 0xtavian** [comment]
@molitona you are on the latest code? I’ll test later tonight. Ty for bringing this up.

**Comment by molitona** [comment]
yep. last code.
Apr 4, 2023, 17:07 by ***@***.***:

**Comment by molitona** [comment]
@0xtavian you tried ?

**Comment by 0xtavian** [comment]
@molitona OK i see the issue. Oddly we are always expecting azure to be installed on a machine with a web browser.


Try changing this line
https://github.com/pry0cc/axiom/blob/master/interact/account-helpers/azure.sh#L89
from 
```
default_email=$(az login | jq -r  '.[].user.name')

```

to 
```
default_email=$(az login --use-device-code | jq -r  '.[].user.name')
```
I'll try to add this patch later tonight after a few more tests

**Comment by molitona** [comment]
@0xtavian you know how max of virtual machines can be spawn with azure trial ?
