### ISSUE TITLE
AWS errors when "security group 'axiom' already exists for VPC"

### ISSUE THREAD

**Issue by quantumburnz** [pry0cc/axiom#644]
Setting up Axiom for a 2nd time (previously used it) and now getting errors during setup. Would be ideal if this were handled gracefully.

```
An error occurred (InvalidGroup.Duplicate) when calling the CreateSecurityGroup operation: The security group 'axiom' already exists for VPC 'vpc-HEX_ID_HERE'

An error occurred (InvalidGroupId.Malformed) when calling the AuthorizeSecurityGroupIngress operation: The security-group ID '' is malformed
```
![image](https://user-images.githubusercontent.com/26365765/201996654-6b2f0073-9575-4607-a401-9010573f35aa.png)

**Comment by 0xtavian** [comment]
@quantumburnz sorry for the delay this open PR addresses this issue https://github.com/pry0cc/axiom/pull/635#issue-1417535951
We are still working thru some other bugs with AWS, such as round Robbin region distribution and managing multiple images (axiom-images functionality). 
I hope to do some more work on axiom over the weekend.

**Comment by 0xtavian** [comment]
Thanks this should be fix. Please let me know if you continue to see the issue.
