### ISSUE TITLE
--rm-logs argument isn't compatible with specific --fleet argument

### ISSUE THREAD

**Issue by swdbo** [pry0cc/axiom#645]
Hello !

It seems the `--rm-logs` command triggers the `delete_logs()` function that runs only on the instances defined in `selected.conf`. 
Ref : https://github.com/pry0cc/axiom/blob/f369d255977498b48c06207265d4263289b565a0/interact/axiom-scan#L182

Example of the command I'm using :
```
axiom-scan roots.txt -m subfinder -o subs.txt --fleet yourfleetname
```

Excepted behaviour :
The delete_logs() should check if a --fleet has been passed, if none, it can use the selected.conf fleet.

Quick fix I'm using right now :
```
axiom-exec 'rm -rf ~/scan/*/input' --fleet yourfleetname*
```

**Comment by 0xtavian** [comment]
Good catch @swdbo ive been meaning to rewrite delete_logs() to use interlace instead of axiom-exec. I’ll try to do this over the weekend.

**Comment by 0xtavian** [comment]
@swdbo fixed! Sorry for the delay. LMK if it doesnt work as expected for you for whatever reason. You'll have to run `axiom-update` (which is just a `cd ~/.axiom && git pull`) to get the latest code.
