### ISSUE TITLE
Tool add request: Katana from ProjectDiscovery

### ISSUE THREAD

**Issue by pierinogiorgio** [pry0cc/axiom#646]
Hi there, I'd like to ask if it's possible to add Katana (crawler tool) by Project Discovery: https://github.com/projectdiscovery/katana

As all tools made by them, Katana is great.

**Comment by 0xtavian** [comment]
@pierinogiorgio sorry for the delay. its been added https://github.com/pry0cc/axiom/commit/99542a36260e0ba4ff8bf298aa4af6f61a79ea30
