### ISSUE TITLE
axiom shuts down everytime even when i request to increase tpo 18GB

### ISSUE THREAD

**Issue by catchmeifyoucaan** [pry0cc/axiom#647]
i'm experiencing shutdowns no matter what size  

 linode: go: downloading github.com/gorilla/mux v1.8.0
    linode: go: downloading github.com/trufflesecurity/overseer v1.1.7-custom5
    linode: go: downloading github.com/sirupsen/logrus v1.9.0
    linode: go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
    linode: go: downloading github.com/google/pprof v0.0.0-20211214055906-6f57359322fd
    linode: go: downloading golang.org/x/sys v0.1.0
    linode: go: downloading cloud.google.com/go/secretmanager v1.9.0
    linode: go: downloading github.com/getsentry/sentry-go v0.15.0
    linode: go: downloading github.com/hashicorp/go-retryablehttp v0.7.1
    linode: go: downloading github.com/joho/godotenv v1.4.0
    linode: go: downloading github.com/pkg/errors v0.9.1
    linode: go: downloading github.com/tailscale/depaware v0.0.0-20210622194025-720c4b409502
    linode: go: downloading google.golang.org/genproto v0.0.0-20221027153422-115e99e71e1c
    linode: go: downloading github.com/go-logr/logr v1.2.3
    linode: go: downloading github.com/go-errors/errors v1.4.2
    linode: go: downloading github.com/go-git/go-git/v5 v5.4.2
    linode: go: downloading google.golang.org/protobuf v1.28.1
    linode: go: downloading github.com/fatih/color v1.13.0
    linode: go: downloading github.com/sergi/go-diff v1.2.0
    linode: go: downloading github.com/bill-rich/disk-buffer-reader v0.1.4
    linode: go: downloading github.com/google/go-github/v42 v42.0.0
    linode: go: downloading golang.org/x/oauth2 v0.0.0-20221014153046-6fdb5e3db783
    linode: go: downloading golang.org/x/sync v0.1.0
    linode: go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
    linode: go: downloading github.com/alecthomas/units v0.0.0-20211218093645-b94a6e3cc137
    linode: go: downloading github.com/jpillora/s3 v1.1.4
    linode: go: downloading cloud.google.com/go/iam v0.6.0
    linode: go: downloading github.com/googleapis/gax-go/v2 v2.6.0
    linode: go: downloading google.golang.org/api v0.102.0
    linode: go: downloading google.golang.org/grpc v1.50.1
    linode: go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
    linode: go: downloading github.com/pkg/diff v0.0.0-20200914180035-5b29258ca4f7
    linode: go: downloading golang.org/x/tools v0.1.12
    linode: go: downloading github.com/ProtonMail/go-crypto v0.0.0-20210428141323-04723f9f07d7
    linode: go: downloading github.com/go-git/go-billy/v5 v5.3.1
    linode: go: downloading github.com/imdario/mergo v0.3.12
    linode: go: downloading github.com/Azure/go-autorest/autorest/azure/auth v0.5.11
    linode: go: downloading github.com/Azure/go-autorest/autorest v0.11.24
    linode: go: downloading github.com/Azure/go-autorest v14.2.0+incompatible
    linode: go: downloading github.com/bitfinexcom/bitfinex-api-go v0.0.0-20210608095005-9e0b26f200fb
    linode: go: downloading github.com/jlaffaye/ftp v0.1.0
    linode: go: downloading github.com/golang-jwt/jwt v3.2.2+incompatible
    linode: go: downloading github.com/denisenkom/go-mssqldb v0.12.3
    linode: go: downloading github.com/go-sql-driver/mysql v1.6.0
    linode: go: downloading github.com/lib/pq v1.10.7
    linode: go: downloading github.com/mattn/go-sqlite3 v1.14.16
    linode: go: downloading github.com/go-ldap/ldap/v3 v3.4.4
    linode: go: downloading go.mongodb.org/mongo-driver v1.11.0
    linode: go: downloading golang.org/x/crypto v0.0.0-20220926161630-eccd6366d1be
    linode: go: downloading github.com/go-redis/redis v6.15.9+incompatible
    linode: go: downloading github.com/envoyproxy/protoc-gen-validate v0.6.13
    linode: go: downloading github.com/bradleyfalzon/ghinstallation/v2 v2.1.0
    linode: go: downloading golang.org/x/exp v0.0.0-20221018205818-5c77f4b2bbd7
    linode: go: downloading github.com/xanzy/go-gitlab v0.74.0
    linode: go: downloading github.com/aws/aws-sdk-go v1.44.83
    linode: go: downloading github.com/bill-rich/go-syslog v0.0.0-20220413021637-49edb52a574c
    linode: go: downloading github.com/crewjam/rfc5424 v0.1.0
    linode: go: downloading github.com/mattn/go-colorable v0.1.13
    linode: go: downloading github.com/mattn/go-isatty v0.0.16
    linode: go: downloading github.com/emirpasic/gods v1.12.0
    linode: go: downloading github.com/google/go-querystring v1.1.0
    linode: go: downloading github.com/mholt/archiver/v4 v4.0.0-alpha.7
    linode: go: downloading cloud.google.com/go/compute/metadata v0.2.1
    linode: go: downloading cloud.google.com/go/compute v1.12.1
    linode: go: downloading go.opencensus.io v0.23.0
    linode: go: downloading golang.org/x/net v0.1.0
    linode: go: downloading golang.org/x/text v0.4.0
    linode: go: downloading github.com/mitchellh/go-homedir v1.1.0
    linode: go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
    linode: go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.18
    linode: go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.4.5
    linode: go: downloading github.com/Azure/go-autorest/logger v0.2.1
    linode: go: downloading github.com/dimchansky/utfbom v1.1.1
    linode: go: downloading github.com/hashicorp/go-multierror v1.1.1
    linode: go: downloading github.com/golang-sql/civil v0.0.0-20190719163853-cb61b32ac6fe
    linode: go: downloading github.com/golang-sql/sqlexp v0.1.0
    linode: go: downloading github.com/Azure/go-ntlmssp v0.0.0-20220621081337-cb9428e4ac1e
    linode: go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
    linode: go: downloading github.com/youmark/pkcs8 v0.0.0-20181117223130-1be2e3e5546d
    linode: go: downloading github.com/golang-jwt/jwt/v4 v4.4.1
    linode: go: downloading github.com/google/go-github/v45 v45.2.0
    linode: go: downloading golang.org/x/time v0.0.0-20220922220347-f3bd1da661af
    linode: go: downloading github.com/andybalholm/brotli v1.0.4
    linode: go: downloading github.com/dsnet/compress v0.0.1
    linode: go: downloading github.com/golang/snappy v0.0.4
    linode: go: downloading github.com/klauspost/compress v1.15.11
    linode: go: downloading github.com/klauspost/pgzip v1.2.5
    linode: go: downloading github.com/nwaples/rardecode/v2 v2.0.0-beta.2
    linode: go: downloading github.com/pierrec/lz4/v4 v4.1.14
    linode: go: downloading github.com/therootcompany/xz v1.0.1
    linode: go: downloading github.com/ulikunitz/xz v0.5.10
    linode: go: downloading github.com/golang/protobuf v1.5.2
    linode: go: downloading github.com/google/go-cmp v0.5.9
    linode: go: downloading golang.org/x/mod v0.6.0-dev.0.20220419223038-86c51ed26bb4
    linode: go: downloading github.com/go-git/gcfg v1.5.0
    linode: go: downloading github.com/kevinburke/ssh_config v0.0.0-20201106050909-4977a11b4351
    linode: go: downloading github.com/xanzy/ssh-agent v0.3.0
    linode: go: downloading github.com/Azure/go-autorest/tracing v0.6.0
    linode: go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0
    linode: go: downloading github.com/hashicorp/errwrap v1.0.0
    linode: go: downloading github.com/montanaflynn/stats v0.0.0-20171201202039-1bf9dbcd8cbe
    linode: go: downloading github.com/jmespath/go-jmespath v0.4.0
    linode: go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
    linode: go: downloading github.com/googleapis/enterprise-certificate-proxy v0.2.0
    linode: go: downloading gopkg.in/warnings.v0 v0.1.2
    linode: go: downloading github.com/xdg-go/scram v1.1.1
    linode: go: downloading github.com/xdg-go/stringprep v1.0.3
    linode: go: downloading github.com/xdg-go/pbkdf2 v1.0.0
    linode:
==> linode: Provisioning step had errors: Running the cleanup provisioner, if present...
Build 'linode' errored after 46 minutes 35 seconds: Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` or `"valid_exit_codes": [0, 2300218]` to the shell provisioner parameters.

==> Wait completed after 46 minutes 35 seconds

==> Some builds didn't complete successfully and had errors:
--> linode: Script disconnected unexpectedly. If you expected your script to disconnect, i.e. from a restart, you can try adding `"expect_disconnect": true` or `"valid_exit_codes": [0, 2300218]` to the shell provisioner parameters.

==> Builds finished but no artifacts were created.
Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB!
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!
You may need to restart your shell: /usr/bin/bash

**Comment by pdelteil** [comment]
Did you try adding `"expect_disconnect": true` ? 

Also, did you try using the script from a remote instance? (VM/VPS)

**Comment by 0xtavian** [comment]
@catchmeifyoucaan not exactly sure why you getting this error but you only need to submit the request for storage increase once. after axiom opens the support ticket it can take 24 hours for linode support to respond. If you are still running into the error, delete any images listed in https://cloud.linode.com/images and try `axiom-build default` again. Make sure your computer is going to sleep during the build process or run in a tmux session. Going to close this issue but LMK if you cant resolve.
