### ISSUE TITLE
No result for httpx scan due to 'sort: string comparison failed: Illegal byte sequence'

### ISSUE THREAD

**Issue by Se1wan** [pry0cc/axiom#650]
Hi,

I just test axiom and had some problems with getting results from httpx module.

**My command:**
`axiom-scan subdomainFinder.output --fleet subdomains -m httpx -o httpx.output -status-code -title -td -nc`

**My result:**
`...
sort: string comparison failed: Illegal byte sequence
sort: Set LC_ALL='C' to work around the problem.
sort: The strings compared were ‘https://******.com [301] [] [HSTS,Varnish]’ and ‘https://******.fi [200] [Uudelleenohjaus Tapiola-ryhm\344n www-sivuille] [HSTS]’.
`

**The problem:**
The output file httpx.output is empty. So for me it looks like there was a problem while combining all sub-results and sorting them.

Thanks in advance for some help.

Best regards,

 Se1wan

**Comment by pdelteil** [comment]
Hi,

What happens if you run it this way?

`` axiom-scan subdomainFinder.output  -m httpx  --fleet subdomains -o httpx.output -status-code -title -td -nc``

**Comment by 0xtavian** [comment]
https://github.com/pry0cc/axiom/issues/651#issuecomment-1352222634
