### ISSUE TITLE
No results for truffle hog

### ISSUE THREAD

**Issue by Se1wan** [pry0cc/axiom#651]
Hi,

I tried to use axiom with trufflehog (default module). I am confused because I do not get any result. I use the following command:
`axiom-scan input.txt -m trufflehog -o result`
input.txt just contains one line which is trufflesecurity, which will definitely lead to multiple hits. Works if I use truffle hog with same command like module without axiom.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/22847193/207708359-a8ec782f-8925-4cac-b7a6-cd59d7ea8c02.png">
I do not get any results. Within the wiki I do not find any information about how output with directory works and what exactly ** _cleantarget_** is used for.

I would appreciate some information what might be the problem. Thanks in advance!

Best regards,

@54v4n7

**Comment by pdelteil** [comment]
Hi there,

In order to replicate the issue can you post your command running
trufflehog locally? (also the results)

**Comment by 0xtavian** [comment]
Hey @Se1wan sorry for delay in response to your other thread https://github.com/pry0cc/axiom/issues/650#issue-1487566984, where you ever able to fix it? Seems like you just might need to configure `locale`. 


Wrt this issue, can you show me a screenshot of your exact command, including the full axiom banner? I’m looking for the `command:` field, which is the final command executed on each instance after combining the user supplied cli parameters/args with the commands in the module. It makes it easier to troubleshoot. 

Unfortunately, there is a lack of documentation wrt one-shot modules. modules that contain the string `_target_` are always executed as one-shot modules, unless `--disable-oneshot` is used. Basically what this means is we use Interlace syntax to handle the threading of arbitrary applications. Look thru the axiom-scan source code and read the comments in the code to get a better understanding of how it all fits together. Also, reviewing other modules can help understand the syntax as well. You can also find limited information about one-shot modules here https://github.com/pry0cc/axiom/wiki/Horizontal-vs-Vertical-Scaling. 

As for why it’s not working for you, I’m not exactly sure. The module should create a docker container running trufflehog and thread input.txt, but we can see in your run time status “threads” is set to 0. It needs to be at least 1. Can you confirm you are using the same trufflehog module we have in master? (Note you can also change the threads at runtime with `—threads` argument) Can you try with more than one target? Thanks in advance.

**Comment by Se1wan** [comment]
Hi @0xtavian,

you are right, I might have fu**ed up while testing different things which broke the whole thing.
Thanks for your detailed answer!

Best regards
