### ISSUE TITLE
axiom only create 1 fleet

### ISSUE THREAD

**Issue by Nishantbhagat57** [pry0cc/axiom#662]
aciom-fleet only create 1 fleet no matter what number I input.
also it created this: payne22 vm instance which I didn't asked for.

My command:
`axiom-fleet scanners -i=8 -t=5`

┌──(azureuser㉿kali)-[~]
└─$ axiom-fleet scanners -i=8 -t=5
Initializing new fleet 'scanners' with 3 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ scanners02 scanners03 scanners04  ]
Initialized instance 'scanners02' at ''!zation...
Initialized instance 'scanners03' at ''!zation...
Initialized instance 'scanners04' at ''!zation...
Selected: [ scanners01 ]anners initialization...
Fleet started succesfully!
To delete your fleet, just run 'axiom-rm "scanners*" -f'
                                                                                                                                                       
┌──(azureuser㉿kali)-[~]
└─$ axiom-ls                            
Listing instances in account: axiomprofile
Instance    IP              Size              Region        Status      $M
payne22     20.204.177.230  Standard_B1s      centralindia  VM running  5.658385928
scanners01  20.219.60.65    Standard_B1s      centralindia  VM running  5.658385928
kalibbp     4.123.456.49    Standard_D2as_v4  centralindia  VM running  52.23125472
_           _               _                 _             Total       $63.548026576
                                                                                                                                                       
┌──(azureuser㉿kali)-[~]
└─$ axiom-select 'scanners*'      
Selected: [ scanners01 ]
                                                            
![Screenshot 2023-01-05 212535](https://user-images.githubusercontent.com/64642374/210825493-5e5f073c-8855-4d6f-934c-b0e8685fa857.png)

**Comment by 0xtavian** [comment]
Remove the `=`characters. They are no longer required. That’s old syntax. If you run `axiom-fleet -h` there is a help menu with syntax examples. Same with axiom-init.

**Comment by Nishantbhagat57** [comment]
Still it's not working perfectly.
My command: `axiom-fleet scanners -i 10`
But it Initialized just 2 instances.

See output:

┌──(azureuser㉿kali)-[~]
└─$ axiom-fleet scanners -i 10        
Initializing new fleet 'scanners' with 10 instances...
INITIALIZING IN 5 SECONDS, CTRL+C to quit... 
Instances: [ scanners01 scanners02 scanners03 scanners04 scanners05 scanners06 scanners07 scanners08 scanners09 scanners10  ]
Initialized instance 'scanners03' at ''!zation...
Initialized instance 'scanners04' at ''!zation...
Initialized instance 'scanners05' at ''!zation...
Initialized instance 'scanners06' at ''!zation...
Initialized instance 'scanners07' at ''!zation...
Initialized instance 'scanners08' at ''!zation...
Initialized instance 'scanners09' at ''!zation...
Initialized instance 'scanners10' at ''!zation...
Initialized instance 'scanners01' at '52.140.125.31'!
Initialized instance 'scanners02' at '52.140.125.64'!
Selected: [ scanners01 scanners02 ]ialization...
Fleet started succesfully!
To delete your fleet, just run 'axiom-rm "scanners*" -f'
                                                                                               
┌──(azureuser㉿kali)-[~]
└─$ axiom-ls                  
Listing instances in account: axiomprofile
Instance    IP             Size              Region        Status      $M
scanners01  52.140.125.31  Standard_B1s      centralindia  VM running  5.658385928
scanners02  52.140.125.64  Standard_B1s      centralindia  VM running  5.658385928
kalibbp     4.123.123.49   Standard_D2as_v4  centralindia  VM running  52.23125472
_           _              _                 _             Total       $63.548026576
                                                                                        
![Screenshot 2023-01-06 185334](https://user-images.githubusercontent.com/64642374/211021643-c7397ab6-3b9a-4fea-a894-5a9338a62926.png)

**Comment by Nishantbhagat57** [comment]
Error from Azure:

"statusMessage": "{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment 'vm_deploy_IU59PVgaqOlAVTCNHeF9rp9HxSJ32d52' is not valid according to the validation procedure. The tracking id is 'd3b01ac0-3194-47d4-84c4-e0e4787da289'. See inner errors for details.\",\"details\":[{\"code\":\"ResourceCountExceedsLimitDueToTemplate\",\"message\":\"Subscription 9002775a-3426-4281-adf9-30ea81fe71a3 has a quota of 3 for resources of type PublicIpAddress with sku SkuNotSpecified. Subscription currently has 3 resources and the template contains 1 new resources of the this type which exceeds the quota. Please contact support to increase the quota for resource type PublicIpAddress\",\"details\":[]}]}}",

**Comment by Nishantbhagat57** [comment]
So, the error related to my azure subscription. I can only create 3 VMs per subscription as I have student account.
Is there any feature so I can use multiple azure account?
