### ISSUE TITLE
Error : " Control socket  .........disabling multiplexing"

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [pry0cc/axiom#667]
Hello 

I start Getting this Error so much lately.
ControlSocket /home/Tester/.axiom/tmp/nuclei+167335771319090/sockets/op@{{VPS-IP}}-2266 already exists, disabling multiplexing
aspen07 scan was still running but downloading partial results
aspen05 scan was still running but downloading partial results
aspen03 scan was still running but downloading partial results

those this Command : --rm-logs , will solve the Problem ? 

Best Regards

**Comment by 0xtavian** [comment]
@Deku-izuku-dotcom any chance are you running multiple axiom-scan commands in parallel using the same module?
Example:
```
axiom-scan input1 -m nuclei &
axiom-scan input2 -m nuclei 
```

I don’t think `—rm-logs` would fix this but I think I know the issue.

**Comment by Deku-izuku-dotcom** [comment]
No i don't run the commands with & symbol

**Comment by 0xtavian** [comment]
@Deku-izuku-dotcom do you happen to have a command which I could use to recreate this issue?

**Comment by Deku-izuku-dotcom** [comment]
I run a command like this:
Axiom-scan urls.txt -m nuclei --nuclei-template  template.yml --threads 50 

When it finish i run the same command for different list , it start normal , but after some time , show me the error.

**Comment by 0xtavian** [comment]
Ok. Just keep in mind to upload a single template you have to use something like `axiom-scan urls.txt -m nuclei -wL /local/path/to/template.yaml`. For a fix, try adding a few seconds sleep in between the first and second axiom-scan command. Also, make sure you are fully up to date via git pull or `axiom-update`. What OS are you using? 
If you can give me the full terminal output when the error is shown that could be helpful in debugging.

**Comment by Deku-izuku-dotcom** [comment]
@0xtavian I use Ubuntu as OS .
Here is a Screenshot:
![Screenshot from 2023-01-10 18-44-29](https://user-images.githubusercontent.com/55627732/211646646-c97db24c-db3e-430b-918e-973196590fe1.png)

I will run it next time with --debug flag , if it reappear i Will send the logs to you

**Comment by Deku-izuku-dotcom** [comment]
Sorry i truncated when screen it & clear the terminal 🤦.

I will send to you if it shows next time

Best regards

**Comment by Deku-izuku-dotcom** [comment]
I try this solution 
I add flag --rm-logs --rm-when-done .
It work fine
