### ISSUE TITLE
axiom-proxy - Permission denied (publickey)

### ISSUE THREAD

**Issue by RedTeamMagic** [pry0cc/axiom#668]
I'm having trouble getting the axiom-proxy command to function correctly.
I am able to connect to an instance with the keys created, but when I try and run axiom-proxy the command fails and the next line shows a permission denied public key error. I've verified that my axiom_rsa.pub key is in authorized_keys on the host and can perform a standard SSH to the box with them as well.
Any thoughts or ideas appreciated

<img width="391" alt="image" src="https://user-images.githubusercontent.com/48022272/212131216-8ba70343-9f7c-441b-8ed4-9207503210e1.png">

**Comment by 0xtavian** [comment]
@RedTeamMagic yea `axiom-proxy` doesn’t work out of the box. Please see https://github.com/pry0cc/axiom/issues/498 and https://github.com/pry0cc/axiom/issues/532 for potential workarounds. Going to close this issue as a repeat but lmk if you run into any trouble.
