### ISSUE TITLE
Fleet Error

### ISSUE THREAD

**Issue by notakodr** [pry0cc/axiom#671]
I'm getting an error when trying to spin up a fleet on AWS.

An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value () for parameter groupId is invalid. The value cannot be empty

Not sure what I am missing.
Big thanks.

**Comment by 0xtavian** [comment]
@notakodr i just tried AWS with a fresh setup and it’s working for me. What OS are you using? Can you make sure you are on the latest code (`axiom-update`), setup a new account (`axiom-account-setup`) and rebuild (`axiom-build`)?  If you run into an error can you paste the entire terminal output?

**Comment by notakodr** [comment]
I just figured it out... seems I had a conflict with sec groups. Working
now.. Loving the progression to aws...  many thanks.
