### ISSUE TITLE
Cant deploy fleets of 512mb in Digital Ocean

### ISSUE THREAD

**Issue by Tapity04** [pry0cc/axiom#675]
The issue I am reporting is that axiom only creates instances with a minimum of 1GB of memory. When attempting to create instances with 512MB of memory ("s-1vcpu-512mb"), these instances do not initialize.
In some regions this "mini" droplets are not available but in nyc1 (the one that i am testing has them), also didn't find any documentation about this. Is this a known issue/bug?

Cheers

**Comment by 0xtavian** [comment]
@Tapity04 You could try `s-1vcpu-512mb-10gb`, which I found here https://slugs.do-api.dev/. But tbh I wouldn’t recommend it. If it even runs, you’ll likely run out of RAM or disk space quickly, since it only comes with `10 GB`. For very large target lists, I definitely wouldn’t recommend it. For smaller scans, maybe. Lmk if it works for you.

**Comment by Tapity04** [comment]
Hey!, thanks for the quick response, I tried with `s-1vcpu-512mb-10gb` but doesn't seems to work either, is there a way to view the debug after doing axiom-init?

thanks

**Comment by 0xtavian** [comment]
@Tapity04 can you show the error you are getting? To debug you can run `axiom-init` with `—debug`. You might also want to add `set -x` to the top of `$HOME/.axiom/providers/do-functions.sh`. axiom-init and axiom-fleet have easily missed help menus btw `axiom-init —help` `axiom-fleet —help`. You should be able to supply the droplet size via the `—size` cli arg for `axiom-init`. Just remember with DO, if the image doesn’t exist in that region you have to transfer it manually via the doctl cli or build in that region (in this case a region that supports `s-1vcpu-512mb-10gb`).

**Comment by 0xtavian** [comment]
Also check the size of the axiom image isn’t greater than 10GB. It very well might be, especially if you are using the default.json provisioner. You should be able to check the size of the image from doctl or the dashboard.
