### ISSUE TITLE
Axiom-Scan Hanging 

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [pry0cc/axiom#679]
Hello 
I use The Solution you Write in #302  it Work Great but , If i use for example account A & B & use the flag --rm-when-done ,  only the Account B instance will removed after finished & the account A will still there & hanging out the scan forever.

Any Solution   to make It work for them both & Terminate the scan after finish ? 
@0xtavian 

Best Regards

**Comment by 0xtavian** [comment]
Unfortunately no.
