### ISSUE TITLE
Can't change instance type when using AWS

### ISSUE THREAD

**Issue by vitorfhc** [pry0cc/axiom#683]
Hi, I changed the instance type in my `axiom.json` config today, but the changes didn't affect the results.

I think this is the culprit:

https://github.com/pry0cc/axiom/blob/431fe613e2b8135c98406bcaeb704df4e20a0421/providers/aws-functions.sh#L321

We are passing the `--instance-type` with an empty value, which means it will use the type used to build the AMI. It's only possible to change it later by rebuilding the image.

Can we get the type from the config and use it?

**Comment by 0xtavian** [comment]
@vitorfhc yes you are correct! Good catch. We need to take the instance-type from the axiom.json

**Comment by vitorfhc** [comment]
> @vitorfhc yes you are correct! Good catch. We need to take the instance-type from the axiom.json

@0xtavian nice, I'll open a PR soon, can I get assigned to the issue?
