### ISSUE TITLE
Issue with katana module and wilcard expansion

### ISSUE THREAD

**Issue by h49nakxs** [pry0cc/axiom#689]
Hello,

When using the option '-cs' with katana (in scope url regex) like the following :
`axiom-scan domain_list -m katana -cs '*.example.com' -o output`

the scan ends up with the following error :
`zsh:1: no matches found: *.examplecom`

This is because the single quotes around the -cs option in the command line are not replicated in the command run by axiom and thus, zsh tries to expand the wildcard.

As a workaround, "noglob" can be added in front of the command line in the katana module : 
```
[{
	"command":"noglob /home/op/go/bin/katana -u _target_ -o _output_/_cleantarget_",
	"ext":"txt",
	"threads":"3"
}]
```
But there's maybe a better way to correct this.

**Comment by 0xtavian** [comment]
@h49nakxs try this `'-cs \*.example.com'` or try adding the command directly to the module.
