### ISSUE TITLE
seperate output for each domain

### ISSUE THREAD

**Issue by sakyb7** [pry0cc/axiom#696]
Hi team,
Is there any option to get seperate output for each domain.
Examaple: If i scan a list of domain and get output of each domain seperatly

Command:
`axiom-scan all-domain.txt -m waybackurls -o`

output:
`domainName.in.txt domainName.org.txt domainName.com.txt ....`

**Comment by 0xtavian** [comment]
@sakyb7 sorry for the delay. You can do this with a one-shot module. If the module ever contains the string `_target_` it’s executed as a threaded command line application. Look for other modules that have `_target_` for an example. 

this should work but I haven’t tested 
```
[{
	"command":"echo _target_ | /home/op/go/bin/waybackurls | tee output/_cleantarget_",
	"ext":"dir",
        "threads": "2"
}]
```

feel free to change the threads to suit your needs. This creates a separate waybackurls process for each target and saves the output into a unique file named after the target. 

Lmk if you run into any issues.

**Comment by sakyb7** [comment]
Please create a details wiki for createing modules...
