### ISSUE TITLE
install only specific tools on vms

### ISSUE THREAD

**Issue by molitona** [pry0cc/axiom#700]
Hi, sometimes i only need 1 tool to install in all vms like httpx for distributed work but i have to wait 1 hour for all tools to install which is too anoying. pls add an option to choose which tools to install in all vms!

**Comment by 0xtavian** [comment]
Hi @molitona,

the provisioner files are located in `$HOME/.axiom/images/provisioners`. If you copy the `barebones.json` provisioner and add the httpx etc install commands from `default.json` to the copy, you can customize a build. Similarly, you can just delete any tools you don’t want from the default.json file and build with that. 

I was working on something using fzf to give an interactive menu where you can select/deselect what tools you want to install on the fly, but haven’t finished it yet. 

You could also spin up barebones (`axiom-build barebones`), and install tools one at a time with `axiom-exec`

**Comment by molitona** [comment]
ok, thanks for the information!
