### ISSUE TITLE
Better input file split

### ISSUE THREAD

**Issue by vitorfhc** [pry0cc/axiom#701]
Hi,

Yesterday I used Axiom to enumerate a few domains using Amass and found a bug.

I had a wordlist of thirteen lines and ten instances running. Three instances didn't receive an input file.

Let's go through why it happened.

The `split_file` function ([link](https://github.com/pry0cc/axiom/blob/51f8ecf42fa5c9bf0741dd0d6da6a128fbad71bc/interact/axiom-scan#L263)) is responsible for dividing the input into multiple parts, but it must decide how many lines each split will take.

It runs the code below to decide:

```bash
lines_per_file=$(expr $lines / $divisor) # 13 / 10 = 1, so lines_per_file = 1
[[ $(expr $lines % $divisor) != 0 ]] && lines_per_file=$(expr $lines_per_file + 1) # 13 % 10 = 3, so lines_per_file = 2
...
split -l $lines_per_file targets
```

Because of how the `split` command works, the result is the following:

- Six files with two lines each
- One file with one line each

The ideal would be:

- Three files with two lines each
- Seven files with one line each

The first case generates seven files for ten instances, which means three will be wasting money and not performing anything at all.

I want to suggest we build a new `split` function. Let's call it `fair_split`.

It calculates how many lines each file split should have and how many files need to receive an extra line.

```go
lines_per_file = input_lines / instances // lines_per_file = 13 / 10 = 1
files_with_extra_line = input_lines % instances // files_with_extra_line = 13 % 10 = 3
```

In this case, we would write `lines_per_file + 1` lines to `files_with_extra_line` files and `lines_per_file` lines to `instances - files_with_extra_line` files.

The result:

- Three files with two lines each
- Seven files with one line each

In this case, we'd have files for every instance, and all of them would be performing a task.

Please let me know what you think and how complex it'd be to implement this.

**Comment by 0xtavian** [comment]
@vitorfhc thank you :) pushed a fix yesterday. Can you confirm if it works as expected for you? Thanks again.

**Comment by vitorfhc** [comment]
Hey, @0xtavian, thanks a lot for fixing it so quickly!

Unfortunately, I think there's a [bug](https://github.com/pry0cc/axiom/commit/b9dd930bbc5f859c5df53fb729469f7bc112f204#r107909591).

**Comment by 0xtavian** [comment]
Added! @vitorfhc
