### ISSUE TITLE
Using axiom-scan for single target

### ISSUE THREAD

**Issue by cyb3rsalih** [pry0cc/axiom#705]
Hi! I want to use my custom module but getting a little problem.

My script gets 2 parameters  ex:
`script.sh --payloads payloads.txt --target github.com`

I want to split only the payload list. 
So I crafted my module like this

```
command": "/home/op/myscript.sh --payloads _wordlist_ --target input |tee -a output
```
I want to use it like this
```
axiom-scan target.com -m myscript -wD payloads.txt -o results.txt
```

But axiom-scan wants a file as an input.

My question is
**Should I edit my script to get the target parameter from stdin or is there any option to handle this in axiom.**

Thanks.

**Comment by 0xtavian** [comment]
@cyb3rsalih  you are very close! Try this 

`command": "/home/op/myscript.sh --payloads input --target github.com | tee -a output"`

axiom-scan payloads.txt -m module 

If you want to also supply a list of targets this won’t work. You’ll have to use a one-shot module. 

Lmk.

**Comment by cyb3rsalih** [comment]
Thanks 🚀
