### ISSUE TITLE
axiom-scan question about the threading and splitting wordlists

### ISSUE THREAD

**Issue by abdilahrf** [pry0cc/axiom#708]
Using this command : `axiom-scan target.txt -m ffuf -wD ~/Tools/wordlist/all.txt -H "X-Forwarded-For:127.0.0.1" -mc all -fc 404 -ac -sf  -o ffuf.csv`

```
all.txt => 1M wordlist
target.txt => https://google.com
```

axiom will only select 1 instance for scanning, but I was expecting axiom to split the wordlist `all.txt` to multiple instance lets say `5` and it will become `all.txt-1 all.txt-2 all.txt-3 all.txt-4 all.txt-5` each wordlist will have `200k lines` and scan `https://google.com` with `5 instances`.

am i using axiom-scan wrong or this thing is not currently supported yet?

**Comment by amine123ait** [comment]
add ```--fleet instance-name*``` at the end of your command 
Though I get this weird Error after : 
"""
raceback (most recent call last):                                                                                                                                                    File "/usr/local/bin/interlace", line 11, in <module>                                                                                                                                 load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')()                                                                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 34, in main                                                                    File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/threader.py", line 112, in __init__                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func                                               File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 271, in process_data_for_tasks_iterator                                 Exception: No target provided, or empty target list                                                                                                                                 Traceback (most recent call last):                                                                                                                                                    File "/usr/local/bin/interlace", line 11, in <module>                                                                                                                                 load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')()                                                                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 34, in main                                                                    File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/threader.py", line 112, in __init__                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func                                               File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 271, in process_data_for_tasks_iterator                                 Exception: No target provided, or empty target list                                                                                                                                 =====================================================                                                                                                                               Interlace v1.9.8        by Michael Skelton (@codingo_)                                                                                                                                                      & Sajeeb Lohani (@sml555_)                                                                                                                                  =====================================================      
"""
Tell me if you have the same problem.

**Comment by amine123ait** [comment]
> Using this command : `axiom-scan target.txt -m ffuf -wD ~/Tools/wordlist/all.txt -H "X-Forwarded-For:127.0.0.1" -mc all -fc 404 -ac -sf -o ffuf.csv`
> 
> ```
> all.txt => 1M wordlist
> target.txt => https://google.com
> ```
> 
> axiom will only select 1 instance for scanning, but I was expecting axiom to split the wordlist `all.txt` to multiple instance lets say `5` and it will become `all.txt-1 all.txt-2 all.txt-3 all.txt-4 all.txt-5` each wordlist will have `200k lines` and scan `https://google.com` with `5 instances`.
> 
> am i using axiom-scan wrong or this thing is not currently supported yet?

raceback (most recent call last):                                                                                                                                                    File "/usr/local/bin/interlace", line 11, in <module>                                                                                                                                 load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')()                                                                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 34, in main                                                                    File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/threader.py", line 112, in __init__                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func                                               File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 271, in process_data_for_tasks_iterator                                 Exception: No target provided, or empty target list                                                                                                                                 Traceback (most recent call last):                                                                                                                                                    File "/usr/local/bin/interlace", line 11, in <module>                                                                                                                                 load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')()                                                                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 34, in main                                                                    File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/threader.py", line 112, in __init__                                                            File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func                                               File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 271, in process_data_for_tasks_iterator                                 Exception: No target provided, or empty target list                                                                                                                                 =====================================================                                                                                                                               Interlace v1.9.8        by Michael Skelton (@codingo_)                                                                                                                                                      & Sajeeb Lohani (@sml555_)                                                                                                                                  =====================================================

**Comment by 0xdef1ant** [comment]
also wondering this

**Comment by Lengso** [comment]
The default should be to divide the delivery fleet according to the input target. It should be possible to customize a module and use the word list as input

**Comment by 0xtavian** [comment]
@abdilahrf @0xdef1ant sorry for the delay. So this syntax wasn’t supported until the last commit. The relevant issue is here https://github.com/pry0cc/axiom/issues/739#issue-1805303064. 

The syntax atm is (but this not the preferred way of doing this)
```
axiom-scan single-target.txt -m ffuf -wD fuzz.txt -f 'test*' --dont-split -o fuff-output.txt
```
You have to specify the fleet prefix (`-f myfleet*`) and `—dont-split` for this to work.
> Using this command : `axiom-scan target.txt -m ffuf -wD ~/Tools/wordlist/all.txt -H "X-Forwarded-For:127.0.0.1" -mc all -fc 404 -ac -sf -o ffuf.csv`
> 
> ```
> all.txt => 1M wordlist
> target.txt => https://google.com
> ```
> 
> axiom will only select 1 instance for scanning, but I was expecting axiom to split the wordlist `all.txt` to multiple instance lets say `5` and it will become `all.txt-1 all.txt-2 all.txt-3 all.txt-4 all.txt-5` each wordlist will have `200k lines` and scan `https://google.com` with `5 instances`.
> 
> am i using axiom-scan wrong or this thing is not currently supported yet?


thanks @Lengso! And yes this is the preferred!

@abdilahrf @0xdef1ant please see the horizontal versus vertical scanning wiki page. Ideally, the input file should be a wordlist (not a target list) to split and upload. You can then specify the single target in the command-line, or you can hardcode it in the module directly. https://github.com/pry0cc/axiom/wiki/Horizontal-vs-Vertical-Scaling

> The default should be to divide the delivery fleet according to the input target. It should be possible to customize a module and use the word list as input

going to close this but lmk if you have any more issues.
