### ISSUE TITLE
Feature Request - Hashcat

### ISSUE THREAD

**Issue by dltmurphy** [pry0cc/axiom#72]
Is it possible to add Hashcat into Axiom?

**Comment by pry0cc** [comment]
Why would you want to crack a hash on a 1GB DigitalOcean Droplet? If you really want to, you can use `apt-get`.

**Comment by absane** [comment]
Randomly found this and thought i would comment. A better alternative is to rent GPUs from [https://vast.ai/](https://vast.ai/). You can build a quick bash script to launch  an instance, install a hashcat docker container, and get to cracking.

To make things easier, wrap your script around their python tool: https://raw.githubusercontent.com/vast-ai/vast-python/master/vast.py
