### ISSUE TITLE
nuclei install fail

### ISSUE THREAD

**Issue by g0nkg0nk** [pry0cc/axiom#725]
https://github.com/pry0cc/axiom/blob/972a0ef7d565d0efc14a2667e70bb04f710c510f/images/provisioners/default.json#L57
provisioners go version 1.19.1
requires 1.20

$ axiom-exec 'nuclei'
...
nuclei: command not found
...

$ axiom-exec 'go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest'
...
github.com/projectdiscovery/interactsh/pkg/client
\# github.com/projectdiscovery/interactsh/pkg/client
go/pkg/mod/github.com/projectdiscovery/interactsh@v1.1.4/pkg/client/client.go:327:17: undefined: errors.Join
note: module requires Go 1.20
...

temp fix:
```
axiom-exec 'curl https://raw.githubusercontent.com/udhos/update-golang/master/update-golang.sh|sudo bash'
axiom-exec 'go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest'
```

**Comment by patrick-othmer** [comment]
MR for this issue #726

**Comment by pdelteil** [comment]
> https://github.com/pry0cc/axiom/blob/972a0ef7d565d0efc14a2667e70bb04f710c510f/images/provisioners/default.json#L57
> 
> provisioners go version 1.19.1
> requires 1.20
> 
> $ axiom-exec 'nuclei' ... nuclei: command not found ...
> 
> $ axiom-exec 'go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest' ... github.com/projectdiscovery/interactsh/pkg/client # github.com/projectdiscovery/interactsh/pkg/client go/pkg/mod/github.com/projectdiscovery/interactsh@v1.1.4/pkg/client/client.go:327:17: undefined: errors.Join note: module requires Go 1.20 ...
> 
> temp fix:
> 
> ```
> axiom-exec 'curl https://raw.githubusercontent.com/udhos/update-golang/master/update-golang.sh|sudo bash'
> axiom-exec 'go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest'
> ```

Thanks. I had the same issue, you saved me some time!
