### ISSUE TITLE
error initializing builder 'digitalocean': Unknown builder digitalocean

### ISSUE THREAD

**Issue by kusayuzayushko** [pry0cc/axiom#740]
trying to install axiom on EndeavourOS (archlinux family)
![image](https://github.com/pry0cc/axiom/assets/521312/cfb43172-72ac-412d-a611-16ab0df8a2af)

packer version 1.9.2 if that matters

**Comment by 0xtavian** [comment]
Yea @kusayuzayushko I need to fix this. A good description of the issue can be found here. https://github.com/hashicorp/packer/issues/12417
For now, run this to fix:
```
packer plugins install github.com/digitalocean/digitalocean
```

**Comment by 0xtavian** [comment]
#742
