### ISSUE TITLE
Cannot set up with Linode

### ISSUE THREAD

**Issue by jad2121** [pry0cc/axiom#742]
Hi. Thank you guys for the amazing product. i am having a problem with setting up axiom with Linode. I receive this error.

Building image default for provider linode... This can take up to 25 minutes so please be patient!
If this fails, verify the account is properly configured and/or try a different region.
Error: Failed to initialize build "linode"

error initializing builder 'linode': Unknown builder linode

I have already submitted the ticket and received the email back

**Comment by jad2121** [comment]
never mind. I figured it out. I had to run packer plugins install github.com/linode/linode

**Comment by 0xtavian** [comment]
Thanks. Related to this https://github.com/pry0cc/axiom/issues/740#issuecomment-1661414528

**Comment by 0xtavian** [comment]
Fixed setup with https://github.com/pry0cc/axiom/commit/964862d4d077ef3f4b5716bb7e01e00cc4443feb but lmk if you continue to see any issues.
