### ISSUE TITLE
Axiom fleets

### ISSUE THREAD

**Issue by Digita1ocean** [pry0cc/axiom#743]
Im unable to do up to 50 fleets in digitalocean.is there other platforms that allows up to 50 fleets.e.g axiom-fleet test -i=50

**Comment by PR3R00T** [comment]
In DO , Settings -> Team Droplet Limit -> Click on the Number and you can submit a request to increase it.
Worth a shot.

**Comment by 0xtavian** [comment]
@Digita1ocean remove the `=`
 `axiom-fleet test -i 50`
