### ISSUE TITLE
axiom-configure fails on nuclei installation

### ISSUE THREAD

**Issue by kyleavery** [pry0cc/axiom#76]
Hello,

My axiom-configure job has ran three times and failed at the same spot each time.

```
    digitalocean: Installing nuclei
==> digitalocean: go: downloading github.com/projectdiscovery/nuclei v1.1.7
==> digitalocean: go get github.com/projectdiscovery/nuclei/v2/cmd/nuclei: module github.com/projectdiscovery/nuclei@upgrade found (v1.1.7), but does not contain package github.com/projectdiscovery/nuclei/v2/cmd/nuclei
==> digitalocean: Provisioning step had errors: Running the cleanup provisioner, if present...
==> digitalocean: Destroying droplet...
==> digitalocean: Deleting temporary ssh key...
```

**Comment by daehee** [comment]
Having same issue with the `nuclei` line item in packer config, where `go get` attempts to grab an outdated version v1.1.7 -- current version is v2.1.0.

**Comment by kyleavery** [comment]
Created a pull request that uses git clone instead of go get. Works fine for me now. #77

**Comment by daehee** [comment]
@kyleavery did you figure out why the `go get` command isn't working in the build script? The same command works without errors on a fully initialized box.

**Comment by kyleavery** [comment]
@daehee I'm not sure what the issue is, but my Kali box had a different issue using go get with nuclei. The git clone method worked on both.

**Comment by pry0cc** [comment]
Fantastic!  Thank you so much everybody 👍 

I'm tied down right now, but I'm happy to merge any PR that does not have a merge conflict to keep you all going.

**Comment by kyleavery** [comment]
@pry0cc Fixed the merge conflict: #78

**Comment by pry0cc** [comment]
Merged

**Comment by k-sau** [comment]
I am still having problem with it. Anyone else facing the same issue? 
![Screenshot from 2020-09-26 11-54-17](https://user-images.githubusercontent.com/7109945/94332022-0dae1300-ffef-11ea-8f50-d05c74a4f19a.png)

**Comment by sillydadddy** [comment]
I am also having issues with installation . But i am not sure why .

**Comment by k-sau** [comment]
Undoing: https://github.com/pry0cc/axiom/pull/78 fixed the problem

**Comment by pry0cc** [comment]
Niceee
