### ISSUE TITLE
Failed to initialize builder 'digitalocean'

### ISSUE THREAD

**Issue by rew1nter** [pry0cc/axiom#761]
I get this error after running `axiom-build`:
![image](https://github.com/pry0cc/axiom/assets/64508791/fbc636fd-ceb7-4a96-8d51-b217d3974b6d)

**Comment by 0xtavian** [comment]
@rew1nter you are running arch right? It seems like you’ll need to install the DO packer plug-in. `packer plugins install github.com/digitalocean/digitalocean`. I’ll add this to the code for arch installs. If you switch to linode  you’ll have to run  `packer plugins install github.com/linode/linode. 

Related to https://github.com/pry0cc/axiom/issues/740
