### ISSUE TITLE
linode installation setup failed

### ISSUE THREAD

**Issue by rix4uni** [pry0cc/axiom#765]
i tried 4 times also tried different `provisioner` getting same error

![image](https://github.com/pry0cc/axiom/assets/72344025/d06f568a-52a2-4945-97b6-b39b3dca2df8)

**Comment by 0xtavian** [comment]
Hey @rix4uni 
During `axiom-account-setup` for linode you should have been prompted to submit a support ticket to Linode to increase your max image storage allocation to 25GB. It takes about 24 hours for them to respond. Did you do that already? Also make sure you don’t have any images already built (`axiom-images ls`). If you do, you should either select one (`axiom-images set axiom-$provisioner-$timestamp`), or delete the all of them (`axiom-images rm axiom-$provisioner-$timestamp`) and try running `axiom-build default` again.

**Comment by rix4uni** [comment]
Thank you, it worked.
