### ISSUE TITLE
Request failed: 400ull initialization...

### ISSUE THREAD

**Issue by TeddyBlue** [pry0cc/axiom#770]
Cant get past this

Request failed: 400ull initialization...
errors
┌───────┬────────────────────────────────────────────┐
│ field │ reason                                     │
├───────┼────────────────────────────────────────────┤
│ type  │ A valid plan type by that ID was not found │

**Comment by 0xtavian** [comment]
@TeddyBlue what OS are using? How did you install axiom? What cloud provider are you using? Did you run axiom-build yet? If nothing works reinstall with our easy install method, setup the cloud account again and build a fresh image. Going to close this but lmk if you continue to see any issues.
