### ISSUE TITLE
all modules containing _target_ cannot be used

### ISSUE THREAD

**Issue by 1979139113** [pry0cc/axiom#771]
All modules containing `_target_` cannot be used.

When I use the following command, it doesn't work properly.

```
axiom-scan targets.txt -m ffuf_base -o res.txt 
```

<img width="1744" alt="image" src="https://github.com/pry0cc/axiom/assets/24983597/66e1f142-3574-4562-919e-8433137798c8">

`_target_` will be replaced with `_safe-target_`, but it won't be replaced with the target I want to scan.

<img width="411" alt="image" src="https://github.com/pry0cc/axiom/assets/24983597/79c844fe-3a99-4b45-abea-dc13a0efe36d">

**Comment by 0xtavian** [comment]
@1979139113 I think you need to rebuild (`axiom-build default`) or use `axiom-exec` to update the version of interlace on the instances.

**Comment by 1979139113** [comment]
I successfully resolved the issue after updating [Interlace](https://github.com/codingo/Interlace). Thank you very much.
