### ISSUE TITLE
After 9 minutes I get empty results

### ISSUE THREAD

**Issue by alfdav** [pry0cc/axiom#776]
Hello, I am running `axiom-scan start.txt --fleet lefleet --spinup 10 -m subfinder -silent -anew subs.txt --quiet` and after 10 minutes and I just get an empty list, if I run subfinder inside one of the fleet instances it does the job quickly. 

Even if I just run one instance it get's stuck as shown below
![Screenshot 2024-01-06 at 7 10 13 PM](https://github.com/pry0cc/axiom/assets/23536173/f4d6bf0c-bd44-499c-82c5-4e5672dc8257)

then it says is completed and when checking the output file there's nothing, I tried with the `-o` flag instead of `-anew` and nothing. I also tried `-threads 1 `

![Screenshot 2024-01-06 at 7 24 55 PM](https://github.com/pry0cc/axiom/assets/23536173/eab27d17-021c-443e-bbe7-20ade945ac14)

**Comment by 0xtavian** [comment]
You need to update Interlace on the remote instances. You can use `axiom-exec` for that or rebuild the base image `axiom-build default`, for example.

**Comment by alfdav** [comment]
thank you that worked. I found codingo's repo and clone to my image then ran the setup. 

Thank you for the quick answer, support and tool.
