### ISSUE TITLE
 Permission denied (publickey)

### ISSUE THREAD

**Issue by notakodr** [pry0cc/axiom#777]
Hello,

Having difficulty with ssh keys. I have created new keys, uploaded them to DO. Added to .axiom/configs/authorized_keys.

Each time i reinstall from scratch, same issue. Hoping you may have an idea.

Big thanks!

**Comment by ChienNQuang** [comment]
@notakodr can I ask what method did you use to resolve this?

**Comment by notakodr** [comment]
Ended up reinstalling everything from scratch... works like a charm! Axiom
4 Lif3!!!

Respect.

**Comment by 0xtavian** [comment]
Hey @ChienNQuang, check out this part of our FAQ explaining how axiom uses ssh keys https://github.com/pry0cc/axiom/wiki/0-Installation#i-cant-log-in-to-my-droplets-i-get-permission-deniedwrong-password

you could always run `axiom-account-setup` and `axiom-build default` again.

**Comment by ChienNQuang** [comment]
Thanks @0xtavian, @notakodr, I was able to rebuild and made it work. The problem was I couldn't use the same image for different host machines, I had to rebuild one specifically for each host.
