### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by sirkilerot** [pry0cc/axiom#798]
I tried installing axiom with easy install than with git clone but always the same error: i also keep getting errors at setup
![Screenshot_2024-04-22_22-09-23](https://github.com/pry0cc/axiom/assets/153434911/980252fb-5196-40c5-99d8-f5b9470f25f8)
![Screenshot_2024-04-22_22-09-57](https://github.com/pry0cc/axiom/assets/153434911/519c0f19-5d8b-4a6e-9841-cfa07d41a8b1)

**Comment by 0xtavian** [comment]
@sirkilerot what OS are you installing axiom on? There seems to be an issue with the aws cli. Can you make sure the aws cli is probably installed and setup?

**Comment by sirkilerot** [comment]
Ok i reinstalled aws cli and it is working. Thanks for help
