### ISSUE TITLE
How can I run axiom-scan with paramspider

### ISSUE THREAD

**Issue by gpxlnx** [pry0cc/axiom#804]
Hi,

How can run axiom-scan using paramspider module? My doubt is where the result was saved?

**Comment by 0xtavian** [comment]
Hey @gpxlnx, 
The results are downloaded from the remote instances and merged into a final local output folder or file (same with any module). 

If you don’t specify the output file name, it will output to `$(pwd)/scan+$timestamp`
```
axiom-scan input -m paramspider 
```

this will save the output to a user specified directory 
```
axiom-scan input -m paramspider -o myoutput 
```

Closing this issue but lmk if you have any more questions
