### ISSUE TITLE
Feature request: Generate Cloth materials

### ISSUE THREAD

**Issue by Allan-Vonk** [pry0cc/axiom#817]
So for this feature i think it would be really cool if you could generate cloth like materials. I am aware of the Catenary type in the path tool, with wich you can make rope like paths, i think something like this but you can select multiple points and it will fill in the middle.

I hope i described it clearly enough, if not please let me know.

**Comment by 0xtavian** [comment]
Sorry, I’m not sure what you mean. Can you give me an example? @Allan-Vonk

**Comment by Allan-Vonk** [comment]
So what i want to create is something like this, where there is a cloth hanging from some points.
![image](https://github.com/user-attachments/assets/4ebe3a4a-00bd-4877-99ae-132188b254c2)

In this next picture i used the path tool with Catenary type paths. It currently is a looped path, i think it would be really cool if you could make it fill in the middle to create something like the first picture.
![image](https://github.com/user-attachments/assets/65f43b75-bb50-4b73-9ae5-b75cb4495f02)


Then you can easily create hanging cloth like this, i a blink of an eye 
![image](https://github.com/user-attachments/assets/74d07797-c07e-4c76-b9aa-bb0d45e8e217)

**Comment by pdelteil** [comment]
Dude is a bot.

**Comment by Allan-Vonk** [comment]
i got the wrong repository didnt i....
