### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'tqdm==4.36.1' 

### ISSUE THREAD

**Issue by ankushgoel27** [pry0cc/axiom#85]
Hi,

I am seeing an error when in run the axiom-scan command.

![1](https://user-images.githubusercontent.com/10580970/92235242-f76dd500-eed0-11ea-9409-ada83a746e6b.png)

**Comment by pry0cc** [comment]
axiom-scan is not public, hence where there is no documentation in the readme.

If you want axiom-scan to work, currently, you will need to figure out for yourself. Axiom-scan is in a pre-release, unsupported experimental stage reserved only for those who can read bash & debug basic python errors.
