### ISSUE TITLE
Error: (droplet.create.image) command is missing required arguments

### ISSUE THREAD

**Issue by mr3lii** [pry0cc/axiom#90]
I am trying to axiom-init and it is gives me :
Error: (droplet.create.image) command is missing required arguments

**Comment by r4d1k4l** [comment]
```axiom-build``` fixed it for me

**Comment by mr3lii** [comment]
not working with me : 

Your build failed :( Please take a look at the errors!
Builds may fail every now and then, there are some known bugs in Ubuntu Server that cause this.
Im sorry, but it just fails sometimes, just sit back and relax and we'll try again until  it works ;)
Building image axiom... This can take up to 25 minutes so please be patient!
Ocassionally this will fail, we  don't know why, but it should auto-restart.
/.axiom/interact/axiom-build: line 46: packer: command not found

**Comment by r4d1k4l** [comment]
You do not have packer installed. **```packer: command not found```**
You can get it from here: https://learn.hashicorp.com/tutorials/packer/getting-started-install
There are other [dependencies](https://github.com/pry0cc/axiom#dependencies) make sure you have them all installed on your system.

**Comment by mr3lii** [comment]
great, that's solved the issue. 
thanks
