### ISSUE TITLE
axiom-init: command not found

### ISSUE THREAD

**Issue by harleyhacker** [pry0cc/axiom#91]
I've tried multiple time as getting the same outcome. Am I missing anything. I've set this up before and was working last week, now on a new droplet this is what I am receiving with no errors on build.

==> Builds finished. The artifacts of successful builds are:
--> digitalocean: A snapshot was created: 'axiom-sfo2-1599448086' (ID: 69684403) in regions 'sfo2'
Your build completed successfully!
To initialize an instance, run axiom-init
Pruning old Axiom images...
Deleting 'axiom-sfo2-1599445907'...
Old Snapshots deleted successfully!
root@axiombox:~# axiom-init
axiom-init: command not found

**Comment by osamahamad** [comment]
@harleyhacker may u share the solution in case u found it  ?

**Comment by 0xtavian** [comment]
@osamahamad @harleyhacker sometimes sourcing doesnt work. idk why. try to logout and back it and see if that works.
