### ISSUE TITLE
Error: 422 You specified an invalid image for Droplet creation.

### ISSUE THREAD

**Issue by Datacrass** [pry0cc/axiom#92]
==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.

This worked initially. Retried with fresh git clone of repo. Same issue persists.

**Comment by pry0cc** [comment]
Did you run `axiom-build`?

**Comment by Datacrass** [comment]
I had tried running axiom-build and it was successful initially. I was able to resolve the issue by removing all generated Hidden files through usage of the application and retrying.
